const {createHash,createPrivateKey,createPublicKey,randomUUID,sign}=require("node:crypto");
const ENVIRONMENT_ID="matchaphone-d5gjgy87ybfb50382";
const RATE_WINDOW_MS=10*60*1000;
const RATE_MAX_FAILURES=5;
function base64url(value){return Buffer.from(value).toString("base64url")}
function normalizeCode(value){const compact=String(value??"").toUpperCase().replace(/[^A-Z0-9]/g,"");return compact.startsWith("MATCHA")&&compact.length===22?compact:""}
function hashCode(value){return createHash("sha256").update(value).digest("hex")}
function canonicalPayload(payload){return JSON.stringify({version:payload.version,environmentId:payload.environmentId,activationId:payload.activationId,cloudbaseUid:payload.cloudbaseUid,deviceKeyHash:payload.deviceKeyHash,issuedAt:payload.issuedAt,permanent:payload.permanent})}
function publicKeyHash(publicKeyJwk){const key=createPublicKey({key:publicKeyJwk,format:"jwk"}),spki=key.export({format:"der",type:"spki"});return base64url(createHash("sha256").update(spki).digest())}
function validateDevice(device){if(!device||!['p256','installation-secret'].includes(device.method)||typeof device.keyHash!=="string"||!/^[A-Za-z0-9_-]{43}$/.test(device.keyHash))return false;if(device.method==="installation-secret")return !device.publicKeyJwk;try{return device.publicKeyJwk?.kty==="EC"&&device.publicKeyJwk?.crv==="P-256"&&publicKeyHash(device.publicKeyJwk)===device.keyHash}catch{return false}}
function signLicense(payload,privateKeyPem,publicKeyId){const key=createPrivateKey(privateKeyPem.replace(/\\n/g,"\n")),signature=sign("sha256",Buffer.from(canonicalPayload(payload)),{key,dsaEncoding:"ieee-p1363"});return{payload,signature:base64url(signature),publicKeyId}}
function licenseFromRecord(record,privateKeyPem,publicKeyId){const payload={version:1,environmentId:ENVIRONMENT_ID,activationId:record.activationId,cloudbaseUid:record.boundUid,deviceKeyHash:record.deviceKeyHash,issuedAt:record.activatedAt,permanent:true};return signLicense(payload,privateKeyPem,publicKeyId)}
function createActivationService({repository,privateKeyPem,publicKeyId,now=Date.now}){if(!privateKeyPem||!publicKeyId)throw new Error("activation signing configuration missing");async function failure(uid,attempt){const current=attempt&&now()-attempt.windowStartedAt<RATE_WINDOW_MS?attempt:{windowStartedAt:now(),failures:0};await repository.setAttempt(uid,{windowStartedAt:current.windowStartedAt,failures:current.failures+1,updatedAt:now()})}return async function activate({uid,code,requestId,device}){if(!uid)return{ok:false,reason:"unauthenticated"};const attempt=await repository.getAttempt(uid);if(attempt&&now()-attempt.windowStartedAt<RATE_WINDOW_MS&&attempt.failures>=RATE_MAX_FAILURES)return{ok:false,reason:"rate-limited"};const normalized=normalizeCode(code);if(!normalized){await failure(uid,attempt);return{ok:false,reason:"invalid-code"}}if(!validateDevice(device)){await failure(uid,attempt);return{ok:false,reason:"invalid-device"}}const codeHash=hashCode(normalized);let record=await repository.getCode(codeHash);if(!record||record.status==="disabled"||record.status==="replaced"){await failure(uid,attempt);return{ok:false,reason:"invalid-code"}}if(record.status==="activated"){if(record.boundUid===uid&&record.deviceKeyHash===device.keyHash){await repository.clearAttempt(uid);return{ok:true,license:licenseFromRecord(record,privateKeyPem,publicKeyId)}}await failure(uid,attempt);return{ok:false,reason:"already-used"}}const activatedAt=now(),activationId=randomUUID(),claimed=await repository.claimCode(codeHash,{status:"activated",boundUid:uid,deviceMethod:device.method,deviceKeyHash:device.keyHash,publicKeyJwk:device.method==="p256"?device.publicKeyJwk:undefined,activationId,activatedAt,lastRequestId:String(requestId??"").slice(0,100),clientVersion:String(device.clientVersion??"").slice(0,40),updatedAt:activatedAt});if(!claimed){record=await repository.getCode(codeHash);if(record?.status==="activated"&&record.boundUid===uid&&record.deviceKeyHash===device.keyHash){await repository.clearAttempt(uid);return{ok:true,license:licenseFromRecord(record,privateKeyPem,publicKeyId)}}await failure(uid,attempt);return{ok:false,reason:"already-used"}}record={...record,status:"activated",boundUid:uid,deviceKeyHash:device.keyHash,activationId,activatedAt};await repository.clearAttempt(uid);return{ok:true,license:licenseFromRecord(record,privateKeyPem,publicKeyId)}}}
module.exports={ENVIRONMENT_ID,RATE_WINDOW_MS,RATE_MAX_FAILURES,normalizeCode,hashCode,canonicalPayload,publicKeyHash,validateDevice,signLicense,createActivationService};
