import {useRef,useState} from "react";
import {Check,Link2,MessageCircle,Monitor,Moon,Palette,RotateCcw,Smartphone,Sun,Trash2,Type,Upload,UserRound} from "lucide-react";
import {AppTopBar,Modal} from "../components/ui";
import {useNavigate} from "react-router-dom";
import {cloneDefaultAppearance,DESKTOP_APPS} from "../core/appearance";
import {activeAppearanceFont,importAppearanceFont,importAppearanceFontUrl,MAX_APPEARANCE_FONT_BYTES} from "../core/fontAssets";
import {compressImage} from "../core/imageAssets";
import {appearanceSourceUrl,deleteImageAssetIfUnused} from "../core/imageAssetUsage";
import {db,setSetting} from "../core/db";
import {useStore} from "../core/store";
import type {AppearanceChatAvatarShape,AppearanceChatBubbleStyle,AppearanceFont,AppearanceSource,AppearanceThemeMode,DesktopAppId,ImageAsset} from "../core/types";

const builtins=[{name:"纯白",value:"#ffffff"},{name:"雾灰",value:"#f3f3f5"},{name:"柔粉",value:"#fdf1f4"},{name:"燕麦",value:"#f7f4ef"}];
const fontAccept=".ttf,.otf,.woff,.woff2,font/ttf,font/otf,font/woff,font/woff2,application/x-font-ttf,application/x-font-opentype,application/font-woff";
const sizeLabel=(bytes?:number)=>!bytes?"":bytes>=1024*1024?`${(bytes/1024/1024).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`;
const fontDetail=(font:AppearanceFont)=>font.source==="url"?`URL · ${font.format.toUpperCase()}`:`${font.format.toUpperCase()}${font.sizeBytes?` · ${sizeLabel(font.sizeBytes)}`:""}`;

export default function AppearancePage(){
 const nav=useNavigate();
 const {appearance,imageAssets,reload}=useStore(),[urlOpen,setUrlOpen]=useState<"wallpaper"|DesktopAppId|null>(null),[url,setUrl]=useState(""),[fontUrlOpen,setFontUrlOpen]=useState(false),[fontUrl,setFontUrl]=useState(""),[fontName,setFontName]=useState(""),[notice,setNotice]=useState(""),[fontSaving,setFontSaving]=useState(false),[fontScaleDraft,setFontScaleDraft]=useState<number|null>(null),fileRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null),fontRef=useRef<HTMLInputElement>(null),pending=useRef<{purpose:ImageAsset["purpose"];target:"wallpaper"|DesktopAppId}|null>(null);
 if(!appearance)return null;
 const fonts=appearance.fonts??[],activeFont=activeAppearanceFont(appearance),fontScale=fontScaleDraft??appearance.fontScale??1,themeMode=appearance.themeMode??"light",bubbleStyle=appearance.chatBubbleStyle??"default",avatarShape=appearance.chatAvatarShape??"circle";
 const save=async(next=appearance)=>{await setSetting("appearance",next);await reload()};
 const [brokenIcons,setBrokenIcons]=useState<Set<DesktopAppId>>(new Set());
 const chooseTheme=async(mode:AppearanceThemeMode)=>{await save({...appearance,version:16,themeMode:mode})};
 const chooseBubbleStyle=async(style:AppearanceChatBubbleStyle)=>{await save({...appearance,version:16,chatBubbleStyle:style});setNotice(style==="kawaii"?"已切换为奶油粉气泡":"已切换为 iMessage 默认气泡")};
 const chooseAvatarShape=async(shape:AppearanceChatAvatarShape)=>{await save({...appearance,version:16,chatAvatarShape:shape});setNotice(`头像已切换为${shape==="square"?"方形":shape==="rounded"?"圆角方形":"圆形"}`)};
 const commitFontScale=async(value:number)=>{const next=Math.max(.85,Math.min(1.25,Math.round(value*20)/20));setFontScaleDraft(next);await save({...appearance,version:16,fontScale:next});setFontScaleDraft(null);setNotice(`字体大小已调整为 ${Math.round(next*100)}%`)};
 const sourceFor=(asset:ImageAsset):AppearanceSource=>({type:"asset",value:asset.id});
 const choose=async(file?:File)=>{if(!file||!pending.current)return;const request={...pending.current};try{const asset=await compressImage(file,request.purpose),oldSource=request.target==="wallpaper"?appearance.wallpaper:appearance.iconSources[request.target],next=request.target==="wallpaper"?{...appearance,wallpaper:sourceFor(asset)}:{...appearance,iconSources:{...appearance.iconSources,[request.target]:sourceFor(asset)}};await db.transaction("rw",[db.imageAssets,db.settings],async()=>{await db.imageAssets.put(asset);await db.settings.put({key:"appearance",value:next})});setBrokenIcons(current=>{const copy=new Set(current);if(request.target!=="wallpaper")copy.delete(request.target);return copy});await reload();if(oldSource?.type==="asset"&&oldSource.value!==asset.id)void deleteImageAssetIfUnused(oldSource.value);setNotice("图片已压缩并保存在当前设备")}catch(e){setNotice(e instanceof Error?e.message:"图片处理失败")}finally{pending.current=null;if(fileRef.current)fileRef.current.value="";if(cameraRef.current)cameraRef.current.value=""}};
 const addFont=async(font:AppearanceFont)=>{await save({...appearance,version:16,fonts:[...fonts,font],activeFontId:font.id,font:undefined});setNotice(`已添加并应用字体“${font.name}”`)};
 const chooseFont=async(file?:File)=>{if(!file||fontSaving)return;setFontSaving(true);try{await addFont(await importAppearanceFont(file))}catch(e){setNotice(e instanceof Error?e.message:"字体导入失败")}finally{setFontSaving(false);if(fontRef.current)fontRef.current.value=""}};
 const addUrlFont=async()=>{try{const font=importAppearanceFontUrl(fontUrl,fontName);await addFont(font);setFontUrlOpen(false);setFontUrl("");setFontName("")}catch(e){setNotice(e instanceof Error?e.message:"字体 URL 添加失败")}};
 const activateFont=async(id?:string)=>{await save({...appearance,activeFontId:id,font:undefined});setNotice(id?`已切换到“${fonts.find(font=>font.id===id)?.name??"字体"}”`:"已恢复系统默认字体")};
 const removeFont=async(font:AppearanceFont)=>{if(!confirm(`从字体库删除“${font.name}”吗？`))return;const next=fonts.filter(item=>item.id!==font.id),activeFontId=appearance.activeFontId===font.id?undefined:appearance.activeFontId;await save({...appearance,fonts:next,activeFontId,font:undefined});setNotice(`已删除字体“${font.name}”`)};
 const openPicker=(target:"wallpaper"|DesktopAppId,camera=false)=>{pending.current={purpose:target==="wallpaper"?"wallpaper":"icon",target};(camera?cameraRef:fileRef).current?.click()};
 const useUrl=async()=>{if(!urlOpen||!url.trim())return;const target=urlOpen,oldSource=target==="wallpaper"?appearance.wallpaper:appearance.iconSources[target],source:AppearanceSource={type:"url",value:url.trim()};if(target==="wallpaper")await save({...appearance,wallpaper:source});else{setBrokenIcons(current=>{const copy=new Set(current);copy.delete(target);return copy});await save({...appearance,iconSources:{...appearance.iconSources,[target]:source}})}if(oldSource?.type==="asset")void deleteImageAssetIfUnused(oldSource.value);setUrlOpen(null);setUrl("")};
 return <div className="app-page appearance-page"><AppTopBar title="外观" backLabel="返回桌面" onBack={()=>nav("/")}/><div className="appearance-content"><p className="appearance-page-intro">把茶茶机布置成你喜欢的样子</p>
  <section className="settings-section"><div className="section-title"><Palette/><div><h2>壁纸</h2><p>默认纯白，也可以使用自己的图片</p></div></div><div className="swatch-row">{builtins.map(x=><button key={x.value} className={appearance.wallpaper.value===x.value?"active":""} onClick={()=>save({...appearance,wallpaper:{type:"color",value:x.value}})}><i style={{background:x.value}}/><span>{x.name}</span></button>)}</div><div className="appearance-actions"><button onClick={()=>openPicker("wallpaper")}><Upload/>相册</button><button onClick={()=>openPicker("wallpaper",true)}><Smartphone/>相机</button><button onClick={()=>{setUrlOpen("wallpaper");setUrl("")}}><Link2/>URL</button></div></section>
    <section className="settings-section appearance-theme-section"><div className="section-title"><Moon/><div><h2>深夜模式</h2><p>选择浅色、黑粉深夜主题，或自动跟随手机系统</p></div></div><div className="settings-theme-options"><button aria-pressed={themeMode==="light"} className={themeMode==="light"?"active":""} onClick={()=>void chooseTheme("light")}><Sun/><span><b>浅色</b><small>始终使用浅色</small></span></button><button aria-pressed={themeMode==="dark"} className={themeMode==="dark"?"active":""} onClick={()=>void chooseTheme("dark")}><Moon/><span><b>深夜</b><small>始终使用黑粉主题</small></span></button><button aria-pressed={themeMode==="system"} className={themeMode==="system"?"active":""} onClick={()=>void chooseTheme("system")}><Monitor/><span><b>跟随系统</b><small>随手机外观切换</small></span></button></div></section>
  <section className="settings-section chat-bubble-settings-section"><div className="section-title"><MessageCircle/><div><h2>聊天气泡</h2><p>选择默认 iMessage 式气泡或奶油粉气泡</p></div></div><div className="chat-bubble-style-options"><button aria-pressed={bubbleStyle==="default"} className={bubbleStyle==="default"?"active":""} onClick={()=>void chooseBubbleStyle("default")}><div className={`chat-bubble-preview chat-bubble-preview-default preview-avatar-${avatarShape}`}><div className="preview-message preview-theirs"><i className="preview-avatar">茶</i><span className="preview-bubble">晚上好</span><small>21:08</small></div><div className="preview-message preview-mine"><small>21:09</small><span className="preview-bubble">刚刚看到</span></div></div><span className="bubble-style-copy"><b>默认气泡</b><small>iMessage 式蓝灰圆角，无小尾巴</small></span>{bubbleStyle==="default"&&<Check/>}</button><button aria-pressed={bubbleStyle==="kawaii"} className={bubbleStyle==="kawaii"?"active":""} onClick={()=>void chooseBubbleStyle("kawaii")}><div className={`chat-bubble-preview chat-bubble-preview-kawaii preview-avatar-${avatarShape}`}><div className="preview-message preview-theirs"><i className="preview-avatar">茶</i><span className="preview-bubble">晚上好</span><small>21:08</small></div><div className="preview-message preview-mine"><small>21:09</small><span className="preview-bubble">刚刚看到</span></div></div><span className="bubble-style-copy"><b>奶油粉气泡</b><small>奶油黄与柔粉渐变气泡</small></span>{bubbleStyle==="kawaii"&&<Check/>}</button></div></section>
  <section className="settings-section chat-avatar-shape-section"><div className="section-title"><UserRound/><div><h2>聊天头像形状</h2><p>单独控制聊天消息两侧头像的显示形状</p></div></div><div className="chat-avatar-shape-options">{([{value:"square",label:"方形"},{value:"rounded",label:"圆角方形"},{value:"circle",label:"圆形"}] as const).map(option=><button key={option.value} aria-pressed={avatarShape===option.value} className={avatarShape===option.value?"active":""} onClick={()=>void chooseAvatarShape(option.value)}><i className={`avatar-shape-sample ${option.value}`}>茶</i><span>{option.label}</span>{avatarShape===option.value&&<Check/>}</button>)}</div></section>
  <section className="settings-section font-settings-section"><div className="section-title"><Type/><div><h2>字体</h2><p>导入本地文件或字体 URL，并在字体库中切换</p></div></div><div className="font-preview"><small>字体预览</small><strong>茶茶机 Matcha 123</strong><span>{activeFont?`正在使用：${activeFont.name}`:"当前使用系统默认字体"}</span></div><div className="font-size-control"><div className="font-size-head"><span>全局字体大小</span><b>{Math.round(fontScale*100)}%</b></div><div className="font-size-slider"><small>A</small><input aria-label="全局字体大小" type="range" min="85" max="125" step="5" value={Math.round(fontScale*100)} onChange={event=>setFontScaleDraft(Number(event.target.value)/100)} onPointerUp={event=>void commitFontScale(Number(event.currentTarget.value)/100)} onKeyUp={event=>void commitFontScale(Number(event.currentTarget.value)/100)}/><strong>A</strong></div><div className="font-size-presets">{[{label:"小",value:.9},{label:"标准",value:1},{label:"大",value:1.1},{label:"特大",value:1.2}].map(item=><button key={item.label} className={Math.abs(fontScale-item.value)<.01?"active":""} onClick={()=>void commitFontScale(item.value)}>{item.label}</button>)}</div><p>同步调整茶茶机页面中的文字显示，图标和图片大小保持不变。</p></div><div className="appearance-actions"><button disabled={fontSaving} onClick={()=>fontRef.current?.click()}><Upload/>{fontSaving?"导入中…":"本地字体"}</button><button onClick={()=>{setFontUrlOpen(true);setFontUrl("");setFontName("")}}><Link2/>字体 URL</button>{activeFont&&<button onClick={()=>void activateFont()}><RotateCcw/>系统默认</button>}</div><div className="font-library-head"><b>字体库</b><small>{fonts.length} 个字体</small></div>{fonts.length?<div className="font-library">{fonts.map(font=><article key={font.id} className={font.id===appearance.activeFontId?"active":""}><button className="font-library-main" onClick={()=>void activateFont(font.id)}><span>{font.id===appearance.activeFontId?<Check/>:<Type/>}</span><div><b>{font.name}</b><small>{fontDetail(font)}</small>{font.source==="url"&&<em>{font.url}</em>}</div></button><button className="font-delete" aria-label={`删除字体${font.name}`} onClick={()=>void removeFont(font)}><Trash2/></button></article>)}</div>:<div className="font-library-empty">还没有导入字体，可以从本地文件或 URL 添加。</div>}<p className="font-limit-note">本地字体会进入备份，单个文件最大 {MAX_APPEARANCE_FONT_BYTES/1024/1024}MB；URL 字体仅保存链接，并需要服务器允许跨域加载。</p></section>
  <section className="settings-section"><div className="section-title"><Smartphone/><div><h2>应用图标</h2><p>每个应用可以单独使用图片或 URL</p></div></div><div className="icon-custom-list">{DESKTOP_APPS.map(app=>{const Icon=app.icon,custom=appearance.iconSources[app.id],src=brokenIcons.has(app.id)?undefined:appearanceSourceUrl(custom,imageAssets);return <div key={app.id}><span className="mini-app-icon">{src?<img key={src} src={src} alt={`${app.name}图标`} onError={()=>{setBrokenIcons(current=>new Set(current).add(app.id));setNotice(`${app.name}图标无法载入，已显示默认图标`)}}/>:<Icon/>}</span><b>{app.name}</b><button type="button" onClick={()=>openPicker(app.id)}>相册</button><button type="button" onClick={()=>{setUrlOpen(app.id);setUrl("")}}>URL</button>{custom&&<button type="button" className="icon-reset-button" aria-label={`恢复${app.name}默认图标`} onClick={async()=>{const next={...appearance.iconSources},old=next[app.id];delete next[app.id];setBrokenIcons(current=>{const copy=new Set(current);copy.delete(app.id);return copy});await save({...appearance,iconSources:next});if(old?.type==="asset")void deleteImageAssetIfUnused(old.value)}}><RotateCcw/></button>}</div>})}</div></section>
  <button className="danger secondary-action" onClick={async()=>{if(confirm("只恢复默认外观和桌面布局？角色与消息不会受到影响。")){await db.imageAssets.clear();await save(cloneDefaultAppearance())}}}><Trash2/>恢复默认外观</button>{notice&&<p className="appearance-notice">{notice}</p>}
 </div><input ref={fileRef} hidden type="file" accept="image/*" onClick={e=>{e.currentTarget.value=""}} onChange={e=>void choose(e.target.files?.[0])}/><input ref={cameraRef} hidden type="file" accept="image/*" capture="environment" onClick={e=>{e.currentTarget.value=""}} onChange={e=>void choose(e.target.files?.[0])}/><input ref={fontRef} hidden type="file" accept={fontAccept} onClick={e=>{e.currentTarget.value=""}} onChange={e=>void chooseFont(e.target.files?.[0])}/> {urlOpen&&<Modal onClose={()=>setUrlOpen(null)}><div className="sheet-head"><div><small>IMAGE URL</small><h2>使用网络图片</h2></div><button onClick={()=>setUrlOpen(null)}>×</button></div><label className="field"><span>图片地址</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/image.jpg"/></label><p className="form-note">仅保存链接；图片无法加载时会自动显示默认样式。</p><button className="primary" onClick={useUrl}>使用这个地址</button></Modal>}
 {fontUrlOpen&&<Modal onClose={()=>setFontUrlOpen(false)}><div className="sheet-head"><div><small>FONT URL</small><h2>添加网络字体</h2></div><button onClick={()=>setFontUrlOpen(false)}>×</button></div><div className="simple-form font-url-form"><label>字体名称（可选）<input value={fontName} onChange={e=>setFontName(e.target.value)} placeholder="例如：圆体"/></label><label>字体文件 URL<input value={fontUrl} onChange={e=>setFontUrl(e.target.value)} placeholder="https://example.com/font.woff2"/></label><p className="form-note">链接需直接指向 TTF、OTF、WOFF 或 WOFF2 文件，并允许网页跨域加载。</p><button className="primary" onClick={()=>void addUrlFont()}>添加并使用</button></div></Modal>}
 </div>
}
