import {useEffect,useRef,useState} from "react";
import {ArrowLeft,BookOpen,Camera,Check,RefreshCw,Search,Trash2,UserPlus,Users,X} from "lucide-react";
import {Navigate,useNavigate,useParams} from "react-router-dom";
import {Avatar,Empty} from "../components/ui";
import {contactStatusOf} from "../core/conversationSettings";
import {markCharacterAsFriend,markCharactersAsFriends} from "../core/contacts";
import {db} from "../core/db";
import {addGroupMembers} from "../core/groupFeatures";
import {completeGroupNpcProfile,createGroupNpcDraft} from "../core/groupNpcs";
import {deleteMediaIfUnused,saveImageMedia} from "../core/mediaAssets";
import {useStore} from "../core/store";
import {defaultProvider,now,SCHEMA_VERSION,uid,type Character,type GroupNpc,type ProviderSettings} from "../core/types";

function FlowShell({title,subtitle,back,children,action}:{title:string;subtitle?:string;back:string;children:React.ReactNode;action?:React.ReactNode}){const nav=useNavigate();return <div className="message-flow-page"><header><button aria-label="返回" onClick={()=>nav(back)}><ArrowLeft/></button><div><b>{title}</b>{subtitle&&<small>{subtitle}</small>}</div>{action??<span/>}</header><main>{children}</main></div>}
function selectableRows(characters:Character[],picked:Set<string>,toggle:(id:string)=>void){return <div className="message-flow-people">{characters.map(character=><button key={character.id} className={picked.has(character.id)?"selected":""} onClick={()=>toggle(character.id)}><Avatar text={character.name} src={character.avatar}/><span><b>{character.name}</b><small>{character.coreSetting??character.bio??"角色"}</small></span><i>{picked.has(character.id)&&<Check/>}</i></button>)}</div>}
function ToggleTabs({value,onChange}:{value:"character"|"npc";onChange:(value:"character"|"npc")=>void}){return <div className="group-member-tabs"><button className={value==="character"?"active":""} onClick={()=>onChange("character")}>角色</button><button className={value==="npc"?"active":""} onClick={()=>onChange("npc")}>NPC</button></div>}
function NpcAvatar({npc}:{npc:GroupNpc}){const [src,setSrc]=useState("");useEffect(()=>{if(!npc.avatarAssetId){setSrc("");return}void db.mediaAssets.get(npc.avatarAssetId).then(asset=>setSrc(asset?.data??""))},[npc.avatarAssetId]);return <Avatar text={npc.name||"N"} src={src||undefined}/>}

function NpcForm({provider,initial,onSave,onCancel}:{provider:ProviderSettings;initial?:GroupNpc;onSave:(npc:GroupNpc)=>void;onCancel:()=>void}){
 const [draft,setDraft]=useState<GroupNpc>(()=>createGroupNpcDraft(initial)),[avatarUrl,setAvatarUrl]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const initialAsset=initial?.avatarAssetId??"",committed=useRef(false);
 useEffect(()=>{if(draft.avatarAssetId)void db.mediaAssets.get(draft.avatarAssetId).then(asset=>setAvatarUrl(asset?.data??""))},[]);
 useEffect(()=>()=>{if(!committed.current&&draft.avatarAssetId&&draft.avatarAssetId!==initialAsset)void deleteMediaIfUnused(draft.avatarAssetId)},[draft.avatarAssetId,initialAsset]);
 const patch=(value:Partial<GroupNpc>)=>setDraft(current=>({...current,...value,updatedAt:now()}));
 const upload=async(file?:File)=>{if(!file)return;const old=draft.avatarAssetId,asset=await saveImageMedia(file,"group-npc-avatar");patch({avatarAssetId:asset.id});setAvatarUrl(asset.data);if(old&&old!==initialAsset)await deleteMediaIfUnused(old)};
 const removeAvatar=async()=>{const old=draft.avatarAssetId;patch({avatarAssetId:undefined});setAvatarUrl("");if(old&&old!==initialAsset)await deleteMediaIfUnused(old)};
 const complete=async()=>{if(!draft.name.trim()){setError("请先填写 NPC 姓名。 ");return}setBusy(true);setError("");try{const result=await completeGroupNpcProfile(provider,draft);patch(result)}catch(reason){setError(reason instanceof Error?reason.message:"AI 补全失败，已保留手动内容。") }finally{setBusy(false)}};
 const save=()=>{if(!draft.name.trim()||!draft.persona.trim()){setError("请填写姓名和性格人设，或使用 AI 补全。 ");return}committed.current=true;onSave({...draft,name:draft.name.trim().slice(0,30),age:draft.age?.trim().slice(0,30),identity:draft.identity?.trim().slice(0,80),basicInfo:draft.basicInfo?.trim().slice(0,500),persona:draft.persona.trim().slice(0,800),speakingStyle:draft.speakingStyle?.trim().slice(0,300),active:true,updatedAt:now()})};
 return <section className="group-npc-editor"><header><div><b>{initial?"编辑 NPC":"新建群聊 NPC"}</b><small>只属于当前群聊，不会进入通讯录或论坛</small></div><button aria-label="关闭" onClick={onCancel}><X/></button></header><div className="group-npc-avatar-row"><label><span>{avatarUrl?<img src={avatarUrl} alt="NPC 头像"/>:<Avatar text={draft.name||"N"}/>}</span><em><Camera/>上传头像<input hidden type="file" accept="image/*" onChange={event=>void upload(event.target.files?.[0])}/></em></label>{draft.avatarAssetId&&<button onClick={()=>void removeAvatar()}><Trash2/>移除</button>}</div><div className="group-npc-fields"><label>姓名<input maxLength={30} value={draft.name} onChange={event=>patch({name:event.target.value})} placeholder="必填"/></label><label>年龄<input maxLength={30} value={draft.age??""} onChange={event=>patch({age:event.target.value})} placeholder="例如 24、未知、数百岁"/></label><label>身份或职业<input maxLength={80} value={draft.identity??""} onChange={event=>patch({identity:event.target.value})} placeholder="例如 咖啡店店员"/></label><label>基础信息<textarea rows={3} maxLength={500} value={draft.basicInfo??""} onChange={event=>patch({basicInfo:event.target.value})} placeholder="经历、关系、喜好等"/></label><label>性格与人设<textarea rows={5} maxLength={800} value={draft.persona} onChange={event=>patch({persona:event.target.value})} placeholder="先简单概括，再让 AI 补全"/></label><label>说话风格<textarea rows={3} maxLength={300} value={draft.speakingStyle??""} onChange={event=>patch({speakingStyle:event.target.value})} placeholder="AI 补全后也可以继续编辑"/></label></div>{error&&<p className="group-npc-error">{error}</p>}<footer><button className="group-npc-ai" disabled={busy} onClick={()=>void complete()}><RefreshCw className={busy?"spin":""}/>{busy?"补全中":"AI 补全人设"}</button><button className="group-npc-save" onClick={save}>添加 NPC</button></footer></section>
}

export function AddFriendsPage(){const nav=useNavigate(),{characters,reload}=useStore(),[query,setQuery]=useState(""),[picked,setPicked]=useState<Set<string>>(new Set()),rows=characters.filter(character=>contactStatusOf(character)==="not-added"&&`${character.name} ${character.bio} ${character.coreSetting??""}`.toLowerCase().includes(query.toLowerCase())),toggle=(id:string)=>setPicked(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next}),save=async()=>{await markCharactersAsFriends(picked);await reload();nav("/messages/contacts")};return <FlowShell title="添加好友" subtitle={`${picked.size} 个已选择`} back="/messages/contacts" action={<button className="message-flow-done" disabled={!picked.size} onClick={()=>void save()}>添加</button>}><label className="message-flow-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索角色"/></label>{rows.length?selectableRows(rows,picked,toggle):<Empty icon={<UserPlus size={40}/>} title="没有待添加角色" text="在角色 App 新建或导入角色后，会显示在这里。"/>}</FlowShell>}
export function FriendRequestsPage(){const {characters,reload}=useStore(),requests=characters.filter(character=>character.contactState?.status==="request-pending"&&character.contactState.friendRequest?.status==="pending"),handle=async(character:Character,accept:boolean)=>{if(accept)await markCharacterAsFriend(character.id);else await db.characters.update(character.id,{contactState:{status:"blocked",blockedAt:character.contactState?.blockedAt??now()},updatedAt:now()});await reload()};return <FlowShell title="好友申请" subtitle={`${requests.length} 条待处理`} back="/messages/contacts">{requests.length?<div className="friend-request-page-list">{requests.map(character=><article key={character.id}><Avatar text={character.name} src={character.avatar}/><div><b>{character.name}</b><time>{new Date(character.contactState!.friendRequest!.createdAt).toLocaleString("zh-CN")}</time><p>{character.contactState!.friendRequest!.message||"想重新添加你为好友。"}</p>{character.contactState?.blockedAt&&<small>该角色此前已被你拉黑，接受后将恢复聊天权限。</small>}</div><footer><button onClick={()=>void handle(character,false)}>拒绝</button><button className="primary" onClick={()=>void handle(character,true)}>接受</button></footer></article>)}</div>:<Empty icon={<UserPlus size={40}/>} title="没有新的好友申请" text="被拉黑的角色再次申请时，申请理由会显示在这里。"/>}</FlowShell>}

export function GroupCreatePage(){
 const nav=useNavigate(),{characters,loreBooks,provider,reload}=useStore(),friends=characters.filter(character=>contactStatusOf(character)==="friend"),[title,setTitle]=useState(""),[picked,setPicked]=useState<Set<string>>(new Set()),[books,setBooks]=useState<Set<string>>(new Set()),[npcs,setNpcs]=useState<GroupNpc[]>([]),[tab,setTab]=useState<"character"|"npc">("character"),[editingNpc,setEditingNpc]=useState(false),[userInGroup,setUserInGroup]=useState(true),[avatarId,setAvatarId]=useState(""),[avatarUrl,setAvatarUrl]=useState(""),[saving,setSaving]=useState(false),committed=useRef(false),avatarRef=useRef(""),npcRef=useRef<GroupNpc[]>([]);
 useEffect(()=>{avatarRef.current=avatarId;npcRef.current=npcs},[avatarId,npcs]);
 useEffect(()=>()=>{if(!committed.current){if(avatarRef.current)void deleteMediaIfUnused(avatarRef.current);for(const npc of npcRef.current)if(npc.avatarAssetId)void deleteMediaIfUnused(npc.avatarAssetId)}},[]);
 const toggle=(current:Set<string>,id:string,setter:(value:Set<string>)=>void)=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);setter(next)};
 const upload=async(file?:File)=>{if(!file)return;const old=avatarId,asset=await saveImageMedia(file,"group-avatar");setAvatarId(asset.id);setAvatarUrl(asset.data);if(old)await deleteMediaIfUnused(old)};
 const remove=async()=>{const old=avatarId;setAvatarId("");setAvatarUrl("");if(old)await deleteMediaIfUnused(old)};
 const total=picked.size+npcs.length;
 const create=async()=>{if(total<2||!title.trim()||saving)return;setSaving(true);const t=now(),id=uid();await db.conversations.add({id,schemaVersion:SCHEMA_VERSION,createdAt:t,updatedAt:t,title:title.trim().slice(0,30),type:"group",memberIds:[...picked],groupNpcs:npcs,presetIds:[],loreBookIds:[...books],lastActivityAt:t,avatarAssetId:avatarId||undefined,chatSettings:{bubbleStyle:"inherit",characterAvatarSize:36,fontScale:92,userInGroup,permissions:{proactiveChatImage:false,proactiveVoiceCall:false,proactiveVideoCall:false,proactiveMeetInvitation:false,proactiveSticker:false},proactiveStickerPackIds:[]}});committed.current=true;await reload();nav(`/messages/${id}`)};
 return <FlowShell title="发起群聊" subtitle={`${total} 位成员`} back="/messages/contacts" action={<button className="message-flow-done" disabled={total<2||!title.trim()||saving} onClick={()=>void create()}>{saving?"创建中":"创建"}</button>}><section className="group-create-profile"><label className="group-avatar-upload"><span>{avatarUrl?<img src={avatarUrl} alt="群头像"/>:<Users/>}</span><em><Camera/>更换头像<input hidden type="file" accept="image/*" onChange={event=>void upload(event.target.files?.[0])}/></em></label>{avatarId&&<button onClick={()=>void remove()}><Trash2/>移除头像</button>}<label>群聊名称<input maxLength={30} value={title} onChange={event=>setTitle(event.target.value)} placeholder="输入群聊名称"/></label></section><ToggleTabs value={tab} onChange={setTab}/>{tab==="character"?<section className="message-flow-section"><header><b>选择角色成员</b><span>{picked.size} 人</span></header>{friends.length?selectableRows(friends,picked,id=>toggle(picked,id,setPicked)):<Empty icon={<Users size={36}/>} title="通讯录还没有好友" text="可以切换到 NPC 创建群专属成员。"/>}</section>:<section className="message-flow-section group-npc-section"><header><b>群专属 NPC</b><button onClick={()=>setEditingNpc(true)}>+ 新建 NPC</button></header>{npcs.length?<div className="group-npc-list">{npcs.map(npc=><article key={npc.id}><NpcAvatar npc={npc}/><span><b>{npc.name}</b><small>{npc.identity||npc.persona}</small></span><button aria-label="移除 NPC" onClick={()=>{setNpcs(current=>current.filter(item=>item.id!==npc.id));if(npc.avatarAssetId)void deleteMediaIfUnused(npc.avatarAssetId)}}><X/></button></article>)}</div>:<Empty icon={<UserPlus size={36}/>} title="还没有 NPC" text="填写基础资料后，可以使用 AI 补全性格和说话风格。"/>}{editingNpc&&<NpcForm provider={provider??defaultProvider} onCancel={()=>setEditingNpc(false)} onSave={npc=>{setNpcs(current=>[...current,npc]);setEditingNpc(false)}}/>}</section>}<section className="message-flow-section"><header><b>挂载世界书</b><span>{books.size} 本</span></header><div className="message-flow-books">{loreBooks.length?loreBooks.map(book=><button key={book.id} className={books.has(book.id)?"selected":""} onClick={()=>toggle(books,book.id,setBooks)}><BookOpen/><span><b>{book.name}</b><small>{book.entries.length} 条设定</small></span><i>{books.has(book.id)&&<Check/>}</i></button>):<p>暂无世界书，可以创建群聊后再添加。</p>}</div></section><label className="message-flow-toggle"><span><b>用户在群内</b><small>关闭后进入上帝视角，你的输入会成为仅你可见的幕后指导。</small></span><input type="checkbox" checked={userInGroup} onChange={event=>setUserInGroup(event.target.checked)}/><i/></label></FlowShell>
}

export function GroupMemberInvitePage(){
 const {id}=useParams(),nav=useNavigate(),{conversations,characters,provider,reload}=useStore(),conversation=conversations.find(item=>item.id===id),candidates=characters.filter(character=>contactStatusOf(character)==="friend"&&!conversation?.memberIds.includes(character.id)),inactive=(conversation?.groupNpcs??[]).filter(npc=>!npc.active),[picked,setPicked]=useState<Set<string>>(new Set()),[pickedNpcs,setPickedNpcs]=useState<Set<string>>(new Set()),[newNpcs,setNewNpcs]=useState<GroupNpc[]>([]),[tab,setTab]=useState<"character"|"npc">("character"),[editingNpc,setEditingNpc]=useState(false),[busy,setBusy]=useState(false),committed=useRef(false),newNpcRef=useRef<GroupNpc[]>([]);
 useEffect(()=>{newNpcRef.current=newNpcs},[newNpcs]);
 useEffect(()=>()=>{if(!committed.current)for(const npc of newNpcRef.current)if(npc.avatarAssetId)void deleteMediaIfUnused(npc.avatarAssetId)},[]);
 const toggle=(setter:React.Dispatch<React.SetStateAction<Set<string>>>,value:string)=>setter(current=>{const next=new Set(current);next.has(value)?next.delete(value):next.add(value);return next});
 if(!conversation||conversation.type!=="group")return <Navigate to="/messages/chats" replace/>;
 const total=picked.size+pickedNpcs.size+newNpcs.length;
 const add=async()=>{if(!total)return;setBusy(true);const reactivated=inactive.filter(npc=>pickedNpcs.has(npc.id)).map(npc=>({...npc,active:true,updatedAt:now()}));await addGroupMembers({conversation,memberIds:[...picked],npcs:[...reactivated,...newNpcs],provider:provider??undefined});committed.current=true;await reload();nav(`/messages/${conversation.id}`)};
 return <FlowShell title="邀请新成员" subtitle={`${total} 个已选择`} back={`/messages/${conversation.id}/settings`} action={<button className="message-flow-done" disabled={!total||busy} onClick={()=>void add()}>{busy?"邀请中":"邀请"}</button>}><ToggleTabs value={tab} onChange={setTab}/>{tab==="character"?(candidates.length?selectableRows(candidates,picked,id=>toggle(setPicked,id)):<Empty icon={<Users size={40}/>} title="没有可邀请的角色" text="通讯录中的好友都已经在群聊中。"/>):<section className="message-flow-section group-npc-section"><header><b>群专属 NPC</b><button onClick={()=>setEditingNpc(true)}>+ 新建 NPC</button></header>{inactive.length>0&&<><small className="group-npc-subtitle">曾在本群的 NPC</small><div className="group-npc-list">{inactive.map(npc=><button key={npc.id} className={pickedNpcs.has(npc.id)?"selected":""} onClick={()=>toggle(setPickedNpcs,npc.id)}><NpcAvatar npc={npc}/><span><b>{npc.name}</b><small>{npc.identity||npc.persona}</small></span><i>{pickedNpcs.has(npc.id)&&<Check/>}</i></button>)}</div></>}{newNpcs.length>0&&<><small className="group-npc-subtitle">本次新建</small><div className="group-npc-list">{newNpcs.map(npc=><article key={npc.id}><NpcAvatar npc={npc}/><span><b>{npc.name}</b><small>{npc.identity||npc.persona}</small></span><button onClick={()=>{setNewNpcs(current=>current.filter(item=>item.id!==npc.id));if(npc.avatarAssetId)void deleteMediaIfUnused(npc.avatarAssetId)}}><X/></button></article>)}</div></>}{!inactive.length&&!newNpcs.length&&!editingNpc&&<Empty icon={<UserPlus size={36}/>} title="创建群专属 NPC" text="NPC 只属于当前群聊，可以正常聊天、投票和抢红包。"/>}{editingNpc&&<NpcForm provider={provider??defaultProvider} onCancel={()=>setEditingNpc(false)} onSave={npc=>{setNewNpcs(current=>[...current,npc]);setEditingNpc(false)}}/>}</section>}</FlowShell>
}
