import {Ban,MessageCircleMore,UserPlus,Users} from "lucide-react";
import {useState} from "react";
import {useNavigate} from "react-router-dom";
import {Avatar,Empty} from "../components/ui";
import {contactStatusOf} from "../core/conversationSettings";
import {ensurePrivateConversation} from "../core/contacts";
import {useStore} from "../core/store";

export default function ContactsTab(){
 const nav=useNavigate(),{characters,reload}=useStore(),[openingId,setOpeningId]=useState(""),[openError,setOpenError]=useState(""),requests=characters.filter(character=>character.contactState?.status==="request-pending"&&character.contactState.friendRequest?.status==="pending"),pending=characters.filter(character=>contactStatusOf(character)==="not-added"),blocked=characters.filter(character=>contactStatusOf(character)==="blocked"),rows=characters.filter(character=>contactStatusOf(character)==="friend");
 const chat=async(characterId:string)=>{if(openingId)return;setOpeningId(characterId);setOpenError("");try{const conversation=await ensurePrivateConversation(characterId);await reload();nav(`/messages/${conversation.id}`)}catch(error){setOpenError(error instanceof Error?error.message:"无法打开聊天，请重试")}finally{setOpeningId("")}};
 return <div className="social-scroll contacts-tab contacts-simple"><section className="contact-action-grid"><button onClick={()=>nav("/messages/contacts/add")}><span><UserPlus/></span><b>添加好友</b><small>{pending.length?`${pending.length} 个角色待添加`:"从角色 App 选择"}</small></button><button onClick={()=>nav("/messages/contacts/requests")}><span><MessageCircleMore/></span><b>好友申请</b><small>{requests.length?`${requests.length} 条待处理`:"暂无新申请"}</small>{requests.length>0&&<i>{requests.length}</i>}</button><button onClick={()=>nav("/messages/group/new")}><span><Users/></span><b>发起群聊</b><small>选择好友与世界书</small></button></section>{openError&&<p className="form-error contact-open-error" role="alert">{openError}</p>}<section className="contact-section"><h3>联系人 <span>{rows.length}</span></h3>{rows.length?<div className="contact-list">{rows.map(character=><button className="contact-row" key={character.id} disabled={Boolean(openingId)} onClick={()=>void chat(character.id)}><Avatar text={character.name} src={character.avatar}/><span className="contact-main"><b>{character.name}</b><small>{openingId===character.id?"正在打开聊天…":character.coreSetting??character.bio??"开始一段对话"}</small></span></button>)}</div>:<Empty icon={<MessageCircleMore size={42}/>} title="还没有联系人" text="先从上方“添加好友”选择角色。"/>}</section>{blocked.length>0&&<section className="contact-section blocked-contact-section"><h3>已拉黑 <span>{blocked.length}</span></h3>{blocked.map(character=><button className="contact-row" key={character.id} onClick={()=>void chat(character.id)}><Avatar text={character.name} src={character.avatar}/><span className="contact-main"><b>{character.name}</b><small><Ban/> 聊天只读</small></span></button>)}</section>}</div>;
}