import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowLeft,BookOpen,Check,ChevronDown,Clock3,ImagePlus,Plus,RefreshCw,Save,Sparkles,Trash2,Upload,Users,X} from "lucide-react";
import {Navigate,useNavigate,useParams} from "react-router-dom";
import {Avatar,Modal} from "../components/ui";
import {createForumCommunity,defaultForumActivitySettings,deleteForumCommunity,generateForumNpcProfile,normalizeForumServer,runForumGeneration,updateForumCommunity} from "../core/forum";
import {db} from "../core/db";
import {deleteMediaIfUnused,saveImageMedia} from "../core/mediaAssets";
import {useStore} from "../core/store";
import {now,uid,type ForumActivitySettings,type ForumImageSource,type ForumNpc,type ForumServer} from "../core/types";

type Props={mode:"create"|"settings"};
const blankNpc=():ForumNpc=>({id:uid(),name:"",persona:"",enabled:true,createdAt:now(),updatedAt:now()});
function sourceUrl(source:ForumImageSource|undefined,assets:Map<string,string>){return source?.type==="asset"?assets.get(source.value)??"":source?.value??""}
function Toggle({title,note,checked,onChange}:{title:string;note?:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="forum-editor-toggle"><span><b>{title}</b>{note&&<small>{note}</small>}</span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><i/></label>}

export default function ForumEditorPage({mode}:Props){
 const {serverId}=useParams(),nav=useNavigate(),{characters,loreBooks,provider,settings,reload}=useStore(),[loaded,setLoaded]=useState(mode==="create"),[server,setServer]=useState<ForumServer|null>(null),[name,setName]=useState(""),[description,setDescription]=useState(""),[introduction,setIntroduction]=useState(""),[iconText,setIconText]=useState(""),[color,setColor]=useState("#777a80"),[avatar,setAvatar]=useState<ForumImageSource|undefined>(),[banner,setBanner]=useState<ForumImageSource|undefined>(),[characterIds,setCharacterIds]=useState<string[]>([]),[npcs,setNpcs]=useState<ForumNpc[]>([]),[loreBookIds,setLoreBookIds]=useState<string[]>([]),[activity,setActivity]=useState<ForumActivitySettings>(defaultForumActivitySettings()),[assets,setAssets]=useState<Map<string,string>>(new Map()),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[deleteOpen,setDeleteOpen]=useState(false),[npcKeywords,setNpcKeywords]=useState("");
 const pendingAssets=useRef(new Set<string>()),keptAssets=useRef(new Set<string>()),obsoleteAssets=useRef(new Set<string>());
 const loadAssets=()=>db.mediaAssets.toArray().then(rows=>setAssets(new Map(rows.map(row=>[row.id,row.data]))));
 useEffect(()=>{void loadAssets()},[]);
 useEffect(()=>{if(mode!=="settings"||!serverId)return;void db.forumServers.get(serverId).then(row=>{if(!row){setLoaded(true);return}const next=normalizeForumServer(row);setServer(next);setName(next.name);setDescription(next.description);setIntroduction(next.introduction??"");setIconText(next.iconText);setColor(next.color);setAvatar(next.avatar);setBanner(next.banner);setCharacterIds(next.characterIds??[]);setNpcs(next.npcs??[]);setLoreBookIds(next.loreBookIds??[]);setActivity(next.activitySettings??defaultForumActivitySettings());setLoaded(true)})},[mode,serverId]);
 useEffect(()=>()=>{for(const id of pendingAssets.current)if(!keptAssets.current.has(id))void deleteMediaIfUnused(id)},[]);
 const previewAvatar=sourceUrl(avatar,assets),previewBanner=sourceUrl(banner,assets),selectedCharacters=characters.filter(character=>characterIds.includes(character.id));
 const markOld=(source?:ForumImageSource)=>{if(source?.type==="asset")obsoleteAssets.current.add(source.value)};
 const upload=async(file:File|undefined,purpose:"forum-avatar"|"forum-banner"|"forum-npc-avatar")=>{if(!file)return;const asset=await saveImageMedia(file,purpose);pendingAssets.current.add(asset.id);setAssets(current=>new Map(current).set(asset.id,asset.data));return{type:"asset" as const,value:asset.id}};
 const chooseMainImage=async(kind:"avatar"|"banner",file?:File)=>{const source=await upload(file,kind==="avatar"?"forum-avatar":"forum-banner");if(!source)return;if(kind==="avatar"){markOld(avatar);setAvatar(source)}else{markOld(banner);setBanner(source)}};
 const setMainUrl=(kind:"avatar"|"banner",value:string)=>{if(kind==="avatar"){markOld(avatar);setAvatar(value.trim()?{type:"url",value:value.trim()}:undefined)}else{markOld(banner);setBanner(value.trim()?{type:"url",value:value.trim()}:undefined)}};
 const toggleCharacter=(id:string)=>setCharacterIds(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
 const quotaOf=(id:string)=>activity.characterQuotas[id]??{enabled:true,postsPerRun:0,repliesPerRun:0};
 const updateQuota=(id:string,patch:Partial<ReturnType<typeof quotaOf>>)=>setActivity(current=>({...current,characterQuotas:{...current.characterQuotas,[id]:{...quotaOf(id),...patch}}}));
 const addNpc=()=>setNpcs(current=>[...current,blankNpc()]);
 const updateNpc=(id:string,patch:Partial<ForumNpc>)=>setNpcs(current=>current.map(npc=>npc.id===id?{...npc,...patch,updatedAt:now()}:npc));
 const removeNpc=(id:string)=>setNpcs(current=>{const target=current.find(npc=>npc.id===id);markOld(target?.avatar);return current.filter(npc=>npc.id!==id)});
 const chooseNpcAvatar=async(id:string,file?:File)=>{const source=await upload(file,"forum-npc-avatar");if(!source)return;markOld(npcs.find(npc=>npc.id===id)?.avatar);updateNpc(id,{avatar:source})};
 const fillNpc=async()=>{if(!provider||!npcKeywords.trim())return;setBusy(true);setMessage("");try{const profile=await generateForumNpcProfile(provider,npcKeywords);const target=npcs.find(npc=>!npc.name.trim()&&!npc.persona.trim());if(target)updateNpc(target.id,profile);else setNpcs(current=>[...current,{...blankNpc(),...profile}]);setNpcKeywords("")}catch(error){setMessage(error instanceof Error?error.message:"NPC 补全失败")}finally{setBusy(false)}};
 const save=async()=>{if(!name.trim()||!settings)return;setBusy(true);setMessage("");try{const cleanNpcs=npcs.filter(npc=>npc.name.trim()&&npc.persona.trim()).map(npc=>({...npc,name:npc.name.trim(),persona:npc.persona.trim()}));let saved:ForumServer;if(mode==="create"){const created=await createForumCommunity({name,description,introduction,iconText,color,authorName:settings.userName||"我",avatar,banner,characterIds,npcs:cleanNpcs,loreBookIds,activitySettings:{...activity,enabled:false}});saved=created.server}else{if(!serverId)throw new Error("论坛不存在");saved=await updateForumCommunity(serverId,{name:name.trim(),description:description.trim(),introduction:introduction.trim(),iconText:iconText.trim().slice(0,2)||name.trim().slice(0,1),color,avatar,banner,characterIds,npcs:cleanNpcs,loreBookIds,activitySettings:{...activity,nextRunAt:activity.enabled?(activity.nextRunAt??now()+activity.intervalMinutes*60000):undefined}})}for(const id of pendingAssets.current)keptAssets.current.add(id);for(const id of obsoleteAssets.current)await deleteMediaIfUnused(id);await reload();nav(`/forum/${saved.id}`,{replace:true})}catch(error){setMessage(error instanceof Error?error.message:"保存失败")}finally{setBusy(false)}};
 const generateNow=async()=>{if(!serverId||!provider)return;setBusy(true);setMessage("");try{const result=await runForumGeneration({serverId,provider});const fresh=await db.forumServers.get(serverId);if(fresh)setActivity(normalizeForumServer(fresh).activitySettings!);setMessage(`已生成 ${result.posts} 篇帖子、${result.replies} 条回复`)}catch(error){setMessage(error instanceof Error?error.message:"生成失败")}finally{setBusy(false)}};
 const removeForum=async()=>{if(!serverId)return;setBusy(true);await deleteForumCommunity(serverId);await reload();nav("/forum",{replace:true})};
 if(!loaded)return <div className="forum-editor-loading">正在读取论坛…</div>;
 if(mode==="settings"&&!server)return <Navigate to="/forum" replace/>;
 return <div className="forum-editor-page"><header><button onClick={()=>nav(mode==="settings"&&serverId?`/forum/${serverId}`:"/forum")}><ArrowLeft/></button><div><small>{mode==="create"?"NEW FORUM":"FORUM SETTINGS"}</small><b>{mode==="create"?"创建论坛":"论坛设置"}</b></div><button className="save" disabled={!name.trim()||busy} onClick={()=>void save()}><Save/></button></header><main>
  <section className="forum-editor-preview"><header className="preview-head"><b>实时预览</b><small>目录页与帖子页</small></header><div className="forum-editor-directory-preview">{previewAvatar?<img src={previewAvatar} alt="论坛头像"/>:<span style={{background:color}}>{iconText||name.slice(0,1)||"坛"}</span>}<div><b>{name||"论坛名称"}</b><p>{description||"论坛简介会显示在这里"}</p><small><Users/>{selectedCharacters.length+npcs.filter(npc=>npc.enabled).length} 位参与者</small></div></div><div className="banner" style={previewBanner?{backgroundImage:`url("${previewBanner}")`}:{background:`linear-gradient(135deg,${color}55,#ececef)`}}/><div className="identity">{previewAvatar?<img src={previewAvatar} alt="论坛头像"/>:<span style={{background:color}}>{iconText||name.slice(0,1)||"坛"}</span>}<div><h2>{name||"论坛名称"}</h2><p>{description||"论坛简介会显示在这里"}</p></div></div></section>
  <section className="forum-editor-section"><h3>论坛资料</h3><div className="forum-editor-group"><label><span>论坛名称<small>{name.length}/30</small></span><input maxLength={30} value={name} onChange={event=>setName(event.target.value)}/></label><label><span>论坛简介<small>{description.length}/120</small></span><textarea rows={3} maxLength={120} value={description} onChange={event=>setDescription(event.target.value)}/></label><label><span>论坛介绍<small>{introduction.length}/5000</small></span><textarea rows={7} maxLength={5000} value={introduction} onChange={event=>setIntroduction(event.target.value)} placeholder="论坛背景、规则与定位"/></label></div></section>
  <section className="forum-editor-section"><h3>视觉素材</h3><div className="forum-editor-group image"><label className="forum-upload-row"><span><b>论坛头像</b><small>本地上传或图片 URL</small></span><Upload/><input hidden type="file" accept="image/*" onChange={event=>void chooseMainImage("avatar",event.target.files?.[0])}/></label><label><span>头像 URL</span><input value={avatar?.type==="url"?avatar.value:""} onChange={event=>setMainUrl("avatar",event.target.value)} placeholder="https://…"/></label><label className="forum-upload-row"><span><b>顶部横幅</b><small>建议使用横向图片</small></span><ImagePlus/><input hidden type="file" accept="image/*" onChange={event=>void chooseMainImage("banner",event.target.files?.[0])}/></label><label><span>横幅 URL</span><input value={banner?.type==="url"?banner.value:""} onChange={event=>setMainUrl("banner",event.target.value)} placeholder="https://…"/></label><button className="forum-editor-clear" onClick={()=>{markOld(banner);setBanner(undefined)}}>移除横幅</button></div></section>
  <section className="forum-editor-section"><h3>添加角色</h3><div className="forum-editor-group"><div className="forum-character-grid">{characters.map(character=><button key={character.id} className={characterIds.includes(character.id)?"selected":""} onClick={()=>toggleCharacter(character.id)}><Avatar text={character.name} src={character.avatar} size="sm"/><span>{character.name}</span>{characterIds.includes(character.id)&&<Check/>}</button>)}</div>{mode==="settings"&&selectedCharacters.map(character=>{const quota=quotaOf(character.id);return <div className="forum-quota-row" key={character.id}><Avatar text={character.name} src={character.avatar} size="sm"/><span><b>{character.name}</b><small>角色配额优先执行</small></span><label>帖子<input type="number" min="0" max="50" value={quota.postsPerRun} onChange={event=>updateQuota(character.id,{postsPerRun:Number(event.target.value)})}/></label><label>回复<input type="number" min="0" max="100" value={quota.repliesPerRun} onChange={event=>updateQuota(character.id,{repliesPerRun:Number(event.target.value)})}/></label><input type="checkbox" checked={quota.enabled} onChange={event=>updateQuota(character.id,{enabled:event.target.checked})}/></div>})}</div></section>
  <section className="forum-editor-section"><h3>论坛 NPC</h3><div className="forum-editor-group"><div className="forum-npc-ai"><input value={npcKeywords} onChange={event=>setNpcKeywords(event.target.value)} placeholder="输入关键词，例如：毒舌的电影爱好者"/><button disabled={!npcKeywords.trim()||busy} onClick={()=>void fillNpc()}><Sparkles/>AI 补全</button></div>{npcs.map(npc=><article className="forum-npc-editor" key={npc.id}><label className="avatar"><Avatar text={npc.name||"N"} src={sourceUrl(npc.avatar,assets)} size="md"/><Upload/><input hidden type="file" accept="image/*" onChange={event=>void chooseNpcAvatar(npc.id,event.target.files?.[0])}/></label><div><input maxLength={30} value={npc.name} onChange={event=>updateNpc(npc.id,{name:event.target.value})} placeholder="显示名称"/><input maxLength={24} value={npc.handle??""} onChange={event=>updateNpc(npc.id,{handle:event.target.value.replace(/\s+/g,"_")})} placeholder="@账号"/><textarea rows={2} maxLength={300} value={npc.persona} onChange={event=>updateNpc(npc.id,{persona:event.target.value})} placeholder="一句人设"/></div><Toggle title="启用" checked={npc.enabled} onChange={value=>updateNpc(npc.id,{enabled:value})}/><button className="remove" onClick={()=>removeNpc(npc.id)}><Trash2/></button></article>)}<button className="forum-editor-add" onClick={addNpc}><Plus/>新增 NPC</button></div></section>
  <section className="forum-editor-section"><h3>挂载世界书</h3><div className="forum-editor-group"><details className="forum-lore-select"><summary><span>{loreBookIds.length?loreBooks.filter(book=>loreBookIds.includes(book.id)).map(book=>book.name).join("、"):"点击选择世界书"}</span><ChevronDown/></summary><div>{loreBooks.length?loreBooks.map(book=><button type="button" key={book.id} className={loreBookIds.includes(book.id)?"selected":""} onClick={()=>setLoreBookIds(current=>current.includes(book.id)?current.filter(id=>id!==book.id):[...current,book.id])}><BookOpen/><span><b>{book.name}</b><small>{book.entries.length} 条设定</small></span><i>{loreBookIds.includes(book.id)&&<Check/>}</i></button>):<p>暂无可挂载的世界书</p>}</div></details></div></section>
  {mode==="settings"&&<section className="forum-editor-section"><h3>后台主动生成</h3><div className="forum-editor-group"><Toggle title="允许后台生成" note="关闭茶茶机期间由未来保活模块调用；当前会在重新打开后补算" checked={activity.enabled} onChange={enabled=>setActivity(current=>({...current,enabled,nextRunAt:enabled?(current.nextRunAt??now()+current.intervalMinutes*60000):undefined}))}/><div className="forum-activity-grid"><label>间隔分钟<input type="number" min="1" max="43200" value={activity.intervalMinutes} onChange={event=>{const intervalMinutes=Math.max(1,Number(event.target.value)||1);setActivity(current=>({...current,intervalMinutes,nextRunAt:current.enabled?now()+intervalMinutes*60000:current.nextRunAt}))}}/></label><label>每轮新帖<input type="number" min="0" max="100" value={activity.postsPerRun} onChange={event=>setActivity(current=>({...current,postsPerRun:Number(event.target.value)}))}/></label><label>额外回复<input type="number" min="0" max="300" value={activity.repliesPerRun} onChange={event=>setActivity(current=>({...current,repliesPerRun:Number(event.target.value)}))}/></label><label>主动私信<input type="number" min="0" max="20" value={activity.directMessagesPerRun??2} onChange={event=>setActivity(current=>({...current,directMessagesPerRun:Number(event.target.value)}))}/></label></div><div className="forum-activity-status"><Clock3/><span><b>下次运行</b><small>{activity.nextRunAt?new Date(activity.nextRunAt).toLocaleString("zh-CN"):"尚未安排"}</small></span></div>{activity.lastSummary&&<div className="forum-activity-status"><RefreshCw/><span><b>最近一次</b><small>{activity.lastSummary}</small></span></div>}<button className="forum-editor-generate" disabled={busy||!provider?.apiKey.trim()} onClick={()=>void generateNow()}><Sparkles/>{busy?"正在生成…":"立即生成一轮"}</button></div></section>}
  {message&&<p className="forum-editor-message">{message}</p>}
  {mode==="settings"&&<section className="forum-editor-section danger"><h3>危险操作</h3><div className="forum-editor-group"><button onClick={()=>setDeleteOpen(true)}><Trash2/>删除论坛</button></div></section>}
 </main>{deleteOpen&&<Modal onClose={()=>setDeleteOpen(false)}><div className="forum-delete-confirm"><Trash2/><h2>删除这个论坛？</h2><p>论坛、频道、帖子、回复和不再使用的图片都会被永久删除。</p><button className="danger-button" disabled={busy} onClick={()=>void removeForum()}>确认删除</button><button className="cancel-button" onClick={()=>setDeleteOpen(false)}>取消</button></div></Modal>}</div>;
}
