import {useEffect,useState} from "react";
import {ArrowLeft,ChevronRight,Clock3,CreditCard,Gift,History,Minus,PackageCheck,Plus,Search,ShoppingBag,Trash2,UtensilsCrossed,WalletCards,X} from "lucide-react";
import {useNavigate,useSearchParams} from "react-router-dom";
import {Avatar,Modal} from "../components/ui";
import {canCharacterInteract} from "../core/conversationSettings";
import {db} from "../core/db";
import {addMallCartItem,checkoutMall,clearMallCart,deleteMallCatalogItem,ensureMallStarterCatalog,ensureMallWallet,generateMallCatalog,mallCartDetails,mallOrderStatus,setMallBalance,syncMallOrderStatuses,updateMallCartQuantity} from "../core/mall";
import {useStore} from "../core/store";
import type {MallCatalogItem,MallCartItem,MallOrder,MallWalletSettings,WalletTransaction} from "../core/types";

type Tab="shop"|"eats"|"wallet"|"orders";
type CartRow={cart:MallCartItem;item:MallCatalogItem};
const yuan=(cents:number)=>`¥${(cents/100).toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const statusName=(order:MallOrder)=>{const status=mallOrderStatus(order);if(order.kind==="eats")return({placed:"已接单",preparing:"制作中",delivering:"配送中",delivered:"已送达",shipped:"配送中",cancelled:"已取消"} as const)[status];return({placed:"已下单",preparing:"备货中",shipped:"已发货",delivering:"配送中",delivered:"已送达",cancelled:"已取消"} as const)[status]};

export default function MallPage(){
 const nav=useNavigate(),[params]=useSearchParams(),{characters,provider,settings,reload}=useStore();
 const [tab,setTab]=useState<Tab>(params.get("tab")==="orders"?"orders":"shop"),[catalog,setCatalog]=useState<MallCatalogItem[]>([]),[cart,setCart]=useState<CartRow[]>([]),[orders,setOrders]=useState<MallOrder[]>([]),[transactions,setTransactions]=useState<WalletTransaction[]>([]),[wallet,setWallet]=useState<MallWalletSettings|null>(null),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[selected,setSelected]=useState<MallCatalogItem|null>(null),[restaurant,setRestaurant]=useState<MallCatalogItem|null>(null),[cartOpen,setCartOpen]=useState(false),[checkoutOpen,setCheckoutOpen]=useState(false),[recipientType,setRecipientType]=useState<"user"|"character">("user"),[recipientId,setRecipientId]=useState(""),[balanceOpen,setBalanceOpen]=useState(false),[balanceText,setBalanceText]=useState("5200"),[orderDetailId,setOrderDetailId]=useState(params.get("order")??"");
 const load=async()=>{await ensureMallStarterCatalog();await syncMallOrderStatuses();const [catalogRows,cartRows,orderRows,txRows,walletRow]=await Promise.all([db.mallCatalogItems.orderBy("createdAt").reverse().toArray(),mallCartDetails(tab==="eats"?"eats":"shop"),db.mallOrders.orderBy("createdAt").reverse().toArray(),db.walletTransactions.orderBy("createdAt").reverse().toArray(),ensureMallWallet()]);setCatalog(catalogRows);setCart(cartRows);setOrders(orderRows);setTransactions(txRows);setWallet(walletRow);setBalanceText(String(walletRow.balanceCents/100))};
 useEffect(()=>{void load()},[tab]);
 const shopItems=catalog.filter(item=>item.kind==="shop"),restaurants=catalog.filter(item=>item.kind==="restaurant"),restaurantMenu=restaurant?catalog.filter(item=>item.kind==="food"&&item.merchantId===restaurant.id):[],cartCount=cart.reduce((sum,row)=>sum+row.cart.quantity,0),cartSubtotal=cart.reduce((sum,row)=>sum+row.item.priceCents*row.cart.quantity,0),cartDelivery=tab==="eats"?(cart[0]?.item.deliveryFeeCents??0):0,cartTotal=cartSubtotal+cartDelivery,selectedCartRow=selected?cart.find(row=>row.item.id===selected.id):undefined,orderDetail=orders.find(order=>order.id===orderDetailId)??null;
 const search=async()=>{if(!query.trim()||busy||!provider)return;setBusy(true);setError("");setNotice("");try{await generateMallCatalog(tab==="eats"?"eats":"shop",query,provider);setNotice(`已生成“${query.trim()}”的虚拟${tab==="eats"?"餐厅与菜单":"商品"}`);setQuery("");await load()}catch(e){setError(e instanceof Error?e.message:"生成失败")}finally{setBusy(false)}};
 const add=async(item:MallCatalogItem)=>{setError("");try{await addMallCartItem(item);setNotice(`${item.title} 已加入购物车`);await load()}catch(e){if(e instanceof Error&&e.message.includes("其他餐厅")&&window.confirm("外卖购物车中已有其他餐厅，是否清空后添加？")){await clearMallCart("eats");await addMallCartItem(item);await load();return}setError(e instanceof Error?e.message:"无法加入购物车")}};
 const removeCatalog=async(item:MallCatalogItem)=>{await deleteMallCatalogItem(item.id);setSelected(null);setRestaurant(null);await load()};
 const checkout=async()=>{if(!wallet||!cart.length||!provider)return;const character=characters.find(item=>item.id===recipientId),recipientName=recipientType==="user"?(settings?.userName||"我"):(character?.name||"");if(recipientType==="character"&&!character){setError("请选择角色");return}setBusy(true);setError("");try{const result=await checkoutMall({cartKind:tab==="eats"?"eats":"shop",recipientType,recipientId:character?.id,recipientName,userName:settings?.userName||"我",provider});setCheckoutOpen(false);setCartOpen(false);setTab("orders");setNotice(result.replyError?"下单成功，角色暂未回复":"下单成功");await reload();await load()}catch(e){setError(e instanceof Error?e.message:"结算失败")}finally{setBusy(false)}};
 const saveBalance=async()=>{const value=Number(balanceText);if(!Number.isFinite(value)||value<0)return;await setMallBalance(Math.round(value*100));setBalanceOpen(false);await load()};
 return <div className="app-page mall-page"><header className="mall-header"><button aria-label="返回桌面" onClick={()=>nav("/")}><ArrowLeft/></button><div><small>VIRTUAL LIFE STORE</small><h1>MALL</h1></div><button aria-label="订单记录" onClick={()=>setTab("orders")}><History/></button></header><nav className="mall-tabs"><button className={tab==="shop"?"active":""} onClick={()=>setTab("shop")}>SHOP</button><button className={tab==="eats"?"active":""} onClick={()=>setTab("eats")}>EATS</button><button className={tab==="wallet"?"active":""} onClick={()=>setTab("wallet")}>WALLET</button></nav><main className="mall-scroll">
 {tab!=="wallet"&&tab!=="orders"&&<><form className={`mall-search ${tab}`} onSubmit={event=>{event.preventDefault();void search()}}><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={tab==="shop"?"搜索任何想买的东西":"搜索餐厅、菜系或想吃的东西"}/><button type="submit" disabled={!query.trim()||busy}>{busy?"生成中":"生成"}</button><button type="button" className="mall-search-cart" aria-label="打开购物车" onClick={()=>setCartOpen(true)}><ShoppingBag/><b>{cartCount}</b></button></form></>}
 {error&&<p className="mall-alert error">{error}</p>}
 {tab==="shop"&&<section className="mall-shop">{shopItems.length?<div className="mall-product-grid">{shopItems.map(item=><button key={item.id} onClick={()=>setSelected(item)}><MallArt item={item}/><small>{item.merchantName}</small><b>{item.title}</b><span>{yuan(item.priceCents)}</span></button>)}</div>:<MallEmpty icon={<ShoppingBag/>} title="这里什么都可以买" text="搜索数码、家居、书籍、食物、玩具、服饰，或任何你想到的虚拟商品。"/>}</section>}
 {tab==="eats"&&<section className="mall-eats">{restaurants.length?<div className="restaurant-list">{restaurants.map(item=><button key={item.id} onClick={()=>setRestaurant(item)}><MallArt item={item}/><div><small>{item.category}</small><b>{item.title}</b><p>{item.description}</p><span>★ {item.rating?.toFixed(1)} · {item.etaMinutes} 分钟 · 配送费 {yuan(item.deliveryFeeCents??0)}</span></div><ChevronRight/></button>)}</div>:<MallEmpty icon={<UtensilsCrossed/>} title="搜索一顿虚拟外卖" text="生成餐厅与菜单后，可以给自己或角色下单。"/>}</section>}
 {tab==="wallet"&&<section className="mall-wallet"><div className="wallet-card"><header><span><WalletCards/>MALL WALLET</span><small>虚拟余额</small></header><b>{yuan(wallet?.balanceCents??520000)}</b><p>仅用于茶茶机内的购物、外卖与聊天转账</p><button onClick={()=>setBalanceOpen(true)}>充值</button></div><div className="wallet-summary"><span><CreditCard/><b>{transactions.filter(tx=>tx.amountCents<0&&tx.state!=="refunded").length}</b><small>支出</small></span><span><Gift/><b>{transactions.filter(tx=>tx.amountCents>0&&tx.kind!=="adjustment").length}</b><small>收入</small></span><span><Clock3/><b>{transactions.filter(tx=>tx.state==="pending").length}</b><small>待处理</small></span></div><div className="wallet-ledger"><header><b>交易记录</b><small>{transactions.length} 条</small></header>{transactions.length?transactions.map(tx=><article key={tx.id}><span className={tx.amountCents>=0?"income":"expense"}>{tx.amountCents>=0?"+":"-"}</span><div><b>{tx.title}</b><small>{new Date(tx.createdAt).toLocaleString("zh-CN")}</small></div><strong className={tx.amountCents>=0?"income":""}>{tx.amountCents>=0?"+":"-"}{yuan(Math.abs(tx.amountCents))}</strong></article>):<p>还没有钱包流水。</p>}</div></section>}
 {tab==="orders"&&<section className="mall-orders"><header><div><small>ORDER HISTORY</small><h2>订单与礼物</h2></div><button onClick={()=>setTab("shop")}><X/></button></header>{orders.length?orders.map(order=><button className="mall-order-row" key={order.id} onClick={()=>setOrderDetailId(order.id)}><span className={`order-icon ${order.kind}`}>{order.kind==="eats"?<UtensilsCrossed/>:<PackageCheck/>}</span><div><small>{order.payerName} → {order.recipientName}</small><b>{order.items.map(item=>item.title).join("、")}</b><p>{order.kind==="eats"?"外卖":"购物/礼物"} · {yuan(order.totalCents)}</p></div><strong>{statusName(order)}</strong></button>):<MallEmpty icon={<PackageCheck/>} title="还没有订单" text="结算后的购物、外卖和角色送来的礼物都会保存在这里。"/>}</section>}
 </main>
 {orderDetail&&<Modal onClose={()=>setOrderDetailId("")}><div className="mall-order-detail"><div className="sheet-head"><div><small>ORDER DETAIL</small><h2>{orderDetail.kind==="eats"?"外卖订单":orderDetail.kind==="gift"?"礼物记录":"购物订单"}</h2></div><button onClick={()=>setOrderDetailId("")}><X/></button></div><div className="order-detail-summary"><span className={`order-icon ${orderDetail.kind}`}>{orderDetail.kind==="eats"?<UtensilsCrossed/>:<PackageCheck/>}</span><div><small>{orderDetail.payerName} → {orderDetail.recipientName}</small><b>{statusName(orderDetail)}</b><p>{new Date(orderDetail.createdAt).toLocaleString("zh-CN")}</p></div></div><div className="order-detail-items">{orderDetail.items.map(item=><article key={item.id}><MallArt item={{...item,id:item.catalogItemId??item.id,schemaVersion:1,createdAt:orderDetail.createdAt,updatedAt:orderDetail.updatedAt,searchId:orderDetail.id,query:"",kind:orderDetail.kind==="eats"?"food":"shop",description:""}}/><div><b>{item.title}</b><small>{item.merchantName} · {item.category}</small></div><span>{item.quantity} × {yuan(item.priceCents)}</span></article>)}</div><div className="order-detail-total"><span>商品小计 <b>{yuan(orderDetail.subtotalCents)}</b></span>{orderDetail.deliveryFeeCents>0&&<span>配送费 <b>{yuan(orderDetail.deliveryFeeCents)}</b></span>}<strong>合计 {yuan(orderDetail.totalCents)}</strong></div>{orderDetail.note&&<p className="order-detail-note">备注：{orderDetail.note}</p>}</div></Modal>}
 {selected&&<Modal onClose={()=>setSelected(null)}><div className="mall-detail mall-product-detail"><div className="sheet-head mall-detail-head"><div><small>{selected.merchantName}</small><h2>商品详情</h2></div><button aria-label="关闭商品详情" onClick={()=>setSelected(null)}><X/></button></div><MallArt item={selected}/><section className="mall-detail-info"><small>{selected.category}</small><h2>{selected.title}</h2><strong>{yuan(selected.priceCents)}</strong><p>{selected.description}</p>{selected.colors?.length&&<div className="mall-detail-option"><b>颜色</b><span>{selected.colors.map(color=><i key={color}>{color}</i>)}</span></div>}{selected.sizes?.length&&<div className="mall-detail-option"><b>规格</b><span>{selected.sizes.map(size=><i key={size}>{size}</i>)}</span></div>}</section><footer className="mall-detail-actions">{selectedCartRow?<div className="mall-detail-cart-quantity"><span>购物车已有 {selectedCartRow.cart.quantity} 件</span><div><button type="button" aria-label="减少一件" onClick={()=>void updateMallCartQuantity(selectedCartRow.cart.id,selectedCartRow.cart.quantity-1).then(load)}><Minus/></button><b>{selectedCartRow.cart.quantity}</b><button type="button" aria-label="增加一件" onClick={()=>void updateMallCartQuantity(selectedCartRow.cart.id,selectedCartRow.cart.quantity+1).then(load)}><Plus/></button></div></div>:<button className="mall-buy-button" onClick={()=>void add(selected)}><ShoppingBag/>加入购物车</button>}<button className="mall-delete-button" onClick={()=>void removeCatalog(selected)}><Trash2/>删除此商品</button></footer></div></Modal>}
 {restaurant&&<Modal onClose={()=>setRestaurant(null)}><div className="restaurant-detail"><div className="sheet-head"><div><small>{restaurant.category}</small><h2>{restaurant.title}</h2></div><button onClick={()=>setRestaurant(null)}><X/></button></div><p>{restaurant.description}</p><div className="restaurant-menu">{restaurantMenu.map(item=><article key={item.id}><MallArt item={item}/><div><b>{item.title}</b><p>{item.description}</p><span>{yuan(item.priceCents)}</span></div><button aria-label={`将${item.title}加入购物车`} onClick={()=>void add(item)}><Plus/></button></article>)}</div><footer className="restaurant-cart-bar"><span><small>购物车</small><b>{cartCount?`${cartCount} 件 · ${yuan(cartTotal)}`:"还没有选择餐品"}</b></span><button disabled={!cartCount} onClick={()=>{setRestaurant(null);setCartOpen(true)}}>查看购物车<ChevronRight/></button></footer><button className="delete-link" onClick={()=>void removeCatalog(restaurant)}><Trash2/>删除餐厅与菜单</button></div></Modal>}
 {cartOpen&&<Modal onClose={()=>setCartOpen(false)}><div className="sheet-head"><div><small>CART</small><h2>{tab==="eats"?"外卖购物车":"购物袋"}</h2></div><button onClick={()=>setCartOpen(false)}><X/></button></div><div className="mall-cart">{cart.length?cart.map(row=><article key={row.cart.id}><MallArt item={row.item}/><div><b>{row.item.title}</b><small>{yuan(row.item.priceCents)}</small></div><span><button onClick={()=>void updateMallCartQuantity(row.cart.id,row.cart.quantity-1).then(load)}><Minus/></button><b>{row.cart.quantity}</b><button onClick={()=>void updateMallCartQuantity(row.cart.id,row.cart.quantity+1).then(load)}><Plus/></button></span></article>):<p>购物车还是空的。</p>}<footer><span>小计 <b>{yuan(cartSubtotal)}</b></span>{cartDelivery>0&&<span>配送费 <b>{yuan(cartDelivery)}</b></span>}<strong>合计 {yuan(cartTotal)}</strong><button className="primary" disabled={!cart.length} onClick={()=>{setCartOpen(false);setCheckoutOpen(true)}}>去结算</button></footer></div></Modal>}
 {checkoutOpen&&<Modal onClose={()=>setCheckoutOpen(false)}><div className="sheet-head"><div><small>CHECKOUT</small><h2>确认结算</h2></div><button onClick={()=>setCheckoutOpen(false)}><X/></button></div><div className="mall-checkout"><div className="recipient-tabs"><button className={recipientType==="user"?"active":""} onClick={()=>setRecipientType("user")}>给自己</button><button className={recipientType==="character"?"active":""} onClick={()=>setRecipientType("character")}>给角色</button></div>{recipientType==="character"&&<div className="recipient-list">{characters.filter(character=>canCharacterInteract(character)).map(character=><button key={character.id} className={recipientId===character.id?"active":""} onClick={()=>setRecipientId(character.id)}><Avatar text={character.name} src={character.avatar} size="sm"/><span>{character.name}</span></button>)}</div>}<p>钱包余额：{yuan(wallet?.balanceCents??0)}</p><strong>本次支付：{yuan(cartTotal)}</strong><button className="primary" disabled={busy||!cart.length||(recipientType==="character"&&!recipientId)||(wallet?.balanceCents??0)<cartTotal} onClick={()=>void checkout()}>{busy?"正在下单…":"确认支付"}</button></div></Modal>}
 {balanceOpen&&<Modal onClose={()=>setBalanceOpen(false)}><div className="sheet-head"><div><small>WALLET BALANCE</small><h2>充值</h2></div><button onClick={()=>setBalanceOpen(false)}><X/></button></div><div className="balance-editor"><label>人民币余额<div><span>¥</span><input inputMode="decimal" value={balanceText} onChange={event=>setBalanceText(event.target.value.replace(/[^0-9.]/g,""))}/></div></label><p>修改会生成一条“余额调整”流水。</p><button className="primary" onClick={()=>void saveBalance()}>确认充值</button></div></Modal>}
 </div>
}

function MallArt({item}:{item:MallCatalogItem}){return <span className={`mall-art tone-${item.tone}`}>{item.kind==="restaurant"?<UtensilsCrossed/>:item.kind==="food"?<span>FOOD</span>:<span>{item.category.slice(0,12).toUpperCase()}</span>}</span>}
function MallEmpty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="mall-empty"><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>}
