import {useEffect,useRef,useState} from "react";
import {ChevronLeft,Sparkles,Users} from "lucide-react";
import {useNavigate,useSearchParams} from "react-router-dom";
import {Avatar} from "../components/ui";
import {createMeetSession,generateMeetOpeningDraft} from "../core/meetService";
import {useStore} from "../core/store";
import type {MeetScene} from "../core/types";

export default function MeetCreatePage(){
 const nav=useNavigate(),[params]=useSearchParams(),conversationId=params.get("conversationId")??"",{characters,conversations,reload}=useStore(),conversation=conversations.find(item=>item.id===conversationId),[selected,setSelected]=useState<string[]>([]),[scene,setScene]=useState<MeetScene>({opening:""}),[saving,setSaving]=useState(false),[generating,setGenerating]=useState(false),[error,setError]=useState(""),generated=useRef(false);
 useEffect(()=>{if(!conversation)return;setSelected(conversation.memberIds.filter(id=>characters.some(character=>character.id===id)))},[conversation?.id,characters.length]);
 useEffect(()=>{if(!conversationId||!conversation||generated.current)return;generated.current=true;const controller=new AbortController();setGenerating(true);void generateMeetOpeningDraft(conversationId,conversation.memberIds,controller.signal).then(opening=>{if(opening)setScene(current=>({...current,opening}))}).catch(()=>setError("自动开场没有生成成功，你仍可以手动填写或直接进入。" )).finally(()=>setGenerating(false));return()=>controller.abort()},[conversationId,conversation?.id]);
 const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
 const regenerate=async()=>{if(!conversationId||generating)return;setGenerating(true);setError("");try{const opening=await generateMeetOpeningDraft(conversationId,selected);if(opening)setScene(current=>({...current,opening}));else setError("尚未配置模型，可以手动填写或直接进入。") }catch{setError("自动开场没有生成成功，你仍可以手动填写或直接进入。") }finally{setGenerating(false)}};
 const start=async()=>{if(!selected.length||saving)return;setSaving(true);setError("");try{const session=await createMeetSession({participantIds:selected,conversationId:conversationId||undefined,scene,suggestionsEnabled:false});await reload();nav(`/meet/${session.id}`)}catch(value){setError(value instanceof Error?value.message:"无法开始见面")}finally{setSaving(false)}};
 return <div className="meet-new-page"><header><button onClick={()=>nav(-1)} aria-label="返回"><ChevronLeft/></button><div><small>NEW MEET</small><h1>创建线下</h1></div><span/></header><main><section className="meet-new-intro"><b>选择这次见面的角色</b><small>{selected.length} 位已选择</small></section><div className="meet-new-characters">{characters.length?characters.map(character=><button type="button" key={character.id} className={selected.includes(character.id)?"selected":""} aria-pressed={selected.includes(character.id)} onClick={()=>toggle(character.id)}><Avatar text={character.name} src={character.avatar} size="md"/><span><b>{character.name}</b><small>{character.relationship.mood||"等待见面"}</small></span><i>{selected.includes(character.id)?"✓":""}</i></button>):<div className="meet-new-empty"><Users/><b>还没有角色</b><small>请先在角色 App 创建角色。</small></div>}</div><label className="meet-new-field"><span><b>剧情大纲</b><em>选填</em></span><textarea rows={5} value={scene.outline??""} onChange={event=>setScene({...scene,outline:event.target.value})} placeholder="例如：两人在雨夜的便利店偶遇，过去的误会逐渐被重新提起……"/></label><label className="meet-new-field"><span><b>开场白</b><em>选填</em>{conversationId&&<button type="button" onClick={()=>void regenerate()} disabled={generating}><Sparkles/>{generating?"正在生成":"重新生成"}</button>}</span><textarea rows={6} value={scene.opening} onChange={event=>setScene({...scene,opening:event.target.value})} placeholder="可以留空，进入见面后直接发送第一句话或动作。"/></label>{generating&&<p className="meet-opening-status"><Sparkles/>正在根据聊天生成开场白…</p>}{error&&<p className="form-error">{error}</p>}</main><footer><button className="primary" disabled={!selected.length||saving} onClick={()=>void start()}>{saving?"正在创建…":"进入见面"}</button></footer></div>
}