import {useEffect,useRef,useState} from "react";
import {ArrowLeft,CalendarDays,ChevronLeft,ChevronRight,ContactRound,Delete,FileText,Image as ImageIcon,LockKeyhole,Mail,MapPin,MessageCircleMore,Mic,NotebookText,Phone,Search,Settings,ShieldAlert,Smartphone,WalletCards} from "lucide-react";
import {Navigate,useNavigate,useParams} from "react-router-dom";
import {Avatar,Modal} from "../components/ui";
import {coreSettingOf} from "../core/character";
import {getCharacterPhoneState,pendingPhoneOperationTrace,phoneOperationDiscoveryChance,savePhoneAppContent} from "../core/phoneEcosystem";
import {ensureEnhancedPhoneState,recordPhoneAppUsage} from "../core/phoneEcosystemEnhancements";
import {recordRecentPhoneApp} from "../core/phoneNavigation";
import {PHONE_APPS,clearExpiredPhoneLock,clearPhonePasscodeFailures,ensurePhonePrivacy,generatePhoneAppContent,handlePhoneDiscovery,highestRiskPhoneApp,isTestCharacter,normalizeTestCharacterPhonePrivacy,phoneAccessPhase,phoneAppRisk,phoneAppUnlocked,phoneLocked,simplePhoneHint,shouldDiscoverPhoneSession,strategyEnabled,verifyPhonePasscode,type PhoneAppContent,type PhoneAppId,type PhoneBrowserContent,type PhoneCalendarContent,type PhoneCallsContent,type PhoneGalleryContent,type PhoneNotesContent,type PhoneWalletContent} from "../core/phoneCheck";
import {useStore} from "../core/store";
import type {Character,CharacterPhoneState} from "../core/types";
import {PersistentTalkApp,PhoneContactsApp,PhoneMailApp,PhoneMapsApp} from "./PhoneEcosystemApps";
import {PhoneFilesApp,PhoneRemindersApp,PhoneSystemApp,PhoneVoiceMemosApp} from "./PhoneUtilityApps";
import {PhoneGlobalSearchOverlay,PhoneRecentAppsOverlay} from "./PhoneNavigationOverlays";

const iconOf=(id:PhoneAppId)=>id==="calendar"?<CalendarDays/>:id==="gallery"?<ImageIcon/>:id==="wallet"?<WalletCards/>:id==="browser"?<Search/>:id==="notes"?<NotebookText/>:id==="calls"?<Phone/>:id==="contacts"?<ContactRound/>:id==="mail"?<Mail/>:id==="maps"?<MapPin/>:id==="files"?<FileText/>:id==="voice-memos"?<Mic/>:id==="system-settings"?<Settings/>:<MessageCircleMore/>;
const yuan=(cents:number)=>`¥${(cents/100).toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const riskText=(value:number)=>`本次查看风险约 ${Math.round(value*100)}% · 退出手机时统一判定一次`;

export default function PhoneCheckPage(){const {characterId}=useParams(),nav=useNavigate(),{characters}=useStore();if(characterId){const character=characters.find(item=>item.id===characterId);return character?<CharacterPhone character={character}/>:<Navigate to="/phone-check" replace/>}return <div className="app-page phone-check-page ios6-settings-page"><header className="phone-check-header ios6-settings-header"><button aria-label="返回桌面" onClick={()=>nav("/")}><ChevronLeft/></button><h1>查手机</h1><span/></header><main className="phone-picker-scroll ios6-settings-scroll"><p className="ios6-settings-section-title">角色手机</p><section className="phone-check-intro ios6-settings-info"><span><ShieldAlert/></span><div><b>选择要查看的角色</b></div></section><p className="ios6-settings-section-title character-section-title">角色</p><div className="phone-character-list ios6-settings-list">{characters.map(character=>{const strategy=strategyEnabled(character);return <button key={character.id} onClick={()=>nav(`/phone-check/${character.id}`)}><Avatar text={character.name} src={character.avatar}/><span><b>{character.name}</b><small>{coreSettingOf(character)||"尚未填写核心设定"}</small><em className={strategy?"strategy":"free"}>{strategy?`攻略模式 · 信任 ${character.relationship.trust}`:"攻略模式关闭 · 全部 App 开放"}</em></span><ChevronRight/></button>})}</div>{!characters.length&&<div className="phone-check-empty ios6-settings-empty"><Smartphone/><h3>还没有角色</h3><p>先在角色 App 中创建角色，才能查看角色手机。</p><button onClick={()=>nav("/characters")}>前往角色 App</button></div>}</main></div>}

function CharacterPhone({character}:{character:Character}){
 const nav=useNavigate(),{provider,reload}=useStore(),[privacy,setPrivacy]=useState(character.phonePrivacy),[phase,setPhase]=useState<"intro"|"lockscreen"|"passcode"|"home">(phoneAccessPhase(character)),[slide,setSlide]=useState(0),[digits,setDigits]=useState(""),[attempts,setAttempts]=useState(character.phonePrivacy?.failedAttempts??0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[active,setActive]=useState<PhoneAppId|null>(null),[loading,setLoading]=useState<PhoneAppId|null>(null),[contents,setContents]=useState<Partial<Record<PhoneAppId,PhoneAppContent>>>({}),[phoneState,setPhoneState]=useState<CharacterPhoneState>(),[launchContactId,setLaunchContactId]=useState<string>(),[homeOverlay,setHomeOverlay]=useState<"search"|"recent"|null>(null),[discovered,setDiscovered]=useState(""),[exitAfterDiscovery,setExitAfterDiscovery]=useState(false),visited=useRef(new Set<PhoneAppId>()),homeGestureStart=useRef<number|null>(null),riskEvaluated=useRef(false),clock=useClock(),strategy=strategyEnabled(character);
 useEffect(()=>{setPrivacy(character.phonePrivacy);setAttempts(character.phonePrivacy?.failedAttempts??0)},[character.phonePrivacy]);
 useEffect(()=>{if(!strategy||!isTestCharacter(character))return;void normalizeTestCharacterPhonePrivacy(character.id).then(next=>{if(next){setPrivacy(next);setAttempts(next.failedAttempts??0);void reload()}})},[character.id,strategy]);
 useEffect(()=>{if(!strategy){setPhase("home");setAttempts(0);setDigits("");setError("");void clearPhonePasscodeFailures(character.id).then(next=>{if(next){setPrivacy(next);if((character.phonePrivacy?.failedAttempts??0)>0)void reload()}});return}setPhase(phoneAccessPhase({...character,phonePrivacy:privacy}))},[strategy,character.id]);
 useEffect(()=>{if(!strategy||!privacy?.lockedUntil||privacy.lockedUntil>Date.now())return;void clearExpiredPhoneLock(character.id).then(next=>{setPrivacy(next);setAttempts(0);setError("");void reload()})},[strategy,character.id,privacy?.lockedUntil]);
 useEffect(()=>{void getCharacterPhoneState(character.id).then(state=>{if(!state)return;setPhoneState(state);setContents({...state.appContents as Partial<Record<PhoneAppId,PhoneAppContent>>,messages:{kind:"ecosystem"},contacts:{kind:"ecosystem"},mail:{kind:"ecosystem"},maps:{kind:"ecosystem"},notes:{kind:"ecosystem"},files:{kind:"ecosystem"},"voice-memos":{kind:"ecosystem"},"system-settings":{kind:"ecosystem"}})})},[character.id]);
 const resetSession=()=>{visited.current.clear();riskEvaluated.current=false;setActive(null);setLaunchContactId(undefined);setHomeOverlay(null);setError("")};
 const applyPhoneState=(state:CharacterPhoneState)=>{setPhoneState(state);setContents(current=>({...current,...state.appContents as Partial<Record<PhoneAppId,PhoneAppContent>>,messages:{kind:"ecosystem"},contacts:{kind:"ecosystem"},mail:{kind:"ecosystem"},maps:{kind:"ecosystem"},notes:{kind:"ecosystem"},files:{kind:"ecosystem"},"voice-memos":{kind:"ecosystem"},"system-settings":{kind:"ecosystem"}}))};
 const initialize=async()=>{if(!strategy){setPhase("home");return}if(!provider)return;setBusy(true);setError("");try{const next=await ensurePhonePrivacy(character.id,provider);setPrivacy(next);setPhase("lockscreen");await reload()}catch(e){setError(e instanceof Error?e.message:"无法初始化角色手机")}finally{setBusy(false)}};
 const discover=async(appId:PhoneAppId|undefined,trace=phoneState?pendingPhoneOperationTrace(phoneState):undefined)=>{if(!provider)return;setBusy(true);try{const result=await handlePhoneDiscovery({characterId:character.id,provider,appId,reason:"app",operationTraceId:trace?.id,operationSummary:trace?.contentSummary,operationSeverity:trace?.severity});setDiscovered(result.strategy?`${character.name}发现了你的动作。角色已经更换密码${result.lockedUntil?"并暂时锁住手机":""}。`:`${character.name}似乎发现了你的动作，并给你发来了一条消息。`);if(result.strategy){setDigits("");setAttempts(0);setPhase("intro")}setActive(null);await reload()}finally{setBusy(false)}};
 const unlock=async(candidate=digits)=>{if(candidate.length!==4||busy)return;setBusy(true);try{const result=await verifyPhonePasscode(character.id,candidate);if(result.privacy)setPrivacy(result.privacy);setAttempts(result.failedAttempts);setDigits("");if(result.status==="unlocked"){setError("");resetSession();setPhase("home");await reload();return}if(result.status==="incorrect"){setError(`密码不正确，还可尝试 ${result.remainingAttempts} 次`);return}if(result.status==="locked"){setError("手机仍在锁定中");return}setError("");setPhase("lockscreen");await handlePhoneDiscovery({characterId:character.id,provider:provider??undefined,reason:"passcode"});await reload()}catch(e){setError(e instanceof Error?e.message:"密码验证失败")}finally{setBusy(false)}}; const appendDigit=(value:number)=>{if(busy||digits.length>=4)return;const next=`${digits}${value}`;setDigits(next);if(next.length===4)setTimeout(()=>void unlock(next),120)};
 const openApp=async(appId:PhoneAppId,contactId?:string)=>{if(!phoneAppUnlocked(character,appId)){setError(`信任度达到 ${PHONE_APPS.find(app=>app.id===appId)?.requiredTrust} 后才会开放`);return}setActive(appId);setHomeOverlay(null);setLaunchContactId(contactId);setError("");if(!provider){setError("请先在设置中配置模型");return}setLoading(appId);try{let state=phoneState??await ensureEnhancedPhoneState(character.id,provider);if(phoneState)state=await ensureEnhancedPhoneState(character.id,provider);const usageState=await recordPhoneAppUsage(character.id,appId);if(usageState)state=usageState;const recentState=await recordRecentPhoneApp(character.id,appId,contactId);if(recentState)state=recentState;setPhoneState(state);if(["messages","contacts","mail","maps","notes","files","voice-memos","system-settings"].includes(appId)){setContents(current=>({...current,...state.appContents as Partial<Record<PhoneAppId,PhoneAppContent>>,[appId]:{kind:"ecosystem"}}));visited.current.add(appId);return}const persisted=state.appContents[appId] as PhoneAppContent|undefined;if(persisted){setContents(current=>({...current,[appId]:persisted}));visited.current.add(appId);return}const content=await generatePhoneAppContent(character.id,appId,provider);await savePhoneAppContent(character.id,appId,content);setContents(current=>({...current,[appId]:content}));if(content.degradedMessage)setError(content.degradedMessage);const next=await getCharacterPhoneState(character.id);if(next)setPhoneState(next);visited.current.add(appId)}catch(e){setError(e instanceof Error?e.message:"读取失败")}finally{setLoading(null)}};
 const showHomeOverlay=(kind:"search"|"recent")=>{if(kind==="search")visited.current.add("browser");setHomeOverlay(kind)};
 const onHomePointerUp=(event:React.PointerEvent<HTMLElement>)=>{const start=homeGestureStart.current;homeGestureStart.current=null;if(start===null||(event.target as HTMLElement).closest("button"))return;const delta=event.clientY-start;if(delta>70)showHomeOverlay("search");else if(delta<-70)showHomeOverlay("recent")};
 const exitPhone=async()=>{if(riskEvaluated.current){resetSession();nav("/phone-check");return}riskEvaluated.current=true;const trace=phoneState?pendingPhoneOperationTrace(phoneState):undefined,traceHit=Boolean(trace&&Math.random()<phoneOperationDiscoveryChance(character,trace)),appId=highestRiskPhoneApp(character,visited.current),appHit=Boolean(appId&&shouldDiscoverPhoneSession(character,visited.current));if(!traceHit&&!appHit){resetSession();nav("/phone-check");return}setExitAfterDiscovery(true);await discover(appId??trace?.appId,traceHit?trace:undefined)};
 const currentCharacter={...character,phonePrivacy:privacy};
 const onLockExpired=async()=>{const next=await clearExpiredPhoneLock(character.id);setPrivacy(next);setAttempts(0);setError("");setPhase(phoneAccessPhase({...character,phonePrivacy:next}));await reload()};
 if(phoneLocked(currentCharacter))return <PhoneLocked character={currentCharacter} onBack={()=>nav("/phone-check")} onExpired={()=>void onLockExpired()}/>;
 if(phase==="intro")return <div className="app-page phone-device-page role-ios6-device"><section className="phone-init-screen"><Avatar text={character.name} src={character.avatar} size="lg"/><small>FIRST ACCESS</small><h1>初始化 {character.name} 的手机</h1><p>先创建稳定密码。解锁后，角色的手机内容会长期保存并持续更新。</p><div className="phone-risk-note"><ShieldAlert/><span><b>{strategy?"攻略模式已开启":"攻略模式未开启"}</b><small>{strategy?"查看和冒用手机可能影响关系。":"全部 App 开放，但角色仍可能发现。"}</small></span></div>{error&&<p className="phone-error">{error}</p>}<button className="phone-primary" disabled={busy} onClick={()=>void initialize()}>{busy?"正在创建…":"确认并创建手机"}</button><button className="phone-secondary" onClick={()=>nav("/phone-check")}>暂不查看</button></section></div>;
 if(phase==="lockscreen")return <div className="app-page phone-device-page role-ios6-device"><section className="role-ios6-lock-screen"><button className="role-ios6-exit lock-exit" onClick={()=>nav("/phone-check")}><ChevronLeft/></button><div className="role-ios6-lock-clock"><b>{clock}</b><span>{new Date().toLocaleDateString("zh-CN",{month:"long",day:"numeric",weekday:"long"})}</span></div><div className="role-ios6-slide-wrap"><span>滑动来解锁</span><input aria-label="滑动来解锁" type="range" min="0" max="100" value={slide} onInput={e=>{const next=Number(e.currentTarget.value);setSlide(next);if(next>=92){setSlide(0);setPhase("passcode")}}} onPointerUp={()=>setSlide(0)}/></div></section></div>;
 if(phase==="passcode")return <div className="app-page phone-device-page role-ios6-device"><section className="role-ios6-passcode-screen"><button className="role-ios6-exit" onClick={()=>setPhase("lockscreen")}><ChevronLeft/></button><div className="role-ios6-passcode-title"><h2>输入密码</h2><p>{isTestCharacter(character)?"测试密码是 0000":simplePhoneHint(privacy?.hint)}</p><div className="passcode-dots">{[0,1,2,3].map(i=><i key={i} className={digits.length>i?"filled":""}/>)}</div>{error&&<small>{error}</small>}</div><div className="passcode-pad ios6-passcode-pad">{[1,2,3,4,5,6,7,8,9].map(n=><button key={n} disabled={busy} onClick={()=>appendDigit(n)}>{n}</button>)}<button disabled={busy} onClick={()=>setPhase("lockscreen")}>取消</button><button disabled={busy} onClick={()=>appendDigit(0)}>0</button><button disabled={busy} onClick={()=>setDigits(v=>v.slice(0,-1))}><Delete/></button></div></section></div>;
 return <div className="app-page phone-device-page role-ios6-device">{active?<PhoneAppView appId={active} character={character} state={phoneState} provider={provider} content={contents[active]} loading={loading===active} error={error} launchContactId={launchContactId} onChange={applyPhoneState} onOpen={(app,id)=>void openApp(app,id)} onBack={()=>{setActive(null);setLaunchContactId(undefined)}} onRetry={()=>void openApp(active,launchContactId)}/>:homeOverlay==="search"&&phoneState?<PhoneGlobalSearchOverlay state={phoneState} onChange={applyPhoneState} onClose={()=>setHomeOverlay(null)} onOpen={(app,id)=>void openApp(app,id)}/>:homeOverlay==="recent"&&phoneState?<PhoneRecentAppsOverlay state={phoneState} onChange={applyPhoneState} onClose={()=>setHomeOverlay(null)} onOpen={(app,id)=>void openApp(app,id)}/>:<section className="role-phone-home role-ios6-home role-ios6-home-no-dock" onPointerDown={event=>{if(!(event.target as HTMLElement).closest("button"))homeGestureStart.current=event.clientY}} onPointerUp={onHomePointerUp}><button className="role-ios6-exit home-exit" disabled={busy||Boolean(loading)} onClick={()=>void exitPhone()}><ChevronLeft/></button><button className="phone-home-search-trigger" aria-label="搜索角色手机" onClick={()=>showHomeOverlay("search")}><Search/><span>搜索</span></button><div className="role-ios6-home-grid">{PHONE_APPS.map(app=>{const unlocked=phoneAppUnlocked(character,app.id);return <button key={app.id} className={`role-ios6-app ${app.id} ${unlocked?"":"locked"}`} onClick={()=>void openApp(app.id)}><span>{unlocked?iconOf(app.id):<LockKeyhole/>}</span><b>{app.label}</b>{!unlocked&&<small>信任 {app.requiredTrust}</small>}</button>})}</div><button className="phone-home-recent-trigger" aria-label="打开最近使用的 App" onClick={()=>showHomeOverlay("recent")}><span/><b>最近</b><small>上滑</small></button>{error&&<p className="phone-floating-error">{error}</p>}</section>}{discovered&&<Modal onClose={()=>{setDiscovered("");if(exitAfterDiscovery){resetSession();nav("/phone-check")}setExitAfterDiscovery(false)}}><div className="phone-discovered-modal"><ShieldAlert/><small>YOU WERE NOTICED</small><h2>被发现了</h2><p>{discovered}</p><button className="phone-primary" onClick={()=>{setDiscovered("");if(exitAfterDiscovery)nav("/phone-check")}}>知道了</button></div></Modal>}</div>
}

function useClock(){const [value,setValue]=useState("");useEffect(()=>{const update=()=>setValue(new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false}));update();const timer=setInterval(update,30000);return()=>clearInterval(timer)},[]);return value}
function PhoneLocked({character,onBack,onExpired}:{character:Character;onBack:()=>void;onExpired:()=>void}){
 const lockedUntil=character.phonePrivacy?.lockedUntil??0,[remaining,setRemaining]=useState(()=>Math.max(0,lockedUntil-Date.now())),expired=useRef(false),passcodeLock=Boolean(character.phonePrivacy?.passcode);
 useEffect(()=>{expired.current=false;const update=()=>{const next=Math.max(0,lockedUntil-Date.now());setRemaining(next);if(next<=0&&!expired.current){expired.current=true;onExpired()}};update();const timer=window.setInterval(update,1000);return()=>window.clearInterval(timer)},[lockedUntil]);
 const seconds=Math.ceil(remaining/1000),countdown=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 return <div className="app-page phone-device-page role-ios6-device"><section className="role-ios6-lock-screen role-ios6-device-locked"><button className="role-ios6-exit lock-exit" onClick={onBack}><ChevronLeft/></button><div className="role-ios6-locked-alert"><LockKeyhole/><small>DEVICE LOCKED</small><h1>手机暂时无法查看</h1><p>{passcodeLock?"密码连续错误五次，手机已锁定五分钟。":`${character.name}发现了之前的查看行为，并暂时更改了访问权限。`}</p><b aria-live="polite">{countdown}</b><button onClick={onBack}>返回角色选择</button></div></section></div>
}

function PhoneAppView({appId,character,state,provider,content,loading,error,launchContactId,onChange,onOpen,onBack,onRetry}:{appId:PhoneAppId;character:Character;state?:CharacterPhoneState;provider:any;content?:PhoneAppContent;loading:boolean;error:string;launchContactId?:string;onChange:(state:CharacterPhoneState)=>void;onOpen:(app:PhoneAppId,id?:string)=>void;onBack:()=>void;onRetry:()=>void}){const ecosystem=["messages","contacts","mail","maps","notes","files","voice-memos","system-settings"].includes(appId),ready=ecosystem?Boolean(state&&provider):Boolean(content);if(!ready)return <section className="role-phone-app immersive"><header className="ios6-app-loading-head"><button onClick={onBack}><ChevronLeft/></button><b>{PHONE_APPS.find(a=>a.id===appId)?.label}</b><span/></header><div className="phone-app-inline-state"><p>{loading?"正在建立角色的长期手机生态…":error||"暂时无法读取内容"}</p>{!loading&&<button className="retry" onClick={onRetry}>重新尝试</button>}</div></section>;if(appId==="messages"&&state&&provider)return <PersistentTalkApp character={character} state={state} provider={provider} onChange={onChange} onBack={onBack} initialContactId={launchContactId} onOpen={onOpen}/>;if(appId==="contacts"&&state)return <PhoneContactsApp state={state} onBack={onBack} onOpen={onOpen} initialContactId={launchContactId}/>;if(appId==="mail"&&state&&provider)return <PhoneMailApp character={character} state={state} provider={provider} onChange={onChange} onBack={onBack} initialTargetId={launchContactId}/>;if(appId==="maps"&&state)return <PhoneMapsApp state={state} onBack={onBack} initialPlaceId={launchContactId}/>;if(appId==="notes"&&state)return <PhoneRemindersApp state={state} onBack={onBack} onChange={onChange} initialTargetId={launchContactId}/>;if(appId==="files"&&state)return <PhoneFilesApp state={state} onBack={onBack} initialTargetId={launchContactId}/>;if(appId==="voice-memos"&&state)return <PhoneVoiceMemosApp state={state} onBack={onBack} initialTargetId={launchContactId}/>;if(appId==="system-settings"&&state)return <PhoneSystemApp state={state} onBack={onBack}/>;return <LegacyApp appId={appId} content={content!} state={state} targetId={launchContactId} onBack={onBack} risk={phoneAppRisk(character,appId)}/>}
function LegacyApp({appId,content,state,targetId,onBack,risk}:{appId:PhoneAppId;content:PhoneAppContent;state?:CharacterPhoneState;targetId?:string;onBack:()=>void;risk:number}){const callContactName=targetId?state?.contacts.find(item=>item.id===targetId)?.name:undefined,calls=appId==="calls"?(content as PhoneCallsContent).records.filter(item=>!callContactName||item.contactName===callContactName):[],calendar=appId==="calendar"?(content as PhoneCalendarContent).events:[],browser=appId==="browser"?(content as PhoneBrowserContent).history:[];return <section className={`role-phone-app role-phone-${appId}`}><header><button onClick={onBack}><ArrowLeft/></button><span className={`phone-app-mark ${appId}`}>{iconOf(appId)}</span><div><small>PRIVATE</small><h2>{PHONE_APPS.find(a=>a.id===appId)?.label}</h2></div></header><div className="role-phone-app-scroll legacy-phone-content">{appId==="gallery"&&<div className="simple-phone-grid">{(content as PhoneGalleryContent).photos.map((item,index)=><article key={index}><ImageIcon/><b>{item.title}</b><small>{item.date} · {item.location}</small><p>{item.description}</p></article>)}</div>}{appId==="browser"&&browser.map((item,index)=><article className={`simple-phone-row ${targetId===`browser:${index}`?"search-target":""}`} key={index}><Search/><div><b>{item.query}</b><small>{item.visitedAt}</small><p>{item.title}</p></div></article>)}{appId==="wallet"&&<><section className="simple-wallet-balance"><small>角色余额</small><b>{yuan((content as PhoneWalletContent).balanceCents)}</b></section>{(content as PhoneWalletContent).transactions.map((item,index)=><article className="simple-phone-row" key={index}><WalletCards/><div><b>{item.title}</b><small>{item.time} · {item.category}</small><p>{item.description}</p></div><strong>{yuan(item.amountCents)}</strong></article>)}</>}{appId==="calendar"&&calendar.map((item:any,index)=><article className={`simple-phone-row ${targetId&&(targetId===item.generationEventId||targetId===`calendar:${index}`)?"search-target":""}`} key={index}><CalendarDays/><div><b>{item.time} · {item.title}</b><small>{item.date} · {item.category}</small><p>{item.note}</p></div></article>)}{appId==="calls"&&calls.map((item,index)=><article className={`simple-phone-row ${callContactName?"search-target":""}`} key={index}><Phone/><div><b>{item.contactName}</b><small>{item.time} · {item.duration}</small><p>{item.details||item.summary}</p></div></article>)}<small className="phone-app-risk-hint">{riskText(risk)}</small></div></section>}