import {useMemo,useRef,useState} from "react";
import {CalendarDays,ChevronLeft,Clock3,ContactRound,FileText,Image as ImageIcon,LockKeyhole,Mail,MapPin,MessageCircleMore,Mic,NotebookText,Phone,Search,Settings,WalletCards,X} from "lucide-react";
import {PHONE_APPS,type PhoneAppId} from "../core/phoneCheck";
import {buildPhoneSearchResults,recentAppSummary,removeRecentPhoneApp,savePhoneSearchQuery,type PhoneSearchResult} from "../core/phoneNavigation";
import type {CharacterPhoneState,PhoneRecentApp} from "../core/types";

const iconOf=(id:PhoneAppId)=>id==="calendar"?<CalendarDays/>:id==="gallery"?<ImageIcon/>:id==="wallet"?<WalletCards/>:id==="browser"?<Search/>:id==="notes"?<NotebookText/>:id==="calls"?<Phone/>:id==="contacts"?<ContactRound/>:id==="mail"?<Mail/>:id==="maps"?<MapPin/>:id==="files"?<FileText/>:id==="voice-memos"?<Mic/>:id==="system-settings"?<Settings/>:<MessageCircleMore/>;
const escapeRegExp=(value:string)=>value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
function Highlight({text,query}:{text:string;query:string}){if(!query.trim())return <>{text}</>;const parts=text.split(new RegExp(`(${escapeRegExp(query.trim())})`,`ig`));return <>{parts.map((part,index)=>part.toLocaleLowerCase()===query.trim().toLocaleLowerCase()?<mark key={index}>{part}</mark>:part)}</>}
export function PhoneGlobalSearchOverlay({state,onChange,onClose,onOpen}:{state:CharacterPhoneState;onChange:(state:CharacterPhoneState)=>void;onClose:()=>void;onOpen:(appId:PhoneAppId,targetId?:string)=>void}){const [query,setQuery]=useState(""),results=useMemo(()=>buildPhoneSearchResults(state,query),[state,query]),groups=useMemo(()=>{const map=new Map<PhoneAppId,PhoneSearchResult[]>();for(const result of results){const rows=map.get(result.appId)??[];rows.push(result);map.set(result.appId,rows)}return[...map.entries()]},[results]);const save=async()=>{if(!query.trim())return;const next=await savePhoneSearchQuery(state.characterId,query);if(next)onChange(next)},open=async(result:PhoneSearchResult)=>{await save();onOpen(result.appId,result.targetId)};return <section className="phone-spotlight"><header><button onClick={onClose}><ChevronLeft/></button><form onSubmit={event=>{event.preventDefault();void save()}}><Search/><input autoFocus value={query} maxLength={120} placeholder="搜索角色手机" onChange={event=>setQuery(event.target.value)}/>{query&&<button type="button" onClick={()=>setQuery("")}><X/></button>}</form></header><main>{!query&&<section className="spotlight-recents"><h3>最近搜索</h3>{(state.searchState?.recentQueries??[]).slice(0,10).map(item=><button key={item.id} onClick={()=>setQuery(item.query)}><Clock3/><span>{item.query}</span></button>)}{!(state.searchState?.recentQueries.length)&&<p>输入联系人、消息、邮件、文件、地点或提醒内容。</p>}<small><LockKeyhole/>隐藏文件不会出现在全局搜索中</small></section>}{query&&groups.map(([appId,rows])=><section className="spotlight-group" key={appId}><h3>{PHONE_APPS.find(item=>item.id===appId)?.label??appId}<span>{rows.length}</span></h3>{rows.slice(0,12).map((result,index)=><button key={`${result.targetId}:${index}`} onClick={()=>void open(result)}><span className={appId}>{iconOf(appId)}</span><div><b><Highlight text={result.title} query={query}/></b><small>{result.subtitle}</small><p><Highlight text={result.snippet.slice(0,160)} query={query}/></p></div></button>)}</section>)}{query&&!results.length&&<div className="spotlight-empty"><Search/><h3>没有找到相关内容</h3><p>隐藏文件不会参与搜索，可以进入文件 App 查看。</p></div>}</main></section>}
export function PhoneRecentAppsOverlay({state,onChange,onClose,onOpen}:{state:CharacterPhoneState;onChange:(state:CharacterPhoneState)=>void;onClose:()=>void;onOpen:(appId:PhoneAppId,targetId?:string)=>void}){const starts=useRef(new Map<string,number>()),rows=(state.recentApps??[]).slice().sort((a,b)=>b.lastOpenedAt-a.lastOpenedAt).slice(0,6),remove=async(row:PhoneRecentApp)=>{const next=await removeRecentPhoneApp(state.characterId,row.appId);if(next)onChange(next)},pointerUp=(row:PhoneRecentApp,event:React.PointerEvent)=>{const start=starts.current.get(row.appId);if(start!==undefined&&start-event.clientY>65)void remove(row);starts.current.delete(row.appId)};return <section className="phone-recent-overlay"><header><button onClick={onClose}><ChevronLeft/></button><div><small>MULTITASKING</small><b>最近使用</b></div><span>{rows.length}/6</span></header><main>{rows.map(row=>{const appId=row.appId as PhoneAppId,summary=recentAppSummary(state,row);return <article key={row.appId} onPointerDown={event=>starts.current.set(row.appId,event.clientY)} onPointerUp={event=>pointerUp(row,event)}><button className="recent-close" aria-label={`关闭 ${summary.title}`} onClick={()=>void remove(row)}><X/></button><button className="recent-card" onClick={()=>onOpen(appId,row.targetId)}><div className={`recent-app-preview ${appId}`}><span>{iconOf(appId)}</span><small>{PHONE_APPS.find(item=>item.id===appId)?.label}</small><h3>{summary.title}</h3><p>{summary.subtitle}</p>{Boolean(summary.badge)&&<i>{summary.badge}</i>}</div><footer><span>{iconOf(appId)}</span><b>{PHONE_APPS.find(item=>item.id===appId)?.label}</b><small>{row.openCount} 次</small></footer></button></article>})}{!rows.length&&<div className="recent-empty"><MessageCircleMore/><h3>还没有最近使用的 App</h3><p>打开角色手机中的 App 后会显示在这里。</p></div>}</main><small className="recent-gesture-tip">向上滑动卡片可关闭，不会删除 App 内容</small></section>}
