import {useEffect,useMemo,useState} from "react";
import {ArrowLeft,AudioLines,Check,Eye,EyeOff,KeyRound,Play,Plus,Radio,RefreshCw,Save,Search,SlidersHorizontal,Sparkles,Trash2,Volume2} from "lucide-react";
import {useNavigate,useSearchParams} from "react-router-dom";
import {getSpeechSettings,setSetting} from "../core/db";
import {normalizeSpeechSettings,SpeechProvider,type SpeechModelOption,type SpeechVoiceOption} from "../core/speech";
import {defaultSpeechSettings,now,uid,type SpeechPreset,type SpeechProviderKind,type SpeechSettings,type SpeechVendorSettings} from "../core/types";

type Catalog={voices:SpeechVoiceOption[];models:SpeechModelOption[]};
const emptyCatalog:Catalog={voices:[],models:[]};

function SectionTitle({icon,title,note,action}:{icon:React.ReactNode;title:string;note:string;action?:React.ReactNode}){
 return <div className="speech-section-title"><span className="speech-section-icon">{icon}</span><div><b>{title}</b><small>{note}</small></div>{action}</div>;
}

function Vendor({kind,value,catalog,query,isDefault,onQuery,onChange,onDefault,onLoad,onTest,busy}:{kind:SpeechProviderKind;value:SpeechVendorSettings;catalog:Catalog;query:string;isDefault:boolean;onQuery:(value:string)=>void;onChange:(next:SpeechVendorSettings)=>void;onDefault:()=>void;onLoad:()=>void;onTest:()=>void;busy:boolean}){
 const [show,setShow]=useState(false),name=kind==="minimax"?"MiniMax":"ElevenLabs",description=kind==="minimax"?"更适合中文表达与细腻情绪，声音参数直接、易于调整。":"拥有丰富的国际音色与模型，可精细控制声音稳定度和风格。";
 const voices=useMemo(()=>catalog.voices.filter(voice=>`${voice.name} ${voice.id} ${voice.category??""}`.toLowerCase().includes(query.toLowerCase())),[catalog.voices,query]);
 return <div className={`speech-provider-page speech-provider-${kind}`}>
  <section className="speech-provider-hero"><div className="speech-provider-orb"><AudioLines/></div><div className="speech-provider-copy"><small>{kind.toUpperCase()} VOICE</small><h2>{name}</h2><p>{description}</p><div className="speech-provider-badges"><span className={value.enabled?"online":"offline"}><i/>{value.enabled?"服务已开启":"服务未开启"}</span>{isDefault&&<span className="default"><Sparkles/>全局默认</span>}</div></div><label className="mini-switch speech-master-switch" aria-label={`${name} 服务开关`}><input type="checkbox" checked={value.enabled} onChange={event=>onChange({...value,enabled:event.target.checked})}/><span/></label></section>
  <div className="speech-provider-default"><span><b>{isDefault?"正在作为默认服务":"设为全局默认服务"}</b><small>{isDefault?"角色选择“跟随全局”时会使用这里的配置":"不会覆盖已经选择语音预设的角色"}</small></span><button className={isDefault?"active":""} disabled={isDefault} onClick={onDefault}>{isDefault?<><Check/>已设为默认</>:"设为默认"}</button></div>
  <section className="speech-config-group speech-connect-group"><SectionTitle icon={<KeyRound/>} title="连接服务" note="密钥只保存在当前设备"/><div className="speech-form-stack"><label><span>API Key</span><div className="secret-input"><input type={show?"text":"password"} value={value.apiKey} onChange={event=>onChange({...value,apiKey:event.target.value})} placeholder="输入服务提供商的 API Key"/><button type="button" aria-label={show?"隐藏密钥":"显示密钥"} onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label><label><span>Base URL</span><input value={value.baseUrl} onChange={event=>onChange({...value,baseUrl:event.target.value})}/></label></div></section>
  <section className="speech-config-group speech-catalog-group"><SectionTitle icon={<Radio/>} title="模型与音色" note={catalog.voices.length?`已读取 ${catalog.voices.length} 个音色 · ${catalog.models.length} 个模型`:"可在线读取，也可以直接填写 ID"} action={<button className="speech-load-catalog" disabled={busy||!value.enabled||!value.apiKey.trim()} onClick={onLoad}><RefreshCw/>拉取列表</button>}/><div className="speech-form-stack"><label><span>模型</span><input list={`speech-models-${kind}`} value={value.model} onChange={event=>onChange({...value,model:event.target.value})} placeholder="选择或输入模型 ID"/><datalist id={`speech-models-${kind}`}>{catalog.models.map(model=><option key={model.id} value={model.id}>{model.name}</option>)}</datalist></label><label><span>Voice ID</span><input value={value.defaultVoiceId} onChange={event=>onChange({...value,defaultVoiceId:event.target.value})} placeholder="选择音色或手动填写 Voice ID"/></label></div>{catalog.voices.length>0&&<div className="speech-voice-library"><label className="speech-voice-search"><Search/><input value={query} onChange={event=>onQuery(event.target.value)} placeholder="搜索音色名称或 ID"/></label><div>{voices.length?voices.map(voice=><button key={voice.id} className={voice.id===value.defaultVoiceId?"active":""} onClick={()=>onChange({...value,defaultVoiceId:voice.id})}><span><b>{voice.name}</b><small>{voice.category??"音色"} · {voice.id}</small></span>{voice.id===value.defaultVoiceId&&<i><Check/>已选择</i>}</button>):<p className="speech-voice-empty">没有匹配的音色</p>}</div></div>}</section>
  <section className="speech-config-group speech-tuning-group"><SectionTitle icon={<SlidersHorizontal/>} title="声音质感" note="参数只会影响之后生成的语音"/><div className="speech-parameter-grid"><label><span>语速</span><input type="number" min="0.5" max="2" step="0.05" value={value.speed} onChange={event=>onChange({...value,speed:Number(event.target.value)})}/></label>{kind==="minimax"?<><label><span>音量</span><input type="number" min="0.1" max="10" step="0.1" value={value.volume??1} onChange={event=>onChange({...value,volume:Number(event.target.value)})}/></label><label><span>音调</span><input type="number" min="-12" max="12" step="1" value={value.pitch??0} onChange={event=>onChange({...value,pitch:Number(event.target.value)})}/></label><label><span>语言增强</span><select value={value.languageBoost??"auto"} onChange={event=>onChange({...value,languageBoost:event.target.value})}><option value="auto">自动</option><option value="Chinese">中文</option><option value="English">English</option><option value="Japanese">日本語</option><option value="Korean">한국어</option></select></label></>:<><label><span>稳定度</span><input type="number" min="0" max="1" step="0.05" value={value.stability??.5} onChange={event=>onChange({...value,stability:Number(event.target.value)})}/></label><label><span>相似度</span><input type="number" min="0" max="1" step="0.05" value={value.similarityBoost??.75} onChange={event=>onChange({...value,similarityBoost:Number(event.target.value)})}/></label><label><span>风格</span><input type="number" min="0" max="1" step="0.05" value={value.style??0} onChange={event=>onChange({...value,style:Number(event.target.value)})}/></label><label className="switch-row compact"><span><b>Speaker Boost</b><small>增强说话者特征</small></span><input type="checkbox" checked={value.useSpeakerBoost!==false} onChange={event=>onChange({...value,useSpeakerBoost:event.target.checked})}/></label></>}</div></section>
  <section className="speech-test-strip"><div><span className="speech-test-icon"><Play/></span><span><b>试听当前音色</b><small>使用页面上方填写的试听文字</small></span></div><button disabled={busy||!value.enabled||!value.apiKey.trim()||!value.defaultVoiceId.trim()} onClick={onTest}>{busy?"处理中…":"开始试听"}</button></section>
  <button className={`speech-clear-key ${value.apiKey?"has-key":"empty-key"}`} disabled={busy||!value.apiKey} onClick={()=>onChange({...value,apiKey:""})}><Trash2/>{value.apiKey?"清除当前服务密钥":"尚未填写服务密钥"}</button>
 </div>;
}

export default function SpeechSettingsPage(){
 const nav=useNavigate(),[params,setParams]=useSearchParams(),activeProvider:SpeechProviderKind=params.get("provider")==="elevenlabs"?"elevenlabs":"minimax",conversationId=params.get("conversationId"),[settings,setSettings]=useState<SpeechSettings>(defaultSpeechSettings),[busy,setBusy]=useState(false),[status,setStatus]=useState(""),[previewText,setPreviewText]=useState("你好，这里是茶茶机的角色语音试听。"),[catalogs,setCatalogs]=useState<Record<SpeechProviderKind,Catalog>>({minimax:emptyCatalog,elevenlabs:emptyCatalog}),[queries,setQueries]=useState<Record<SpeechProviderKind,string>>({minimax:"",elevenlabs:""}),[presetName,setPresetName]=useState(""),[editingPresetId,setEditingPresetId]=useState("");
 useEffect(()=>{void getSpeechSettings().then(value=>setSettings(normalizeSpeechSettings(value)))},[]);
 const patch=(kind:SpeechProviderKind,next:SpeechVendorSettings)=>setSettings(current=>({...current,[kind]:next}));
 const changeProvider=(kind:SpeechProviderKind)=>{const next=new URLSearchParams(params);next.set("provider",kind);setParams(next)};
 const save=async()=>{setBusy(true);try{const normalized=normalizeSpeechSettings(settings);await setSetting("speech",normalized);setSettings(normalized);setStatus("语音设置已保存在当前浏览器")}finally{setBusy(false)}};
 const test=async(kind:SpeechProviderKind)=>{if(!previewText.trim())return;setBusy(true);setStatus("正在生成试听语音…");try{const blob=await new SpeechProvider(kind,settings[kind]).synthesize(previewText.trim()),url=URL.createObjectURL(blob),audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);audio.onerror=()=>URL.revokeObjectURL(url);await audio.play();setStatus("试听已开始播放")}catch(error){setStatus(error instanceof Error?error.message:"试听失败")}finally{setBusy(false)}};
 const loadCatalog=async(kind:SpeechProviderKind)=>{setBusy(true);setStatus(`正在读取 ${kind==="minimax"?"MiniMax":"ElevenLabs"} 音色…`);try{const provider=new SpeechProvider(kind,settings[kind]),[voices,models]=await Promise.all([provider.listVoices(),provider.listModels()]);setCatalogs(current=>({...current,[kind]:{voices,models}}));setStatus(`已读取 ${voices.length} 个音色和 ${models.length} 个模型`)}catch(error){setStatus(error instanceof Error?error.message:"读取音色失败")}finally{setBusy(false)}};
 const savePreset=async()=>{const name=presetName.trim(),voice=settings[activeProvider];if(!name){setStatus("请先填写预设名称");return}if(!voice.apiKey.trim()||!voice.model.trim()||!voice.defaultVoiceId.trim()){setStatus("保存预设前请填写 API Key、模型和 Voice ID");return}const t=now(),existing=settings.presets.find(item=>item.id===editingPresetId),preset:SpeechPreset={id:existing?.id??uid(),name:name.slice(0,40),provider:activeProvider,settings:{...voice},createdAt:existing?.createdAt??t,updatedAt:t},next=normalizeSpeechSettings({...settings,presets:existing?settings.presets.map(item=>item.id===existing.id?preset:item):[...settings.presets,preset]});await setSetting("speech",next);setSettings(next);setEditingPresetId(preset.id);setPresetName(preset.name);setStatus(`已保存语音预设“${preset.name}”`)};
 const loadPreset=(preset:SpeechPreset)=>{setSettings(current=>({...current,[preset.provider]:{...preset.settings}}));setEditingPresetId(preset.id);setPresetName(preset.name);changeProvider(preset.provider);setStatus(`已载入预设“${preset.name}”，修改后可再次保存`)};
 const removePreset=async(id:string)=>{const next=normalizeSpeechSettings({...settings,presets:settings.presets.filter(item=>item.id!==id)});await setSetting("speech",next);setSettings(next);if(editingPresetId===id){setEditingPresetId("");setPresetName("")}setStatus("语音预设已删除")};
 return <div className="page speech-settings-page">
  <header className="page-head speech-page-head"><button aria-label="返回" onClick={()=>nav(conversationId?`/messages/${conversationId}/settings`:"/settings")}><ArrowLeft/></button><div><small>CHARACTER VOICE</small><h1>角色语音服务</h1></div></header>
  <nav className="speech-provider-tabs" aria-label="语音服务切换"><button className={activeProvider==="minimax"?"active":""} onClick={()=>changeProvider("minimax")}><i className="minimax"><AudioLines/></i><span><b>MiniMax</b><small>中文与情绪</small></span>{settings.defaultProvider==="minimax"&&<em>默认</em>}</button><button className={activeProvider==="elevenlabs"?"active":""} onClick={()=>changeProvider("elevenlabs")}><i className="elevenlabs"><AudioLines/></i><span><b>ElevenLabs</b><small>国际与拟真</small></span>{settings.defaultProvider==="elevenlabs"&&<em>默认</em>}</button></nav>
  <main className="speech-settings-body">
   <section className="speech-preset-panel"><SectionTitle icon={<Sparkles/>} title="语音预设" note="保存服务、模型、音色和声音参数，之后可在每个角色的聊天设置中选择"/><div className="speech-preset-editor"><input maxLength={40} value={presetName} onChange={event=>setPresetName(event.target.value)} placeholder="输入预设名称，例如：低沉男声"/><button onClick={()=>{setEditingPresetId("");setPresetName("")}}><Plus/>新建</button><button className="save" disabled={busy} onClick={()=>void savePreset()}><Save/>{editingPresetId?"更新":"保存"}</button></div><div className="speech-preset-list">{settings.presets.length?settings.presets.map(preset=><article key={preset.id} className={preset.id===editingPresetId?"active":""}><button onClick={()=>loadPreset(preset)}><span><b>{preset.name}</b><small>{preset.provider==="minimax"?"MiniMax":"ElevenLabs"} · {preset.settings.defaultVoiceId||"未选择音色"}</small></span><em>载入</em></button><button className="danger" aria-label={`删除预设 ${preset.name}`} onClick={()=>void removePreset(preset.id)}><Trash2/></button></article>):<p>还没有语音预设。配置好当前服务后输入名称保存即可。</p>}</div><small className="speech-preset-note">预设中的 API Key 只保存在当前设备，导出聊天备份时会自动清除。</small></section>
   <section className="speech-preview-copy"><div className="speech-preview-heading"><span><Volume2/></span><div><b>试听文案</b><small>写一句最能听出角色语气的话</small></div></div><textarea rows={3} maxLength={500} value={previewText} onChange={event=>setPreviewText(event.target.value)}/><footer><span>{previewText.length}/500</span><small>API Key 与在线列表都不会进入备份</small></footer></section>
   {activeProvider==="minimax"?<Vendor kind="minimax" value={settings.minimax} catalog={catalogs.minimax} query={queries.minimax} isDefault={settings.defaultProvider==="minimax"} onQuery={value=>setQueries(current=>({...current,minimax:value}))} onChange={value=>patch("minimax",value)} onDefault={()=>setSettings(current=>({...current,defaultProvider:"minimax"}))} onLoad={()=>void loadCatalog("minimax")} onTest={()=>void test("minimax")} busy={busy}/>:<Vendor kind="elevenlabs" value={settings.elevenlabs} catalog={catalogs.elevenlabs} query={queries.elevenlabs} isDefault={settings.defaultProvider==="elevenlabs"} onQuery={value=>setQueries(current=>({...current,elevenlabs:value}))} onChange={value=>patch("elevenlabs",value)} onDefault={()=>setSettings(current=>({...current,defaultProvider:"elevenlabs"}))} onLoad={()=>void loadCatalog("elevenlabs")} onTest={()=>void test("elevenlabs")} busy={busy}/>} 
   {status&&<div className="settings-toast speech-status-toast"><Volume2/>{status}</div>}
   <section className="speech-save-panel"><div><span className="speech-save-mark"><Save/></span><span><b>保存当前服务</b><small>确认后立即用于跟随全局设置的角色</small></span></div><button className="speech-save-button" disabled={busy} onClick={save}>{busy?"正在保存…":`保存 ${activeProvider==="minimax"?"MiniMax":"ElevenLabs"} 设置`}</button></section>
  </main>
 </div>;
}