import {useCallback,useEffect,useLayoutEffect,useMemo,useRef,useState,type CSSProperties,type PointerEvent as ReactPointerEvent} from "react";
import {ArrowDown,Heart,Languages,ListMusic,Pause,Play,Repeat2,Shuffle,SkipBack,SkipForward,Timer,Type,Volume2,X} from "lucide-react";
import {activeLyricIndex,isInteractiveSwipeTarget} from "../core/musicImmersive";
import {useMusicPlayer} from "../core/musicPlayer";

type PlayerView="cover"|"lyrics";
type Props={onClose:()=>void;onOpenQueue:()=>void;onEdit:()=>void;onNotice:(message:string)=>void};
const formatDuration=(ms=0)=>{const total=Math.max(0,Math.floor(ms/1000));return `${Math.floor(total/60)}:${String(total%60).padStart(2,"0")}`};

export function MusicNowPlaying({onClose,onOpenQueue,onEdit,onNotice}:Props){
 const player=useMusicPlayer(),[view,setView]=useState<PlayerView>("cover"),[showTimer,setShowTimer]=useState(false),[followPaused,setFollowPaused]=useState(false);
 const lyricNodes=useRef(new Map<number,HTMLButtonElement>()),lyricsScrollRef=useRef<HTMLDivElement|null>(null),autoScrollRef=useRef(false),followTimerRef=useRef<number|undefined>(undefined),swipeRef=useRef<{x:number;y:number;id:number}|undefined>(undefined);
 const track=player.currentTrack,plainLyrics=track?.lyricsKind==="plain"&&track.customLyrics,activeIndex=activeLyricIndex(player.lyrics,player.positionMs),hasTranslation=player.lyrics.some(line=>Boolean(line.translation));
 const backgroundStyle=useMemo<CSSProperties>(()=>track?.coverUrl?{backgroundImage:`url(${JSON.stringify(track.coverUrl)})`}:{},[track?.coverUrl]);
 useLayoutEffect(()=>{const root=document.querySelector(".music-now-immersive");for(const node of [document.scrollingElement,root?.closest(".screen"),root?.closest(".phone")])if(node instanceof HTMLElement)node.scrollTop=0},[player.lyrics.length,track?.id,view]);
 useEffect(()=>{setView("cover");setFollowPaused(false)},[track?.id]);
 useEffect(()=>()=>{if(followTimerRef.current)window.clearTimeout(followTimerRef.current)},[]);
 const scrollToActive=useCallback((behavior:ScrollBehavior="smooth")=>{const container=lyricsScrollRef.current,node=lyricNodes.current.get(activeIndex);if(!container||!node)return;autoScrollRef.current=true;const top=node.offsetTop-container.clientHeight/2+node.clientHeight/2;if(typeof container.scrollTo==="function")container.scrollTo({top:Math.max(0,top),behavior});else container.scrollTop=Math.max(0,top);window.setTimeout(()=>{autoScrollRef.current=false},450)},[activeIndex]);
 useEffect(()=>{if(view!=="lyrics"||plainLyrics||followPaused||activeIndex<0)return;scrollToActive()},[activeIndex,followPaused,plainLyrics,scrollToActive,view]);
 if(!track)return null;
 const suspendFollow=()=>{if(autoScrollRef.current||plainLyrics)return;setFollowPaused(true);if(followTimerRef.current)window.clearTimeout(followTimerRef.current);followTimerRef.current=window.setTimeout(()=>setFollowPaused(false),8000)};
 const resumeFollow=()=>{setFollowPaused(false);scrollToActive()};
 const onPointerDown=(event:ReactPointerEvent<HTMLElement>)=>{if(isInteractiveSwipeTarget(event.target))return;swipeRef.current={x:event.clientX,y:event.clientY,id:event.pointerId}};
 const onPointerUp=(event:ReactPointerEvent<HTMLElement>)=>{const start=swipeRef.current;swipeRef.current=undefined;if(!start||start.id!==event.pointerId)return;const dx=event.clientX-start.x,dy=event.clientY-start.y;if(Math.abs(dx)<56||Math.abs(dx)<=Math.abs(dy)*1.2)return;setView(dx<0?"lyrics":"cover")};
 const setDurationTimer=(minutes:number)=>{player.setSleepTimer({mode:"duration",endsAt:Date.now()+minutes*60000});setShowTimer(false);onNotice(`已设置 ${minutes} 分钟睡眠定时`)};
 const setTrackTimer=()=>{player.setSleepTimer({mode:"track-end",trackId:track.id});setShowTimer(false);onNotice("将在本曲播完后渐弱暂停")};
 const cancelTimer=()=>{player.cancelSleepTimer();setShowTimer(false);onNotice("睡眠定时已取消")};
 return <main className={`music-page music-now-page music-now-immersive view-${view}`} onPointerDown={onPointerDown} onPointerUp={onPointerUp}>
  <div className="music-now-backdrop" style={backgroundStyle} aria-hidden="true"/><div className="music-now-shade" aria-hidden="true"/>
  <header className="music-now-head"><button type="button" aria-label="返回音乐页" onClick={onClose}><ArrowDown aria-hidden="true"/></button><div><small>正在播放</small><b>{track.album||"茶茶机音乐"}</b></div><button type="button" aria-label="打开播放队列" onClick={onOpenQueue}><ListMusic aria-hidden="true"/></button></header>
  <div className="music-now-view-tabs" role="tablist" aria-label="播放页视图"><button type="button" role="tab" aria-selected={view==="cover"} className={view==="cover"?"active":""} onClick={()=>setView("cover")}><span/>封面</button><button type="button" role="tab" aria-selected={view==="lyrics"} className={view==="lyrics"?"active":""} onClick={()=>setView("lyrics")}><span/>歌词</button></div>
  <div className="music-now-pager"><section className="music-now-pane music-now-cover-pane" aria-hidden={view!=="cover"}>
   <div className="music-now-cover">{track.coverUrl?<img src={track.coverUrl} alt=""/>:<span>♪</span>}</div>
   <div className="music-now-meta"><div><h2>{track.title}</h2><p>{track.artists.join(" / ")}</p></div><button type="button" className={track.favorite?"is-favorite":""} aria-label={track.favorite?"取消收藏":"收藏"} onClick={()=>void player.toggleFavorite(track.id)}><Heart aria-hidden="true" fill={track.favorite?"currentColor":"none"}/></button></div>
   <input className="music-progress" type="range" min={0} max={Math.max(1,player.durationMs)} value={Math.min(player.positionMs,Math.max(1,player.durationMs))} onChange={event=>player.seek(Number(event.target.value))} aria-label="播放进度"/>
   <div className="music-time"><span>{formatDuration(player.positionMs)}</span><span>{formatDuration(player.durationMs)}</span></div>
   <div className="music-now-controls"><button type="button" className={player.shuffle?"active":""} aria-label="随机播放" onClick={player.toggleShuffle}><Shuffle aria-hidden="true"/></button><button type="button" aria-label="上一首" onClick={()=>void player.previous()}><SkipBack aria-hidden="true"/></button><button type="button" className="music-play-large" aria-label={player.playing?"暂停":"播放"} onClick={()=>void player.toggle()}>{player.playing?<Pause aria-hidden="true"/>:<Play aria-hidden="true"/>}</button><button type="button" aria-label="下一首" onClick={()=>void player.next()}><SkipForward aria-hidden="true"/></button><button type="button" className={player.repeatMode!=="off"?"active":""} aria-label={`循环模式：${player.repeatMode}`} onClick={player.cycleRepeat}><Repeat2 aria-hidden="true"/>{player.repeatMode==="one"?<small>1</small>:null}</button></div>
   <div className="music-now-utilities"><label className="music-volume"><Volume2 aria-hidden="true"/><input type="range" min={0} max={1} step={.01} value={player.volume} onChange={event=>player.setVolume(Number(event.target.value))} aria-label="音量"/><span>{Math.round(player.volume*100)}%</span></label><button type="button" className={player.sleepTimer?"active":""} onClick={()=>setShowTimer(true)} aria-label={player.sleepTimer?`睡眠定时剩余 ${player.sleepTimerLabel}`:"设置睡眠定时"}><Timer aria-hidden="true"/><span>{player.sleepTimer?player.sleepTimerLabel:"睡眠定时"}</span></button></div>
  </section><section className="music-now-pane music-now-lyrics-pane" aria-hidden={view!=="lyrics"}>
   <div className="music-lyrics-toolbar"><div><b>{plainLyrics?"静态歌词":"同步歌词"}</b><small>{plainLyrics?"TXT 歌词":"点击歌词可跳转"}</small></div><div>{hasTranslation?<button type="button" className={player.lyricsTranslationVisible?"active":""} aria-label={player.lyricsTranslationVisible?"隐藏翻译":"显示翻译"} onClick={()=>player.setLyricsTranslationVisible(!player.lyricsTranslationVisible)}><Languages aria-hidden="true"/></button>:null}<div className="music-lyrics-size" role="group" aria-label="歌词字号"><Type aria-hidden="true"/>{(["small","medium","large"] as const).map((size,index)=><button type="button" key={size} className={player.lyricsFontSize===size?"active":""} aria-label={`${["小","中","大"][index]}号歌词`} onClick={()=>player.setLyricsFontSize(size)}>{["小","中","大"][index]}</button>)}</div></div></div>
   <div ref={lyricsScrollRef} className={`music-lyrics-scroll immersive size-${player.lyricsFontSize}`} data-no-player-swipe onScroll={suspendFollow}>{plainLyrics?plainLyrics.split(/\r?\n/).filter(Boolean).map((line,index)=><p key={`${index}-${line}`}>{line}</p>):player.lyrics.length?player.lyrics.map((line,index)=>{const distance=Math.abs(index-activeIndex);return <button type="button" key={`${line.timeMs}-${index}`} ref={node=>{if(node)lyricNodes.current.set(index,node);else lyricNodes.current.delete(index)}} className={`${index===activeIndex?"active ":""}${distance===1?"near":""}`} onClick={()=>{player.seek(line.timeMs);resumeFollow()}}><span>{line.text||"…"}</span>{line.translation&&player.lyricsTranslationVisible?<small>{line.translation}</small>:null}</button>}):<div className="music-lyrics-empty"><p>暂无歌词</p><small>可以导入 LRC 或 TXT 歌词文件。</small><button type="button" onClick={onEdit}>导入或编辑歌词</button></div>}</div>
   {followPaused&&!plainLyrics?<button type="button" className="music-lyrics-follow" onClick={resumeFollow}>回到当前歌词</button>:null}<button type="button" className="music-lyrics-edit" onClick={onEdit}>编辑歌词</button>
  </section></div>
  {showTimer?<div className="music-overlay music-now-overlay" role="presentation" onClick={()=>setShowTimer(false)}><section className="music-sleep-sheet" role="dialog" aria-modal="true" aria-label="睡眠定时" onClick={event=>event.stopPropagation()}><header><div><h3>睡眠定时</h3><small>最后 10 秒会逐渐降低音量</small></div><button type="button" aria-label="关闭" onClick={()=>setShowTimer(false)}><X aria-hidden="true"/></button></header>{player.sleepTimer?<div className="music-sleep-active"><Timer aria-hidden="true"/><span><b>{player.sleepTimerLabel}</b><small>到时暂停，保留一起听会话</small></span></div>:null}<div className="music-sleep-options"><button type="button" onClick={setTrackTimer}>本曲播完<small>切歌时自动取消</small></button>{[15,30,45,60].map(minutes=><button type="button" key={minutes} onClick={()=>setDurationTimer(minutes)}>{minutes} 分钟</button>)}</div>{player.sleepTimer?<button type="button" className="music-sleep-cancel" onClick={cancelTimer}>取消定时</button>:null}</section></div>:null}
 </main>
}