import {describe,it} from "vitest";
import {strict as assert} from "node:assert";
import {createHash,createPublicKey,generateKeyPairSync,verify} from "node:crypto";
import serviceModule from "../../cloudfunctions/activation-gateway/service.js";
const {canonicalPayload,createActivationService,hashCode}=serviceModule;
function fixture(){const {privateKey,publicKey}=generateKeyPairSync("ec",{namedCurve:"prime256v1",privateKeyEncoding:{type:"pkcs8",format:"pem"},publicKeyEncoding:{type:"spki",format:"pem"}}),publicObject=createPublicKey(publicKey),spki=publicObject.export({format:"der",type:"spki"}),device={method:"p256",publicKeyJwk:publicObject.export({format:"jwk"}),keyHash:createHash("sha256").update(spki).digest("base64url"),clientVersion:"test"},code="MATCHAABCDEFGH23456789",records=new Map([[hashCode(code),{_id:hashCode(code),status:"unused"}]]),attempts=new Map(),repository={async getCode(id){return records.get(id)??null},async claimCode(id,data){const row=records.get(id);if(!row||row.status!=="unused")return false;records.set(id,{...row,...data});return true},async getAttempt(uid){return attempts.get(uid)??null},async setAttempt(uid,data){attempts.set(uid,data)},async clearAttempt(uid){attempts.delete(uid)}};return{privateKey,publicObject,device,code,records,attempts,activate:createActivationService({repository,privateKeyPem:privateKey,publicKeyId:"key-1",now:()=>1000})}}
describe("activation gateway service",()=>{
 it("atomically binds one code and returns an idempotent signed license",async()=>{const ctx=fixture(),first=await ctx.activate({uid:"u1",code:ctx.code,requestId:"r1",device:ctx.device}),retry=await ctx.activate({uid:"u1",code:ctx.code,requestId:"r2",device:ctx.device}),other=await ctx.activate({uid:"u2",code:ctx.code,requestId:"r3",device:ctx.device});assert.equal(first.ok,true);assert.equal(retry.ok,true);assert.deepEqual(first.license.payload,retry.license.payload);assert.deepEqual(other,{ok:false,reason:"already-used"});assert.equal(verify("sha256",Buffer.from(canonicalPayload(first.license.payload)),{key:ctx.publicObject,dsaEncoding:"ieee-p1363"},Buffer.from(first.license.signature,"base64url")),true)});
 it("allows only one winner during concurrent activation",async()=>{const ctx=fixture(),[a,b]=await Promise.all([ctx.activate({uid:"u1",code:ctx.code,requestId:"a",device:ctx.device}),ctx.activate({uid:"u2",code:ctx.code,requestId:"b",device:{...ctx.device,keyHash:"A".repeat(43)}})]);assert.equal(Number(a.ok)+Number(b.ok),1)});
 it("rate limits repeated invalid attempts without revealing the code",async()=>{const ctx=fixture();for(let index=0;index<5;index++)assert.deepEqual(await ctx.activate({uid:"bad",code:"wrong",requestId:String(index),device:ctx.device}),{ok:false,reason:"invalid-code"});assert.deepEqual(await ctx.activate({uid:"bad",code:"wrong",requestId:"six",device:ctx.device}),{ok:false,reason:"rate-limited"})});
 it("rejects unauthenticated and mismatched device requests",async()=>{const ctx=fixture();assert.deepEqual(await ctx.activate({uid:"",code:ctx.code,requestId:"x",device:ctx.device}),{ok:false,reason:"unauthenticated"});assert.deepEqual(await ctx.activate({uid:"u1",code:ctx.code,requestId:"x",device:{...ctx.device,keyHash:"A".repeat(43)}}),{ok:false,reason:"invalid-device"})});
});
