import {z} from "zod";
import {coreSettingOf,personaOf} from "./character";
import {buildContext} from "./context";
import {prepareRoleplayResources,reviewCharacterReply} from "./personaEngine";
import {canCharacterInteract} from "./conversationSettings";
import {db,getAppSettings,getMallWalletSettings} from "./db";
import {pauseActiveMeetForOnlineActivity} from "./crossModeContinuity";
import {generateCharacterMessageGroup} from "./groupChat";
import {groupActors,groupNpcAsCharacter} from "./groupNpcs";
import {resolveSecondaryProvider} from "./modelServices";
import {OpenAIProvider} from "./provider";
import {now,SCHEMA_VERSION,uid,type Character,type Conversation,type GroupNpc,type Message,type PollVote,type ProviderSettings,type RedPacketClaim,type WalletTransaction} from "./types";

export function splitRedPacket(total:number,count:number,random=Math.random){const cents=Math.round(total),n=Math.trunc(count);if(n<1||cents<n)throw new Error("红包金额必须保证每个红包至少 0.01 元");const values=Array(n).fill(1),remaining=cents-n;for(let i=0;i<remaining;i++)values[Math.floor(random()*n)]++;return values}
function shuffle<T>(items:T[],random=Math.random){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}

export async function createGroupRedPacket(input:{conversation:Conversation;members:Character[];npcs?:GroupNpc[];totalAmountCents:number;packetCount:number;note:string;eventId?:string;random?:()=>number}){
 if(input.conversation.type!=="group")throw new Error("只有群聊可以发送红包");
 const characterActors=input.members.filter(member=>canCharacterInteract(member)).map(member=>({type:"character" as const,id:member.id,name:member.name})),npcActors=(input.npcs??input.conversation.groupNpcs??[]).filter(npc=>npc.active).map(npc=>({type:"npc" as const,id:npc.id,name:npc.name})),eligible=[...characterActors,...npcActors];
 if(!eligible.length)throw new Error("群聊中没有可领取红包的成员");
 const count=Math.max(1,Math.min(eligible.length,Math.trunc(input.packetCount))),total=Math.round(input.totalAmountCents),eventId=input.eventId??uid(),existing=await db.messages.where("conversationId").equals(input.conversation.id).filter(message=>message.kind==="red-packet"&&message.attachments?.some(item=>item.type==="red-packet"&&item.eventId===eventId)===true).first();if(existing)return existing;
 const random=input.random??Math.random,claimers=shuffle(eligible,random).slice(0,count),amounts=splitRedPacket(total,count,random),t=now(),messageId=uid(),transactionId=uid(),claims:RedPacketClaim[]=claimers.map((actor,index)=>({participantType:actor.type,participantId:actor.id,participantName:actor.name,characterId:actor.id,characterName:actor.name,amountCents:amounts[index],claimedAt:t+index})),wallet=await getMallWalletSettings();if(wallet.balanceCents<total)throw new Error("钱包余额不足");
 const transaction:WalletTransaction={id:transactionId,schemaVersion:SCHEMA_VERSION,createdAt:t,updatedAt:t,kind:"red-packet",amountCents:-total,state:"completed",title:input.note.trim()||"群聊红包",messageId},message:Message={id:messageId,schemaVersion:SCHEMA_VERSION,createdAt:t,updatedAt:t,conversationId:input.conversation.id,senderType:"user",content:`[红包] ¥${(total/100).toFixed(2)} · ${input.note.trim()||"恭喜发财"}`,kind:"red-packet",attachments:[{type:"red-packet",eventId,totalAmountCents:total,packetCount:count,note:input.note.trim()||"恭喜发财",claims,walletTransactionId:transactionId,state:"completed"}],status:"complete",proactiveEventId:eventId};
 await db.transaction("rw",[db.settings,db.walletTransactions,db.messages,db.conversations,db.meetSessions],async()=>{await pauseActiveMeetForOnlineActivity(input.conversation.id,t);await db.settings.put({key:"mall-wallet",value:{...wallet,balanceCents:wallet.balanceCents-total,updatedAt:t}});await db.walletTransactions.add(transaction);await db.messages.add(message);await db.conversations.update(input.conversation.id,{lastActivityAt:t,updatedAt:t})});return message
}

const voteSchema=z.object({optionIds:z.array(z.string()).min(1)});
export async function createGroupPoll(input:{conversation:Conversation;question:string;mode:"single"|"multiple";options:string[];createdBy:"user"|"assistant"}){const clean=input.options.map(value=>value.trim()).filter(Boolean).slice(0,8);if(input.conversation.type!=="group"||clean.length<2)throw new Error("投票至少需要两个选项");const t=now(),message:Message={id:uid(),schemaVersion:SCHEMA_VERSION,createdAt:t,updatedAt:t,conversationId:input.conversation.id,senderType:input.createdBy==="user"?"user":"system",content:`[投票] ${input.question.trim()}`,kind:"poll",attachments:[{type:"poll",pollId:uid(),question:input.question.trim().slice(0,100),mode:input.mode,options:clean.map(text=>({id:uid(),text})),votes:[],state:"open",createdBy:input.createdBy}],status:"complete"};await db.transaction("rw",[db.messages,db.conversations,db.meetSessions],async()=>{if(input.createdBy==="user")await pauseActiveMeetForOnlineActivity(input.conversation.id,t);await db.messages.add(message);await db.conversations.update(input.conversation.id,{lastActivityAt:t,updatedAt:t})});return message}
export async function generateCharacterPollVotes(messageId:string,members:Character[],primary:ProviderSettings,npcs:GroupNpc[]=[]){const message=await db.messages.get(messageId),attachment=message?.attachments?.find(item=>item.type==="poll");if(!message||!attachment||attachment.type!=="poll"||attachment.state!=="open")return;const provider=await resolveSecondaryProvider(primary),validIds=new Set(attachment.options.map(option=>option.id)),votes:PollVote[]=[],actors=[...members.filter(member=>canCharacterInteract(member)).map(character=>({type:"character" as const,id:character.id,name:character.name,profile:character})),...npcs.filter(npc=>npc.active).map(npc=>({type:"npc" as const,id:npc.id,name:npc.name,profile:groupNpcAsCharacter(npc)}))];for(const actor of actors){try{const prompt=[`成员：${actor.name}`,`核心设定：${coreSettingOf(actor.profile)}`,`人物设定：${personaOf(actor.profile)}`,`投票题目：${attachment.question}`,`模式：${attachment.mode==="single"?"单选":"多选"}`,`选项：${attachment.options.map(option=>`${option.id}=${option.text}`).join("；")}`,attachment.mode==="single"?'只返回 JSON：{"optionIds":["一个选项ID"]}':'只返回 JSON：{"optionIds":["一个或多个选项ID"]}'].join("\n");const raw=await new OpenAIProvider({...provider,stream:false}).chat([{role:"system",content:"你只负责依据成员人设完成群聊投票，只输出严格 JSON。"},{role:"user",content:prompt}],{stream:false}),parsed=voteSchema.parse(JSON.parse(raw.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/, ""))),ids=[...new Set(parsed.optionIds.filter(id=>validIds.has(id)))].slice(0,attachment.mode==="single"?1:attachment.options.length);if(ids.length)votes.push({voterType:actor.type,voterId:actor.id,voterName:actor.name,optionIds:ids,createdAt:now()});else throw new Error("无有效选项")}catch{const option=attachment.options[Math.abs(actor.id.split("").reduce((sum,char)=>sum+char.charCodeAt(0),0))%attachment.options.length];votes.push({voterType:actor.type,voterId:actor.id,voterName:actor.name,optionIds:[option.id],createdAt:now()})}}
 const current=await db.messages.get(messageId),poll=current?.attachments?.find(item=>item.type==="poll");if(!current||!poll||poll.type!=="poll")return;await db.messages.update(messageId,{attachments:(current.attachments??[]).map(item=>item.type==="poll"?{...item,votes:[...item.votes.filter(vote=>vote.voterType==="user"),...votes]}:item),updatedAt:now()})}
export async function voteInPoll(messageId:string,optionIds:string[],userName:string){const message=await db.messages.get(messageId),poll=message?.attachments?.find(item=>item.type==="poll");if(!message||!poll||poll.type!=="poll"||poll.state!=="open")return;const valid=new Set(poll.options.map(option=>option.id)),ids=[...new Set(optionIds.filter(id=>valid.has(id)))].slice(0,poll.mode==="single"?1:poll.options.length);if(!ids.length)return;const vote:PollVote={voterType:"user",voterName:userName||"我",optionIds:ids,createdAt:now()};await db.messages.update(messageId,{attachments:(message.attachments??[]).map(item=>item.type==="poll"?{...item,votes:[...item.votes.filter(row=>row.voterType!=="user"),vote]}:item),updatedAt:now()})}
export async function closePoll(messageId:string){const message=await db.messages.get(messageId);if(!message)return;await db.messages.update(messageId,{attachments:(message.attachments??[]).map(item=>item.type==="poll"?{...item,state:"closed" as const,closedAt:now()}:item),updatedAt:now()})}
export async function saveDirectorInstruction(conversation:Conversation,text:string){const t=now(),message:Message={id:uid(),schemaVersion:SCHEMA_VERSION,createdAt:t,updatedAt:t,conversationId:conversation.id,senderType:"system",content:text.trim(),kind:"director",visibility:"private",status:"complete"};await db.transaction("rw",[db.messages,db.conversations],async()=>{await db.messages.add(message);await db.conversations.update(conversation.id,{lastActivityAt:t,updatedAt:t})});return message}

export async function addGroupMembers(input:{conversation:Conversation;memberIds?:string[];npcs?:GroupNpc[];provider?:ProviderSettings}){
 const current=new Set(input.conversation.memberIds),addedIds=(input.memberIds??[]).filter(id=>!current.has(id)),characters=(await db.characters.bulkGet(addedIds)).filter(Boolean) as Character[],incoming=input.npcs??[],existingNpcs=input.conversation.groupNpcs??[],npcMap=new Map(existingNpcs.map(npc=>[npc.id,npc])),addedNpcs:GroupNpc[]=[];for(const npc of incoming){const old=npcMap.get(npc.id);const next={...(old??npc),...npc,active:true,updatedAt:now()};npcMap.set(npc.id,next);addedNpcs.push(next)}if(!characters.length&&!addedNpcs.length)return;
 const t=now(),eventId=uid(),names=[...characters.map(character=>character.name),...addedNpcs.map(npc=>npc.name)],content=`${names.join("、")}加入了群聊`,event:Message={id:uid(),schemaVersion:SCHEMA_VERSION,createdAt:t,updatedAt:t,conversationId:input.conversation.id,senderType:"system",content,kind:"group-event",status:"complete",proactiveEventId:eventId};
 await db.transaction("rw",[db.conversations,db.messages],async()=>{await db.conversations.update(input.conversation.id,{memberIds:[...current,...addedIds],groupNpcs:[...npcMap.values()],lastActivityAt:t,updatedAt:t});await db.messages.add(event)});if(input.provider?.apiKey)await generateGroupEventReactions(input.conversation.id,eventId,[...addedIds,...addedNpcs.map(npc=>npc.id)],input.provider);return event
}
export async function generateGroupEventReactions(conversationId:string,eventId:string,priorityIds:string[],provider:ProviderSettings){
 const [conversation,characters,messages,loreBooks,memories,app,mediaAssets]=await Promise.all([db.conversations.get(conversationId),db.characters.toArray(),db.messages.where("conversationId").equals(conversationId).sortBy("createdAt"),db.loreBooks.toArray(),db.memories.toArray(),getAppSettings(),db.mediaAssets.toArray()]);if(!conversation)return;
 const actors=groupActors(conversation,characters,mediaAssets).filter(actor=>actor.type==="npc"||canCharacterInteract(actor.character)),priority=priorityIds.map(id=>actors.find(actor=>actor.id===id)).filter(Boolean) as typeof actors,others=actors.filter(actor=>!priorityIds.includes(actor.id)),speakers=actors.length<=6?actors:[...priority,...others.slice(0,Math.max(0,6-priority.length))].slice(0,6),base=now();let offset=0;
 for(const speaker of speakers)try{const prepared=await prepareRoleplayResources({character:speaker.character,conversation,loreBooks,provider}),profiles=actors.map(actor=>actor.id===speaker.id?prepared.character:actor.character),ctx=buildContext({character:prepared.character,conversation,messages,loreBooks:prepared.loreBooks,memories,userText:`群聊刚发生了成员变化，请以${speaker.name}身份自然回应。`,settings:app,provider,characters:profiles,groupNpcs:conversation.groupNpcs,mediaAssets,scene:"group-event"}),draft=await generateCharacterMessageGroup(provider,ctx,prepared.character),review=await reviewCharacterReply({character:prepared.character,conversation,scene:"group-event",draftMessages:draft,messages,characters:profiles,groupNpcs:conversation.groupNpcs,loreBooks:prepared.loreBooks,memories,settings:app,provider}),parts=review.revisedMessages.slice(0,2),rows=parts.map((content,index):Message=>({id:uid(),schemaVersion:SCHEMA_VERSION,createdAt:base+offset+index,updatedAt:base+offset+index,conversationId,senderType:speaker.type,senderId:speaker.id,content,status:"complete",generation:{model:provider.model,temperature:provider.temperature,stream:false,roundId:eventId,speakerTurnId:uid(),segmentIndex:index}}));offset+=rows.length;if(rows.length)await db.messages.bulkAdd(rows)}catch{}
 await db.conversations.update(conversationId,{lastActivityAt:base+offset,updatedAt:now()})
}