import {z} from "zod";
import {blobToDataUrl} from "./mediaAssets";
import type {ImageGenerationProviderKind,ImageGenerationSettings} from "./types";

export interface ImageGenerationRequest{prompt:string;negativePrompt?:string;referenceDataUrl?:string}
export interface ImageGenerationResult{dataUrl:string;provider:ImageGenerationProviderKind;model:string}
export class ImageGenerationError extends Error{constructor(public code:"config"|"auth"|"quota"|"cors"|"network"|"response",message:string){super(message)}}
const cleanBase=(value:string)=>value.trim().replace(/\/+$/,""),asError=async(response:Response)=>{let detail="";try{detail=JSON.stringify(await response.json())}catch{detail=await response.text().catch(()=>"")}if(response.status===401||response.status===403)throw new ImageGenerationError("auth","生图服务鉴权失败，请检查密钥或订阅");if(response.status===402||response.status===429)throw new ImageGenerationError("quota","生图服务额度不足或请求过于频繁");throw new ImageGenerationError("response",`生图服务返回 ${response.status}${detail?`：${detail.slice(0,180)}`:""}`)};
async function fetchSafe(url:string,init:RequestInit){try{return await fetch(url,init)}catch(error){const text=error instanceof Error?error.message:String(error);throw new ImageGenerationError(/cors|failed to fetch/i.test(text)?"cors":"network",/cors|failed to fetch/i.test(text)?"浏览器无法跨域访问该生图服务":"无法连接生图服务")}}
function dataUrlBlob(data:string){const [head,body]=data.split(","),mime=/data:([^;]+)/.exec(head)?.[1]??"image/png",bytes=Uint8Array.from(atob(body),c=>c.charCodeAt(0));return new Blob([bytes],{type:mime})}
async function openAI(settings:ImageGenerationSettings["openai"],request:ImageGenerationRequest):Promise<ImageGenerationResult>{if(!settings.enabled||!settings.apiKey.trim())throw new ImageGenerationError("config","请先启用并配置 GPT/OpenAI 生图服务");const prompt=[request.prompt,settings.positivePrompt?`Rendering preference only: ${settings.positivePrompt}`:"",settings.negativePrompt?`Avoid: ${settings.negativePrompt}`:"",request.negativePrompt?`Avoid: ${request.negativePrompt}`:""].filter(Boolean).join("\n");const headers={Authorization:`Bearer ${settings.apiKey.trim()}`};let response:Response;if(request.referenceDataUrl){const form=new FormData();form.set("model",settings.model);form.set("prompt",prompt);form.set("size",settings.size);form.set("quality",settings.quality);form.set("image",dataUrlBlob(request.referenceDataUrl),"reference.png");response=await fetchSafe(`${cleanBase(settings.baseUrl)}/images/edits`,{method:"POST",headers,body:form})}else response=await fetchSafe(`${cleanBase(settings.baseUrl)}/images/generations`,{method:"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({model:settings.model,prompt,n:1,size:settings.size,quality:settings.quality,response_format:"b64_json"})});if(!response.ok)await asError(response);const raw=await response.json(),parsed=z.object({data:z.array(z.object({b64_json:z.string().optional(),url:z.string().url().optional()})).min(1)}).parse(raw),image=parsed.data[0];if(image.b64_json)return{dataUrl:`data:image/png;base64,${image.b64_json}`,provider:"openai",model:settings.model};if(image.url){const file=await fetchSafe(image.url,{});if(!file.ok)await asError(file);return{dataUrl:await blobToDataUrl(await file.blob()),provider:"openai",model:settings.model}}throw new ImageGenerationError("response","生图服务没有返回图片")}
async function unzipFirst(buffer:ArrayBuffer,mime="image/png"){const view=new DataView(buffer);if(view.getUint32(0,true)!==0x04034b50)return blobToDataUrl(new Blob([buffer],{type:mime}));const method=view.getUint16(8,true),size=view.getUint32(18,true),nameLen=view.getUint16(26,true),extraLen=view.getUint16(28,true),start=30+nameLen+extraLen,chunk=buffer.slice(start,start+size);if(method===0)return blobToDataUrl(new Blob([chunk],{type:mime}));if(method===8&&typeof DecompressionStream!=="undefined"){const stream=new Blob([chunk]).stream().pipeThrough(new DecompressionStream("deflate-raw"));return blobToDataUrl(await new Response(stream).blob())}throw new ImageGenerationError("response","当前浏览器无法解压 NovelAI 图片响应")}
async function novelAI(settings:ImageGenerationSettings["novelai"],request:ImageGenerationRequest):Promise<ImageGenerationResult>{if(!settings.enabled||!settings.apiKey.trim())throw new ImageGenerationError("config","请先启用并配置 NovelAI 生图服务");const seed=Math.floor(Math.random()*2_147_483_647),response=await fetchSafe(`${cleanBase(settings.baseUrl)}/ai/generate-image`,{method:"POST",headers:{Authorization:`Bearer ${settings.apiKey.trim()}`,"Content-Type":"application/json"},body:JSON.stringify({input:[request.prompt,settings.positivePrompt,request.referenceDataUrl?"Use the supplied character appearance description consistently":""].filter(Boolean).join(", "),model:settings.model,action:"generate",parameters:{params_version:3,width:settings.width,height:settings.height,scale:settings.scale,sampler:settings.sampler,steps:settings.steps,n_samples:1,seed,uc:[settings.negativePrompt,request.negativePrompt].filter(Boolean).join(", "),qualityToggle:true,sm:true,sm_dyn:true}})});if(!response.ok)await asError(response);return{dataUrl:await unzipFirst(await response.arrayBuffer(),response.headers.get("content-type")??"image/png"),provider:"novelai",model:settings.model}}
export async function generateImage(settings:ImageGenerationSettings,request:ImageGenerationRequest){return settings.provider==="novelai"?novelAI(settings.novelai,request):openAI(settings.openai,request)}
export async function testImageGeneration(settings:ImageGenerationSettings){return generateImage(settings,{prompt:"A simple white ceramic teacup on a clean neutral background, soft daylight"})}
