import {db} from "./db";
import {normalizeLoreMount,uniqueLoreName} from "./lore";
import {now,uid,type Character,type Conversation,type LoreBook,type LoreMount} from "./types";

function materializedCharacterIds(character:Character,books:LoreBook[]){if(character.loreBookIds!==undefined)return[...character.loreBookIds];return books.filter(book=>book.mount?.mode!=="none").map(book=>book.id)}
function setMembership(ids:string[],bookId:string,include:boolean){const next=new Set(ids);include?next.add(bookId):next.delete(bookId);return[...next]}
function mountIncludesCharacter(mount:LoreMount,id:string){return mount.mode==="global"||(mount.mode==="selected"&&mount.characterIds.includes(id))}
function mountIncludesConversation(mount:LoreMount,id:string){return mount.mode==="global"||(mount.mode==="selected"&&mount.conversationIds.includes(id))}
export async function persistLoreMount(bookId:string,value:LoreMount){const mount=normalizeLoreMount(value)!;await db.transaction("rw",db.loreBooks,db.characters,db.conversations,async()=>{const [book,books,characters,conversations]=await Promise.all([db.loreBooks.get(bookId),db.loreBooks.toArray(),db.characters.toArray(),db.conversations.toArray()]);if(!book)throw new Error("世界书不存在");for(const character of characters){const loreBookIds=setMembership(materializedCharacterIds(character,books),bookId,mountIncludesCharacter(mount,character.id));await db.characters.update(character.id,{loreBookIds,updatedAt:now()})}for(const conversation of conversations){const loreBookIds=setMembership(conversation.loreBookIds,bookId,mountIncludesConversation(mount,conversation.id));await db.conversations.update(conversation.id,{loreBookIds,updatedAt:now()})}await db.loreBooks.update(bookId,{mount,updatedAt:now()})})}
export async function createLoreBook(book:LoreBook){await db.loreBooks.add(book);await persistLoreMount(book.id,book.mount??{mode:"none",characterIds:[],conversationIds:[]})}
export async function importLoreBooks(books:LoreBook[],mount:LoreMount,shelfGroupId?:string){const existing=await db.loreBooks.toArray(),names=existing.map(book=>book.name),created:LoreBook[]=[];for(const source of books){const name=uniqueLoreName(source.name,names);names.push(name);created.push({...source,id:uid(),name,createdAt:now(),updatedAt:now(),mount,shelfGroupId:shelfGroupId||undefined,entries:source.entries.map(entry=>({...entry,id:uid(),createdAt:entry.createdAt??now(),updatedAt:now()}))})}for(const book of created)await createLoreBook(book);return created}
export async function deleteLoreBook(bookId:string){await db.transaction("rw",db.loreBooks,db.characters,db.conversations,async()=>{const [characters,conversations]=await Promise.all([db.characters.toArray(),db.conversations.toArray()]);for(const character of characters)if(character.loreBookIds?.includes(bookId))await db.characters.update(character.id,{loreBookIds:character.loreBookIds.filter(id=>id!==bookId),updatedAt:now()});for(const conversation of conversations)if(conversation.loreBookIds.includes(bookId))await db.conversations.update(conversation.id,{loreBookIds:conversation.loreBookIds.filter(id=>id!==bookId),updatedAt:now()});await db.loreBooks.delete(bookId)})}
export type LoreBatchAction="enable"|"disable"|"delete"|"duplicate"|"move";
export async function batchLoreEntries(bookId:string,entryIds:string[],action:LoreBatchAction,targetBookId?:string){const selected=new Set(entryIds);if(!selected.size)return;await db.transaction("rw",db.loreBooks,async()=>{const source=await db.loreBooks.get(bookId);if(!source)throw new Error("世界书不存在");const picked=source.entries.filter(entry=>selected.has(entry.id)),timestamp=now();if(action==="enable"||action==="disable"){await db.loreBooks.update(bookId,{entries:source.entries.map(entry=>selected.has(entry.id)?{...entry,enabled:action==="enable",updatedAt:timestamp}:entry),updatedAt:timestamp});return}if(action==="delete"){await db.loreBooks.update(bookId,{entries:source.entries.filter(entry=>!selected.has(entry.id)),updatedAt:timestamp});return}if(action==="duplicate"){await db.loreBooks.update(bookId,{entries:[...source.entries,...picked.map(entry=>({...entry,id:uid(),title:`${entry.title||"未命名条目"} 副本`,createdAt:timestamp,updatedAt:timestamp}))],updatedAt:timestamp});return}if(action==="move"){if(!targetBookId||targetBookId===bookId)throw new Error("请选择其他世界书");const target=await db.loreBooks.get(targetBookId);if(!target)throw new Error("目标世界书不存在");const existingIds=new Set(target.entries.map(entry=>entry.id)),moving=picked.map(entry=>existingIds.has(entry.id)?{...entry,id:uid(),updatedAt:timestamp}:{...entry,updatedAt:timestamp});await db.loreBooks.update(target.id,{entries:[...target.entries,...moving],updatedAt:timestamp});await db.loreBooks.update(source.id,{entries:source.entries.filter(entry=>!selected.has(entry.id)),updatedAt:timestamp})}})}
export function mountSummary(book:LoreBook,characters:Character[],conversations:Conversation[]){if(book.mount?.mode==="global")return"全局生效";if(book.mount?.mode==="none")return"仅存书库";const characterCount=book.mount?.characterIds.length??characters.filter(character=>character.loreBookIds===undefined||character.loreBookIds.includes(book.id)).length,conversationCount=book.mount?.conversationIds.length??conversations.filter(conversation=>conversation.loreBookIds.includes(book.id)).length;return characterCount||conversationCount?`${characterCount} 个角色 · ${conversationCount} 个会话`:"仅存书库"}