import {db} from "./db";
import {compressImage} from "./imageAssets";
import {now,uid,type MediaAsset} from "./types";

export const MAX_CHAT_IMAGE_BYTES=1_000_000,MAX_STICKER_BYTES=1_000_000,MAX_FEED_IMAGE_BYTES=1_000_000,MAX_VOICE_BYTES=5_000_000,MAX_VOICE_DURATION_MS=60_000;
export async function saveImageMedia(file:File,purpose:"chat-image"|"feed-image"|"feed-reference"|"sticker"|"forum-avatar"|"forum-banner"|"forum-npc-avatar"|"forum-post-image"|"forum-profile-banner"|"forum-member-avatar"|"forum-member-banner"|"group-avatar"|"group-npc-avatar"):Promise<MediaAsset>{
 const sticker=purpose==="sticker",forum=purpose.startsWith("forum-"),max=sticker?MAX_STICKER_BYTES:purpose.startsWith("feed-")||forum?MAX_FEED_IMAGE_BYTES:MAX_CHAT_IMAGE_BYTES;
 const image=await compressImage(file,"widget",sticker?1024:purpose==="forum-avatar"||purpose==="forum-npc-avatar"||purpose==="forum-member-avatar"||purpose==="group-avatar"||purpose==="group-npc-avatar"?768:1920,max);
 const sizeBytes=Math.ceil((image.data.split(",")[1]?.length??0)*3/4),asset:MediaAsset={...image,purpose,sizeBytes};
 if(sizeBytes>max*1.1)throw new Error("图片压缩后仍然过大，请选择更小的图片");
 await db.mediaAssets.put(asset);return asset;
}
export async function blobToDataUrl(blob:Blob){return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)})}
export async function dataUrlToFile(data:string,name="generated.png"){const blob=await(await fetch(data)).blob();return new File([blob],name,{type:blob.type||"image/png"})}
export async function saveVoiceMedia(blob:Blob,durationMs:number):Promise<MediaAsset>{if(durationMs<=0||durationMs>MAX_VOICE_DURATION_MS)throw new Error("录音时长必须在 60 秒以内");if(blob.size>MAX_VOICE_BYTES)throw new Error("录音文件不能超过 5MB");const t=now(),asset:MediaAsset={id:uid(),createdAt:t,updatedAt:t,purpose:"voice",mimeType:blob.type||"audio/webm",sizeBytes:blob.size,data:await blobToDataUrl(blob),durationMs};await db.mediaAssets.put(asset);return asset}
export async function mediaUrl(assetId?:string){if(!assetId)return "";return (await db.mediaAssets.get(assetId))?.data??""}
export function displayDuration(durationMs=0){const seconds=Math.max(0,Math.round(durationMs/1000));return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`}
export async function deleteMediaIfUnused(assetId:string){const [messages,packs,posts,characters,conversations,forumServers,forumPosts]=await Promise.all([db.messages.toArray(),db.stickerPacks.toArray(),db.feedPosts.toArray(),db.characters.toArray(),db.conversations.toArray(),db.forumServers.toArray(),db.forumPosts.toArray()]);const usedByMessage=messages.some(message=>message.attachments?.some(a=>("assetId" in a)&&a.assetId===assetId)),usedByPack=packs.some(pack=>pack.stickers.some(sticker=>sticker.assetId===assetId)),usedByFeed=posts.some(post=>post.images?.some(image=>image.assetId===assetId)),usedByCharacter=characters.some(character=>character.chatSettings?.feedImage?.referenceAssetId===assetId||character.visualProfile?.lastAcceptedImageAssetId===assetId),usedByConversation=conversations.some(conversation=>conversation.avatarAssetId===assetId||(conversation.groupNpcs??[]).some(npc=>npc.avatarAssetId===assetId)),sourceUses=(source?:{type:string;value:string})=>source?.type==="asset"&&source.value===assetId,usedByForum=forumServers.some(server=>sourceUses(server.avatar)||sourceUses(server.banner)||sourceUses(server.userProfile?.banner)||(server.npcs??[]).some(npc=>sourceUses(npc.avatar))||Object.values(server.memberProfiles??{}).some(profile=>sourceUses(profile.avatar)||sourceUses(profile.banner))||(server.directThreads??[]).some(thread=>sourceUses(thread.participantAvatar)))||forumPosts.some(post=>sourceUses(post.authorAvatar)||(post.images??[]).some(image=>(image.source==="asset"||image.source==="sticker")&&image.assetId===assetId)||post.replies.some(reply=>sourceUses(reply.authorAvatar)));if(!usedByMessage&&!usedByPack&&!usedByFeed&&!usedByCharacter&&!usedByConversation&&!usedByForum)await db.mediaAssets.delete(assetId)}
