import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState,type ReactNode} from "react";
import {Pause,Play,SkipForward,Timer,X} from "lucide-react";
import {useNavigate} from "react-router-dom";
import {db,getSetting,setSetting} from "./db";
import {defaultMusicClientSettings,deleteMusicTrack,fetchNeteaseLyrics,isMusicTrackSaved,musicTrackUrl,parseLrc,recordMusicTrackPlayed,reportMusicPlayback,setMusicTrackFavorite,updateListeningPlayback,type ParsedLyricLine} from "./music";
import {formatSleepTimerRemaining,sleepFadeVolume,sleepTimerRemainingMs} from "./musicImmersive";
import {ensureMusicReportPreferences,recordMusicListeningMilestone,recordMusicListeningSegment} from "./musicReport";
import {normalizeListeningQueueEntries,scheduleMusicDjTurn,syncListeningQueue} from "./musicDj";
import type {ListeningSession,MusicClientSettings,MusicSleepTimer,MusicTrack} from "./types";

interface PersistedPlayer{queue:string[];index:number;positionMs:number;currentTrackId?:string}
interface ListeningTracker{track:MusicTrack;selectedBy:"user"|"character";lastPositionMs:number;lastWallAt:number;accumulatedMs:number;started:boolean;completed:boolean}
interface MusicPlayerValue{
 tracks:MusicTrack[];savedTracks:MusicTrack[];queue:string[];queueTracks:MusicTrack[];queueEntries:import("./types").ListeningQueueEntry[];currentTrack?:MusicTrack;currentIndex:number;playing:boolean;positionMs:number;durationMs:number;lyrics:ParsedLyricLine[];error?:string;activeSession?:ListeningSession;repeatMode:MusicClientSettings["repeatMode"];shuffle:boolean;volume:number;
 lyricsTranslationVisible:boolean;lyricsFontSize:NonNullable<MusicClientSettings["lyricsFontSize"]>;sleepTimer?:MusicSleepTimer;sleepTimerRemainingMs?:number;sleepTimerLabel:string;
 playTrack:(track:MusicTrack,queue?:MusicTrack[],selectedBy?:"user"|"character")=>Promise<void>;toggle:()=>Promise<void>;pause:()=>Promise<void>;next:()=>Promise<void>;previous:()=>Promise<void>;seek:(value:number)=>void;setQueue:(tracks:MusicTrack[])=>Promise<void>;playNext:(track:MusicTrack)=>Promise<void>;addToQueue:(track:MusicTrack)=>Promise<void>;removeFromQueue:(trackId:string)=>void;moveQueueItem:(from:number,to:number)=>void;clearQueue:()=>void;cycleRepeat:()=>void;toggleShuffle:()=>void;setVolume:(value:number)=>void;setLyricsTranslationVisible:(value:boolean)=>void;setLyricsFontSize:(value:NonNullable<MusicClientSettings["lyricsFontSize"]>)=>void;setSleepTimer:(value:MusicSleepTimer)=>void;cancelSleepTimer:()=>void;toggleFavorite:(trackId:string)=>Promise<void>;saveTrack:(trackId:string)=>Promise<void>;rememberTrack:(track:MusicTrack)=>Promise<void>;deleteTrack:(trackId:string)=>Promise<void>;reloadCurrent:()=>Promise<void>;stop:()=>void;refreshLibrary:()=>Promise<void>;
}
const MusicPlayerContext=createContext<MusicPlayerValue|null>(null);

export function MusicPlayerProvider({children}:{children:ReactNode}){
 const audioRef=useRef<HTMLAudioElement|undefined>(undefined),urlRef=useRef<{url:string;revoke:boolean}|undefined>(undefined),retryRef=useRef<string|undefined>(undefined),persistRef=useRef(0),recordedRef=useRef<{id?:string;at:number}>({at:0}),sleepFiringRef=useRef(false),listeningTrackerRef=useRef<ListeningTracker|undefined>(undefined),activeSessionRef=useRef<ListeningSession|undefined>(undefined);
 if(!audioRef.current&&typeof Audio!=="undefined")audioRef.current=new Audio();
 const [tracks,setTracks]=useState<MusicTrack[]>([]),[queue,setQueueIds]=useState<string[]>([]),[currentIndex,setCurrentIndex]=useState(0),[playing,setPlaying]=useState(false),[positionMs,setPositionMs]=useState(0),[durationMs,setDurationMs]=useState(0),[lyrics,setLyrics]=useState<ParsedLyricLine[]>([]),[error,setError]=useState<string|undefined>(undefined),[activeSession,setActiveSession]=useState<ListeningSession|undefined>(undefined),[repeatMode,setRepeatMode]=useState<MusicClientSettings["repeatMode"]>("off"),[shuffle,setShuffle]=useState(false),[volume,setVolumeState]=useState(.85),[lyricsTranslationVisible,setLyricsTranslationState]=useState(true),[lyricsFontSize,setLyricsFontSizeState]=useState<NonNullable<MusicClientSettings["lyricsFontSize"]>>("medium"),[sleepTimer,setSleepTimerState]=useState<MusicSleepTimer|undefined>(undefined),[sleepRemaining,setSleepRemaining]=useState<number|undefined>(undefined);
 const currentTrack=tracks.find(track=>track.id===queue[currentIndex]),queueTracks=queue.map(id=>tracks.find(track=>track.id===id)).filter(Boolean) as MusicTrack[],savedTracks=tracks.filter(isMusicTrackSaved),queueEntries=activeSession?normalizeListeningQueueEntries(activeSession):queue.map(trackId=>({trackId,selectedBy:"user" as const,addedAt:0}));
 const refreshLibrary=useCallback(async()=>setTracks(await db.musicTracks.orderBy("importedAt").reverse().toArray()),[]);
 const saveClientPatch=useCallback(async(patch:Partial<MusicClientSettings>)=>{const stored=await getSetting<Partial<MusicClientSettings>>("music-client",defaultMusicClientSettings);await setSetting("music-client",{...defaultMusicClientSettings,...stored,...patch})},[]);
 useEffect(()=>{void ensureMusicReportPreferences()},[]);
 const flushListeningProgress=useCallback((force=false)=>{const tracker=listeningTrackerRef.current,audio=audioRef.current;if(!tracker||!audio||(!force&&audio.paused))return;const stamp=Date.now(),position=Math.round(audio.currentTime*1000),wallDelta=Math.max(0,stamp-tracker.lastWallAt),positionDelta=position-tracker.lastPositionMs;if(!force&&wallDelta<15000)return;const listened=Math.max(0,Math.min(positionDelta,wallDelta+2000));tracker.lastPositionMs=position;tracker.lastWallAt=stamp;if(!listened)return;tracker.accumulatedMs+=listened;const session=activeSessionRef.current;void recordMusicListeningSegment({track:tracker.track,listenedMs:listened,startedAt:stamp-Math.min(wallDelta,listened),endedAt:stamp,characterId:session?.state==="active"?session.characterId:undefined});const threshold=tracker.track.durationMs?Math.min(30000,Math.max(1000,tracker.track.durationMs*.5)):30000;if(!tracker.started&&tracker.accumulatedMs>=threshold){tracker.started=true;void recordMusicListeningMilestone({track:tracker.track,at:stamp,kind:"start",characterId:session?.state==="active"?session.characterId:undefined,selectedBy:tracker.selectedBy})}},[]);
 const finishTrackedTrack=useCallback((outcome:"complete"|"skip")=>{flushListeningProgress(true);const tracker=listeningTrackerRef.current;if(!tracker)return;listeningTrackerRef.current=undefined;if(outcome==="complete"){tracker.completed=true;void recordMusicListeningMilestone({track:tracker.track,at:Date.now(),kind:"complete"})}else if(!tracker.completed)void recordMusicListeningMilestone({track:tracker.track,at:Date.now(),kind:"skip"})},[flushListeningProgress]);
 useEffect(()=>{activeSessionRef.current=activeSession},[activeSession]);
 useEffect(()=>{void Promise.all([refreshLibrary(),getSetting<PersistedPlayer>("music-player",{queue:[],index:0,positionMs:0}),getSetting<Partial<MusicClientSettings>>("music-client",defaultMusicClientSettings)]).then(([,saved,raw])=>{const settings={...defaultMusicClientSettings,...raw};setQueueIds(saved.queue);setCurrentIndex(Math.max(0,Math.min(saved.index,Math.max(0,saved.queue.length-1))));setPositionMs(saved.positionMs);setRepeatMode(settings.repeatMode);setShuffle(settings.shuffle);setVolumeState(settings.volume);setLyricsTranslationState(settings.lyricsTranslationVisible??true);setLyricsFontSizeState(settings.lyricsFontSize??"medium");setSleepTimerState(settings.sleepTimer);if(audioRef.current)audioRef.current.volume=settings.volume});const reload=()=>void refreshLibrary();window.addEventListener("mira:music-library-changed",reload);return()=>window.removeEventListener("mira:music-library-changed",reload)},[refreshLibrary]);
 const persist=useCallback((force=false)=>{const stamp=Date.now();if(!force&&stamp-persistRef.current<4000)return;persistRef.current=stamp;void setSetting("music-player",{queue,index:currentIndex,positionMs,currentTrackId:currentTrack?.id} satisfies PersistedPlayer)},[queue,currentIndex,positionMs,currentTrack?.id]);
 useEffect(()=>{const flush=()=>flushListeningProgress(true);document.addEventListener("visibilitychange",flush);window.addEventListener("pagehide",flush);return()=>{flush();persist(true);document.removeEventListener("visibilitychange",flush);window.removeEventListener("pagehide",flush);if(urlRef.current?.revoke)URL.revokeObjectURL(urlRef.current.url)}},[flushListeningProgress,persist]);
 useEffect(()=>{void setSetting("music-player",{queue,index:currentIndex,positionMs,currentTrackId:currentTrack?.id} satisfies PersistedPlayer)},[queue,currentIndex,currentTrack?.id]);
 useEffect(()=>{if(!currentTrack||audioRef.current?.src)return;setDurationMs(currentTrack.durationMs??0);if(currentTrack.customLyrics){if(currentTrack.lyricsKind==="plain")setLyrics(currentTrack.customLyrics.split(/\r?\n/).map(text=>text.trim()).filter(Boolean).map((text,index)=>({timeMs:index,text})));else setLyrics(parseLrc(currentTrack.customLyrics,currentTrack.customTranslatedLyrics))}else if(currentTrack.externalId)void fetchNeteaseLyrics(currentTrack.externalId).then(value=>setLyrics(parseLrc(value.lrc,value.translatedLrc))).catch(()=>setLyrics([]));else setLyrics([])},[currentTrack?.customLyrics,currentTrack?.customTranslatedLyrics,currentTrack?.durationMs,currentTrack?.externalId,currentTrack?.id,currentTrack?.lyricsKind]);
 const syncActiveQueue=useCallback((nextQueue:string[],index:number,eventType?:"queue-add"|"queue-remove",trackId?:string)=>{void db.listeningSessions.where("state").equals("active").first().then(session=>session?syncListeningQueue({sessionId:session.id,queue:nextQueue,currentIndex:index,actor:"user",eventType,changedTrackId:trackId}):undefined).then(session=>{if(session)setActiveSession(session)})},[]);
 const persistIncoming=useCallback(async(values:MusicTrack[])=>{if(!values.length)return values;const existing=await db.musicTracks.bulkGet(values.map(item=>item.id)),stamp=Date.now(),stored=values.map((item,index)=>{const old=existing[index];return{...item,libraryStatus:old?.libraryStatus??item.libraryStatus??(item.source==="netease"?"temporary":"saved"),favorite:old?.favorite??item.favorite,lastPlayedAt:old?.lastPlayedAt??item.lastPlayedAt,playCount:old?.playCount??item.playCount,customLyrics:old?.customLyrics??item.customLyrics,customTranslatedLyrics:old?.customTranslatedLyrics??item.customTranslatedLyrics,lyricsKind:old?.lyricsKind??item.lyricsKind,createdAt:old?.createdAt??item.createdAt??stamp,updatedAt:stamp,importedAt:old?.importedAt??item.importedAt??stamp}});await db.musicTracks.bulkPut(stored);setTracks(current=>{const map=new Map(current.map(item=>[item.id,item]));stored.forEach(item=>map.set(item.id,item));return[...map.values()]});return stored},[]);
 const clearSleepTimer=useCallback((restore=true)=>{sleepFiringRef.current=false;setSleepTimerState(undefined);setSleepRemaining(undefined);if(restore&&audioRef.current)audioRef.current.volume=volume;void saveClientPatch({sleepTimer:undefined})},[saveClientPatch,volume]);
 const pausePlayback=useCallback(async(actor:"user"|"character"|"system"="user")=>{const audio=audioRef.current;if(!audio)return;flushListeningProgress(true);audio.pause();const session=activeSession??await db.listeningSessions.where("state").equals("active").first();if(session){const updated=await updateListeningPlayback(session.id,{playbackState:"paused",positionMs:Math.round(audio.currentTime*1000)},"pause",actor);if(updated)setActiveSession(updated)}},[activeSession,flushListeningProgress]);
 const finishSleepTimer=useCallback(async()=>{if(sleepFiringRef.current)return;sleepFiringRef.current=true;if(audioRef.current)audioRef.current.volume=0;await pausePlayback("system");clearSleepTimer(true);window.dispatchEvent(new CustomEvent("mira:music-sleep-timer-finished",{detail:{message:"睡眠定时已结束，音乐已渐弱暂停"}}))},[clearSleepTimer,pausePlayback]);
 const cancelSleepTimer=useCallback(()=>clearSleepTimer(true),[clearSleepTimer]);
 const setSleepTimer=useCallback((value:MusicSleepTimer)=>{sleepFiringRef.current=false;setSleepTimerState(value);const remaining=sleepTimerRemainingMs(value,Date.now(),currentTrack?.id,positionMs,durationMs);setSleepRemaining(remaining);if(audioRef.current)audioRef.current.volume=sleepFadeVolume(volume,remaining);void saveClientPatch({sleepTimer:value})},[currentTrack?.id,durationMs,positionMs,saveClientPatch,volume]);
 const loadTrack=useCallback(async(track:MusicTrack,autoplay=true,selectedBy:"user"|"character"="user",resumeAt=0)=>{const audio=audioRef.current;if(!audio)return;if(listeningTrackerRef.current&&listeningTrackerRef.current.track.id!==track.id)finishTrackedTrack("skip");if(sleepTimer?.mode==="track-end"&&sleepTimer.trackId!==track.id){clearSleepTimer(true);window.dispatchEvent(new CustomEvent("mira:music-sleep-timer-cancelled",{detail:{message:"已切换歌曲，本曲播完定时已取消"}}))}setError(undefined);audio.pause();if(urlRef.current?.revoke)URL.revokeObjectURL(urlRef.current.url);const resolved=await musicTrackUrl(track);urlRef.current=resolved;audio.src=resolved.url;audio.preload="auto";audio.volume=volume;retryRef.current=undefined;setPositionMs(resumeAt);setDurationMs(track.durationMs??0);setLyrics([]);audio.onloadedmetadata=()=>{if(resumeAt>0&&Number.isFinite(audio.duration))audio.currentTime=Math.min(resumeAt/1000,Math.max(0,audio.duration-1));setDurationMs(Number.isFinite(audio.duration)?Math.round(audio.duration*1000):track.durationMs??0)};if(track.customLyrics){if(track.lyricsKind==="plain")setLyrics(track.customLyrics.split(/\r?\n/).map(text=>text.trim()).filter(Boolean).map((text,index)=>({timeMs:index,text})));else setLyrics(parseLrc(track.customLyrics,track.customTranslatedLyrics))}else if(track.externalId)void fetchNeteaseLyrics(track.externalId).then(value=>setLyrics(parseLrc(value.lrc,value.translatedLrc))).catch(()=>setLyrics([]));if("mediaSession" in navigator)navigator.mediaSession.metadata=new MediaMetadata({title:track.title,artist:track.artists.join(" / "),album:track.album??"",artwork:track.coverUrl?[{src:track.coverUrl}]:[]});const session=await db.listeningSessions.where("state").equals("active").first()??undefined;setActiveSession(session);activeSessionRef.current=session;if(!listeningTrackerRef.current||listeningTrackerRef.current.track.id!==track.id)listeningTrackerRef.current={track,selectedBy,lastPositionMs:resumeAt,lastWallAt:Date.now(),accumulatedMs:0,started:false,completed:false};else{listeningTrackerRef.current.track=track;listeningTrackerRef.current.selectedBy=selectedBy;listeningTrackerRef.current.lastPositionMs=resumeAt;listeningTrackerRef.current.lastWallAt=Date.now()}if(session)await updateListeningPlayback(session.id,{currentTrackId:track.id,positionMs:resumeAt,playbackState:autoplay?"playing":"paused",selectedBy},"track-change",selectedBy);if(track.externalId)void reportMusicPlayback(track.externalId,"start",resumeAt);if(autoplay){await audio.play();const stamp=Date.now();if(recordedRef.current.id!==track.id||stamp-recordedRef.current.at>30000){recordedRef.current={id:track.id,at:stamp};void recordMusicTrackPlayed(track.id,stamp)}}},[clearSleepTimer,finishTrackedTrack,sleepTimer,volume]);
 const playTrack=useCallback(async(track:MusicTrack,nextQueue?:MusicTrack[],selectedBy:"user"|"character"="user")=>{const values=nextQueue?.length?nextQueue:[track],stored=await persistIncoming(values),storedTrack=stored.find(item=>item.id===track.id)??track;let ids=queue;if(nextQueue?.length){ids=stored.map(item=>item.id);setQueueIds(ids)}else if(!ids.includes(storedTrack.id)){ids=[...ids,storedTrack.id];setQueueIds(ids)}const index=Math.max(0,ids.indexOf(storedTrack.id));setCurrentIndex(index);if(selectedBy==="user")syncActiveQueue(ids,index);await loadTrack(storedTrack,true,selectedBy)},[loadTrack,persistIncoming,queue,syncActiveQueue]);
 const playIndex=useCallback(async(index:number)=>{if(!queue.length)return;const safe=(index+queue.length)%queue.length,track=tracks.find(item=>item.id===queue[safe]);if(!track)return;setCurrentIndex(safe);const selectedBy=activeSession?normalizeListeningQueueEntries(activeSession)[safe]?.selectedBy??"user":"user";await loadTrack(track,true,selectedBy)},[activeSession,loadTrack,queue,tracks]);
 const next=useCallback(async()=>{if(!queue.length)return;if(shuffle&&queue.length>1){let index=currentIndex;while(index===currentIndex)index=Math.floor(Math.random()*queue.length);await playIndex(index);return}if(currentIndex+1<queue.length)await playIndex(currentIndex+1);else if(repeatMode==="all")await playIndex(0);else await pausePlayback("user")},[currentIndex,pausePlayback,playIndex,queue.length,repeatMode,shuffle]);
 const previous=useCallback(async()=>{const audio=audioRef.current;if(audio&&audio.currentTime>5){audio.currentTime=0;setPositionMs(0);return}if(currentIndex>0||repeatMode==="all")await playIndex(currentIndex-1)},[currentIndex,playIndex,repeatMode]);
 const evaluateSleepTimer=useCallback(()=>{if(!sleepTimer)return;const audio=audioRef.current;if(sleepTimer.mode==="track-end"&&currentTrack&&sleepTimer.trackId!==currentTrack.id){clearSleepTimer(true);window.dispatchEvent(new CustomEvent("mira:music-sleep-timer-cancelled",{detail:{message:"已切换歌曲，本曲播完定时已取消"}}));return}const remaining=sleepTimerRemainingMs(sleepTimer,Date.now(),currentTrack?.id,positionMs,durationMs);setSleepRemaining(remaining);if(audio)audio.volume=sleepFadeVolume(volume,remaining);if(remaining!==undefined&&remaining<=0)void finishSleepTimer()},[clearSleepTimer,currentTrack,durationMs,finishSleepTimer,positionMs,sleepTimer,volume]);
 useEffect(()=>{if(!sleepTimer)return;evaluateSleepTimer();const id=window.setInterval(evaluateSleepTimer,250),onVisibility=()=>evaluateSleepTimer();document.addEventListener("visibilitychange",onVisibility);return()=>{window.clearInterval(id);document.removeEventListener("visibilitychange",onVisibility)}},[evaluateSleepTimer,sleepTimer]);
 useEffect(()=>{const audio=audioRef.current;if(!audio)return;const onTime=()=>{const nextPosition=Math.round(audio.currentTime*1000);setPositionMs(nextPosition);flushListeningProgress();if("mediaSession" in navigator&&Number.isFinite(audio.duration)&&audio.duration>0)try{navigator.mediaSession.setPositionState({duration:audio.duration,playbackRate:audio.playbackRate,position:Math.min(audio.currentTime,audio.duration)})}catch{}},onPlay=()=>{if(listeningTrackerRef.current){listeningTrackerRef.current.lastPositionMs=Math.round(audio.currentTime*1000);listeningTrackerRef.current.lastWallAt=Date.now()}setPlaying(true);if("mediaSession" in navigator)navigator.mediaSession.playbackState="playing"},onPause=()=>{flushListeningProgress(true);setPlaying(false);persist(true);if("mediaSession" in navigator)navigator.mediaSession.playbackState="paused"},onEnded=()=>{finishTrackedTrack("complete");if(currentTrack?.externalId)void reportMusicPlayback(currentTrack.externalId,"complete",durationMs);if(sleepTimer?.mode==="track-end"&&currentTrack?.id===sleepTimer.trackId)void finishSleepTimer();else if(repeatMode==="one"&&currentTrack)void loadTrack(currentTrack,true);else void next()},onError=()=>{if(currentTrack?.source==="netease"&&retryRef.current!==currentTrack.id){retryRef.current=currentTrack.id;window.setTimeout(()=>void loadTrack(currentTrack,true).catch(()=>void next()),500)}else{finishTrackedTrack("skip");setError("歌曲播放失败，已跳到下一首");window.setTimeout(()=>void next(),500)}};audio.addEventListener("timeupdate",onTime);audio.addEventListener("play",onPlay);audio.addEventListener("pause",onPause);audio.addEventListener("ended",onEnded);audio.addEventListener("error",onError);return()=>{audio.removeEventListener("timeupdate",onTime);audio.removeEventListener("play",onPlay);audio.removeEventListener("pause",onPause);audio.removeEventListener("ended",onEnded);audio.removeEventListener("error",onError)}},[currentTrack,durationMs,finishSleepTimer,finishTrackedTrack,flushListeningProgress,loadTrack,next,persist,repeatMode,sleepTimer]);
 const resumePlayback=useCallback(async()=>{const audio=audioRef.current;if(!audio)return;if(!audio.src&&currentTrack)await loadTrack(currentTrack,true,"user",positionMs);else await audio.play();const session=activeSession??await db.listeningSessions.where("state").equals("active").first();if(session){const updated=await updateListeningPlayback(session.id,{playbackState:"playing",positionMs:Math.round(audio.currentTime*1000)},"play","user");if(updated)setActiveSession(updated)}},[activeSession,currentTrack,loadTrack,positionMs]);
 const pause=useCallback(()=>pausePlayback("user"),[pausePlayback]);
 const toggle=useCallback(async()=>{const audio=audioRef.current;if(!audio)return;if(audio.paused)await resumePlayback();else await pause()},[pause,resumePlayback]);
 useEffect(()=>{if(!("mediaSession" in navigator))return;navigator.mediaSession.setActionHandler("play",()=>void resumePlayback());navigator.mediaSession.setActionHandler("pause",()=>void pause());navigator.mediaSession.setActionHandler("nexttrack",()=>void next());navigator.mediaSession.setActionHandler("previoustrack",()=>void previous());navigator.mediaSession.setActionHandler("seekto",details=>{if(details.seekTime!==undefined&&audioRef.current)audioRef.current.currentTime=details.seekTime})},[next,pause,previous,resumePlayback]);
 useEffect(()=>{const id=window.setInterval(()=>{persist();const session=activeSession,audio=audioRef.current;if(session&&audio){const position=Math.round(audio.currentTime*1000);void updateListeningPlayback(session.id,{positionMs:position,playbackState:audio.paused?"paused":"playing"}).then(updated=>{if(updated)setActiveSession(updated)});if(!audio.paused&&currentTrack)void scheduleMusicDjTurn(session.id,currentTrack.id,position)}},5000);return()=>window.clearInterval(id)},[activeSession,currentTrack,persist]);
 useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<{type:string;trackId?:string;placement?:"next"|"end";selectedBy?:"user"|"character"}>).detail;if(detail.type==="pause")void pausePlayback("character");else if(detail.type==="next")void next();else if(detail.type==="clear-queue"){audioRef.current?.pause();setQueueIds([]);setCurrentIndex(0);setPositionMs(0)}else if(detail.type==="queue-track"&&detail.trackId){const apply=(track:MusicTrack)=>setQueueIds(current=>{const at=detail.placement==="next"?Math.min(current.length,currentIndex+1):current.length;return[...current.slice(0,at),track.id,...current.slice(at)]}),track=tracks.find(item=>item.id===detail.trackId);if(track)apply(track);else void db.musicTracks.get(detail.trackId).then(value=>{if(value){setTracks(current=>current.some(item=>item.id===value.id)?current:[...current,value]);apply(value)}})}else if(detail.type==="play"&&detail.trackId){const run=(track:MusicTrack)=>void playTrack(track,undefined,detail.selectedBy??"character"),track=tracks.find(item=>item.id===detail.trackId);if(track)run(track);else void db.musicTracks.get(detail.trackId).then(value=>{if(value)run(value)})}};window.addEventListener("mira:music-action",handler);return()=>window.removeEventListener("mira:music-action",handler)},[currentIndex,next,pausePlayback,playTrack,tracks]);
 const seek=useCallback((value:number)=>{const audio=audioRef.current;if(!audio)return;flushListeningProgress(true);audio.currentTime=Math.max(0,value/1000);setPositionMs(value);if(listeningTrackerRef.current){listeningTrackerRef.current.lastPositionMs=value;listeningTrackerRef.current.lastWallAt=Date.now()}void setSetting("music-player",{queue,index:currentIndex,positionMs:value,currentTrackId:currentTrack?.id} satisfies PersistedPlayer);if(activeSession)void updateListeningPlayback(activeSession.id,{positionMs:value},"seek")},[activeSession,currentIndex,currentTrack?.id,flushListeningProgress,queue]);
 const setQueue=useCallback(async(value:MusicTrack[])=>{const stored=await persistIncoming(value),ids=stored.map(item=>item.id);setQueueIds(ids);setCurrentIndex(0);syncActiveQueue(ids,0)},[persistIncoming,syncActiveQueue]);
 const playNext=useCallback(async(track:MusicTrack)=>{const[stored]=await persistIncoming([track]);setQueueIds(current=>{const at=Math.min(current.length,currentIndex+1),nextQueue=[...current.slice(0,at),stored.id,...current.slice(at)];syncActiveQueue(nextQueue,currentIndex,"queue-add",stored.id);return nextQueue})},[currentIndex,persistIncoming,syncActiveQueue]);
 const addToQueue=useCallback(async(track:MusicTrack)=>{const[stored]=await persistIncoming([track]);setQueueIds(current=>{const nextQueue=[...current,stored.id];syncActiveQueue(nextQueue,currentIndex,"queue-add",stored.id);return nextQueue})},[currentIndex,persistIncoming,syncActiveQueue]);
 const removeFromQueue=useCallback((trackId:string)=>{setQueueIds(current=>{const index=current.indexOf(trackId),nextQueue=current.filter(id=>id!==trackId);if(index>=0&&index<currentIndex)setCurrentIndex(value=>Math.max(0,value-1));else if(index===currentIndex){audioRef.current?.pause();setPlaying(false);setPositionMs(0);setCurrentIndex(value=>Math.min(value,Math.max(0,nextQueue.length-1)))}syncActiveQueue(nextQueue,Math.min(currentIndex,Math.max(0,nextQueue.length-1)),"queue-remove",trackId);return nextQueue})},[currentIndex,syncActiveQueue]);
 const moveQueueItem=useCallback((from:number,to:number)=>{setQueueIds(current=>{if(from<0||to<0||from>=current.length||to>=current.length)return current;const nextQueue=[...current],[item]=nextQueue.splice(from,1);nextQueue.splice(to,0,item);const nextIndex=currentIndex===from?to:currentIndex>from&&currentIndex<=to?currentIndex-1:currentIndex<from&&currentIndex>=to?currentIndex+1:currentIndex;setCurrentIndex(nextIndex);syncActiveQueue(nextQueue,nextIndex);return nextQueue})},[currentIndex,syncActiveQueue]);
 const cycleRepeat=useCallback(()=>setRepeatMode(current=>{const nextMode=current==="off"?"all":current==="all"?"one":"off";void saveClientPatch({repeatMode:nextMode});return nextMode}),[saveClientPatch]);
 const toggleShuffle=useCallback(()=>setShuffle(current=>{const nextValue=!current;void saveClientPatch({shuffle:nextValue});return nextValue}),[saveClientPatch]);
 const setVolume=useCallback((value:number)=>{const nextValue=Math.max(0,Math.min(1,value));setVolumeState(nextValue);const remaining=sleepTimerRemainingMs(sleepTimer,Date.now(),currentTrack?.id,positionMs,durationMs);if(audioRef.current)audioRef.current.volume=sleepFadeVolume(nextValue,remaining);void saveClientPatch({volume:nextValue})},[currentTrack?.id,durationMs,positionMs,saveClientPatch,sleepTimer]);
 const setLyricsTranslationVisible=useCallback((value:boolean)=>{setLyricsTranslationState(value);void saveClientPatch({lyricsTranslationVisible:value})},[saveClientPatch]);
 const setLyricsFontSize=useCallback((value:NonNullable<MusicClientSettings["lyricsFontSize"]>)=>{setLyricsFontSizeState(value);void saveClientPatch({lyricsFontSize:value})},[saveClientPatch]);
 const stop=useCallback(()=>{finishTrackedTrack("skip");audioRef.current?.pause();if(audioRef.current)audioRef.current.src="";setQueueIds([]);setCurrentIndex(0);setPositionMs(0);setLyrics([]);if(urlRef.current?.revoke)URL.revokeObjectURL(urlRef.current.url);urlRef.current=undefined;clearSleepTimer(true);void setSetting("music-player",{queue:[],index:0,positionMs:0} satisfies PersistedPlayer)},[clearSleepTimer,finishTrackedTrack]);
 const clearQueue=useCallback(()=>{stop();syncActiveQueue([],0,"queue-remove",currentTrack?.id)},[currentTrack?.id,stop,syncActiveQueue]);
 const toggleFavorite=useCallback(async(trackId:string)=>{const track=tracks.find(item=>item.id===trackId)??await db.musicTracks.get(trackId);if(!track)return;await setMusicTrackFavorite(trackId,!track.favorite);await refreshLibrary()},[refreshLibrary,tracks]);
 const saveTrack=useCallback(async(trackId:string)=>{await db.musicTracks.update(trackId,{libraryStatus:"saved",updatedAt:Date.now()});window.dispatchEvent(new Event("mira:music-library-changed"));await refreshLibrary()},[refreshLibrary]);
 const rememberTrack=useCallback(async(track:MusicTrack)=>{await persistIncoming([{...track,libraryStatus:track.libraryStatus??"temporary"}])},[persistIncoming]);
 const deleteTrack=useCallback(async(trackId:string)=>{if(currentTrack?.id===trackId){if(queue.length>1)await next();else stop()}await deleteMusicTrack(trackId);setQueueIds(current=>current.filter(id=>id!==trackId));await refreshLibrary()},[currentTrack?.id,next,queue.length,refreshLibrary,stop]);
 const reloadCurrent=useCallback(async()=>{if(!currentTrack)return;const fresh=await db.musicTracks.get(currentTrack.id);if(!fresh)return;await refreshLibrary();await loadTrack(fresh,playing,"user",positionMs)},[currentTrack,loadTrack,playing,positionMs,refreshLibrary]);
 const sleepTimerLabel=formatSleepTimerRemaining(sleepTimer,sleepRemaining);
 const value=useMemo<MusicPlayerValue>(()=>({tracks,savedTracks,queue,queueTracks,queueEntries,currentTrack,currentIndex,playing,positionMs,durationMs,lyrics,error,activeSession,repeatMode,shuffle,volume,lyricsTranslationVisible,lyricsFontSize,sleepTimer,sleepTimerRemainingMs:sleepRemaining,sleepTimerLabel,playTrack,toggle,pause,next,previous,seek,setQueue,playNext,addToQueue,removeFromQueue,moveQueueItem,clearQueue,cycleRepeat,toggleShuffle,setVolume,setLyricsTranslationVisible,setLyricsFontSize,setSleepTimer,cancelSleepTimer,toggleFavorite,saveTrack,rememberTrack,deleteTrack,reloadCurrent,stop,refreshLibrary}),[tracks,savedTracks,queue,queueTracks,queueEntries,currentTrack,currentIndex,playing,positionMs,durationMs,lyrics,error,activeSession,repeatMode,shuffle,volume,lyricsTranslationVisible,lyricsFontSize,sleepTimer,sleepRemaining,sleepTimerLabel,playTrack,toggle,pause,next,previous,seek,setQueue,playNext,addToQueue,removeFromQueue,moveQueueItem,clearQueue,cycleRepeat,toggleShuffle,setVolume,setLyricsTranslationVisible,setLyricsFontSize,setSleepTimer,cancelSleepTimer,toggleFavorite,saveTrack,rememberTrack,deleteTrack,reloadCurrent,stop,refreshLibrary]);
 return <MusicPlayerContext.Provider value={value}>{children}</MusicPlayerContext.Provider>
}
export function useMusicPlayer(){const value=useContext(MusicPlayerContext);if(!value)throw new Error("MusicPlayerProvider is missing");return value}
export function GlobalMusicMiniPlayer(){const nav=useNavigate(),player=useMusicPlayer();if(!player.currentTrack)return null;return <div className={`global-music-mini${player.sleepTimer?" has-sleep-timer":""}`} role="region" aria-label="音乐播放器"><button className="global-music-main" onClick={()=>nav("/music")}><span className="music-cover-mini">{player.currentTrack.coverUrl?<img src={player.currentTrack.coverUrl} alt=""/>:"♪"}</span><span><b>{player.currentTrack.title}</b><small>{player.currentTrack.artists.join(" / ")}</small></span></button>{player.sleepTimer?<span className="global-music-timer" title={`睡眠定时：${player.sleepTimerLabel}`} aria-label={`睡眠定时剩余 ${player.sleepTimerLabel}`}><Timer aria-hidden="true"/><small>{player.sleepTimerLabel}</small></span>:null}<button aria-label={player.playing?"暂停":"播放"} onClick={()=>void player.toggle()}>{player.playing?<Pause/>:<Play/>}</button><button aria-label="下一首" onClick={()=>void player.next()}><SkipForward/></button><button aria-label="关闭播放器" onClick={player.stop}><X/></button></div>}
