import {z} from "zod";
import {coreSettingOf,personaOf} from "./character";
import {db,getAppSettings} from "./db";
import {OpenAIProvider} from "./provider";
import {userPersonaContext} from "./userPersona";
import {now,uid,type Character,type CharacterPhoneState,type PhoneContact,type ProviderSettings} from "./types";

const generatedContactSchema=z.object({name:z.string().min(1).max(80),relationship:z.string().min(1).max(160),persona:z.string().min(20).max(1600),status:z.string().max(200).default(""),phone:z.string().max(80).default(""),email:z.string().max(200).default(""),characterKnowledge:z.array(z.string().max(300)).max(12).default([]),firstAppearance:z.enum(["contact-only","talk","mail","call"]),talkMessage:z.string().max(2000).default(""),mailSubject:z.string().max(200).default(""),mailBody:z.string().max(5000).default(""),callDirection:z.enum(["incoming","outgoing","missed"]).default("incoming"),callSummary:z.string().max(500).default(""),callDetails:z.string().max(2000).default("")});
const cleanJson=(text:string)=>{const cleaned=text.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"");const start=cleaned.indexOf("{"),end=cleaned.lastIndexOf("}");return JSON.parse(start>=0&&end>start?cleaned.slice(start,end+1):cleaned)};
const normalizeIdentity=(value:string)=>value.normalize("NFKC").toLocaleLowerCase().replace(/[\s@._\-+()（）【】\[\]，,。.!！?？:：]/g,"");
export function stablePhoneEventRoll(eventId:string){let hash=2166136261;for(let index=0;index<eventId.length;index++){hash^=eventId.charCodeAt(index);hash=Math.imul(hash,16777619)}return(hash>>>0)/4294967296}
export function phoneNewContactProbability(input:{newEntityCount:number;sourceActivityCount:number}){return Math.min(.35,.15+(input.newEntityCount>0?.1:0)+Math.min(.1,Math.max(0,input.sourceActivityCount)*.02))}
export function phoneContactDuplicate(state:CharacterPhoneState,input:{name:string;email?:string;phone?:string}){const name=normalizeIdentity(input.name),email=normalizeIdentity(input.email??""),phone=normalizeIdentity(input.phone??"");return state.contacts.find(contact=>normalizeIdentity(contact.name)===name||Boolean(email&&normalizeIdentity(contact.email??"")===email)||Boolean(phone&&normalizeIdentity(contact.phone??"")===phone))}
export function touchPhoneContact(state:CharacterPhoneState,contactId:string,at=now()){const contact=state.contacts.find(item=>item.id===contactId);if(!contact)return;contact.lastInteractionAt=at;contact.interactionCount=(contact.interactionCount??0)+1;contact.updatedAt=at}
async function noveltySignals(character:Character,state:CharacterPhoneState,since:number){const [books,memories,meetSessions,orders,conversations]=await Promise.all([db.loreBooks.toArray(),db.memories.where("characterId").equals(character.id).toArray(),db.meetSessions.where("participantIds").equals(character.id).toArray(),db.mallOrders.toArray(),db.conversations.where("memberIds").equals(character.id).toArray()]),conversationIds=conversations.map(item=>item.id),messages=conversationIds.length?await db.messages.where("conversationId").anyOf(conversationIds).toArray():[],known=new Set(state.contacts.map(item=>normalizeIdentity(item.name))),candidateNames=books.filter(book=>book.enabled&&(character.loreBookIds?.includes(book.id)||book.mount?.mode==="global"||book.mount?.characterIds?.includes(character.id))).flatMap(book=>book.compiledContext?.entities?.map(entity=>entity.name)??[]).filter(name=>name&&normalizeIdentity(name)!==normalizeIdentity(character.name)&&!known.has(normalizeIdentity(name))).slice(0,20),recentMemories=memories.filter(item=>item.updatedAt>since),recentMeet=meetSessions.filter(item=>item.updatedAt>since),recentOrders=orders.filter(item=>item.updatedAt>since&&(item.recipientId===character.id||item.payerId===character.id||item.payerName===character.name||item.recipientName===character.name)),recentMessages=messages.filter(item=>item.createdAt>since),sourceActivityCount=recentMemories.length+recentMeet.length+recentOrders.length+Math.min(5,recentMessages.length);return{candidateNames:[...new Set(candidateNames)],sourceActivityCount,context:{memories:recentMemories.slice(-8).map(item=>({title:item.title,content:item.content})),meet:recentMeet.slice(-5).map(item=>({outline:item.scene?.outline,summary:item.summary,status:item.status})),orders:recentOrders.slice(-5).map(item=>({title:item.items.map(row=>row.title).join("、"),status:item.status,payer:item.payerName,recipient:item.recipientName})),messages:recentMessages.slice(-12).map(item=>({senderType:item.senderType,content:item.content}))}}}
function markContactRoll(state:CharacterPhoneState,eventId:string){state.proactiveState??={generationEventIds:[]};const marker=`contact-roll:${eventId}`;if(!state.proactiveState.generationEventIds.includes(marker))state.proactiveState.generationEventIds=[...state.proactiveState.generationEventIds,marker].slice(-160)}
function hasContactRoll(state:CharacterPhoneState,eventId:string){return state.proactiveState?.generationEventIds.includes(`contact-roll:${eventId}`)===true||state.contacts.some(item=>item.introducedEventId===eventId)}
function ensureCallContainer(state:CharacterPhoneState){const calls=(state.appContents.calls&&typeof state.appContents.calls==="object"?state.appContents.calls:{}) as any;if(!Array.isArray(calls.contacts))calls.contacts=[];if(!Array.isArray(calls.records))calls.records=[];state.appContents.calls=calls;return calls}
function addFirstAppearance(state:CharacterPhoneState,character:Character,contact:PhoneContact,value:z.infer<typeof generatedContactSchema>,eventId:string,t:number){if(value.firstAppearance==="talk"){const thread={id:uid(),contactId:contact.id,messages:[{id:uid(),senderType:"contact" as const,content:value.talkMessage||"你好，之前的事情想和你确认一下。",createdAt:t,generationEventId:`${eventId}:talk`}],updatedAt:t,unreadCount:1};state.talkThreads.push(thread);state.timeline.push({id:uid(),type:"talk",occurredAt:t,participantIds:[contact.id],summary:`新联系人 ${contact.name} 发来了 Talk`,generationEventId:`${eventId}:talk`})}else if(value.firstAppearance==="mail"){state.mail.messages.push({id:uid(),threadId:uid(),folder:"inbox",fromContactId:contact.id,fromAddress:contact.email??"contact@mail.local",toContactIds:[],toAddresses:[`${character.name}@mail.local`],subject:value.mailSubject||"关于最近的事情",body:value.mailBody||"想和你确认一下最近提到的事情。",sentAt:t,createdAt:t,updatedAt:t,generationEventId:`${eventId}:mail`});state.mail.unreadCount++;state.timeline.push({id:uid(),type:"mail",occurredAt:t,participantIds:[contact.id],summary:`收到了新联系人 ${contact.name} 的邮件`,generationEventId:`${eventId}:mail`})}else if(value.firstAppearance==="call"){const calls=ensureCallContainer(state);calls.records.push({contactName:contact.name,direction:value.callDirection,time:new Date(t).toISOString(),duration:value.callDirection==="missed"?"":"02:36",summary:value.callSummary||"第一次联系",details:value.callDetails||`${contact.name}因为近期发生的事情联系了${character.name}。`,transcript:value.callDirection==="missed"?[]:[{speaker:contact.name,content:value.callSummary||"有件事想和你确认。"},{speaker:character.name,content:"你说。"}]});state.timeline.push({id:uid(),type:"call",occurredAt:t,participantIds:[contact.id],summary:`与新联系人 ${contact.name} 产生了通话记录`,generationEventId:`${eventId}:call`})}const calls=ensureCallContainer(state);if(!calls.contacts.some((item:any)=>item.name===contact.name))calls.contacts.push({name:contact.name,relationship:contact.relationship,phoneLabel:contact.phone||"手机",about:contact.persona})}
export async function maybeIntroducePhoneContact(input:{state:CharacterPhoneState;character:Character;provider:ProviderSettings;eventId:string;since:number;origin:"lore"|"plot"|"proactive"}){const state=input.state;if(state.contacts.length>=40||hasContactRoll(state,input.eventId)||!input.provider.apiKey.trim())return state;const signals=await noveltySignals(input.character,state,input.since),probability=phoneNewContactProbability({newEntityCount:signals.candidateNames.length,sourceActivityCount:signals.sourceActivityCount});if(stablePhoneEventRoll(input.eventId)>=probability){markContactRoll(state,input.eventId);state.updatedAt=now();await db.characterPhoneStates.put(state);return state}const settings=await getAppSettings(),existing=state.contacts.map(contact=>({name:contact.name,relationship:contact.relationship,email:contact.email,phone:contact.phone})),prompt=`为虚构角色的手机生态创建 1 位真正的新联系人。不能复用或改名包装现有联系人，也不能把所有新人都写成对角色温柔示好的人。新人应来自角色合理的生活范围，可以是同事、老师、客户、同学、邻居、服务人员、旧识或关系紧张者。只允许知道其身份合理获知的信息。\n角色：${input.character.name}\n核心设定：${coreSettingOf(input.character)}\n完整人设：${personaOf(input.character)}\n背景：${input.character.background}\n${userPersonaContext(settings)}\n现有联系人（禁止重复）：${JSON.stringify(existing)}\n世界书候选人物：${JSON.stringify(signals.candidateNames)}\n本轮新增剧情来源：${JSON.stringify(signals.context)}\n返回严格 JSON：{"name":"姓名","relationship":"与角色的具体关系","persona":"独立人设、立场、边界和说话特点","status":"近况","phone":"虚构号码或标签","email":"虚构邮箱","characterKnowledge":["该联系人合理知道的内容"],"firstAppearance":"contact-only|talk|mail|call","talkMessage":"首次 Talk 内容","mailSubject":"首次邮件主题","mailBody":"首次邮件正文","callDirection":"incoming|outgoing|missed","callSummary":"通话摘要","callDetails":"通话内容"}。优先使用有依据的世界书或剧情人物；没有明确人物时，创建符合角色当前生活因果的陌生人。`;
 try{const raw=await new OpenAIProvider({...input.provider,stream:false}).chat([{role:"system",content:"你是茶茶机角色手机联系人导演，只输出严格 JSON，不暴露模型、API、提示词或生成过程。"},{role:"user",content:prompt}],{stream:false}),value=generatedContactSchema.parse(cleanJson(raw)),duplicate=phoneContactDuplicate(state,value);if(duplicate){markContactRoll(state,input.eventId);state.updatedAt=now();await db.characterPhoneStates.put(state);return state}const t=now(),contact:PhoneContact={id:uid(),name:value.name,relationship:value.relationship,persona:value.persona,status:value.status||undefined,phone:value.phone||undefined,email:value.email||`contact${state.contacts.length+1}@mail.local`,avatarText:value.name.slice(0,1),characterKnowledge:value.characterKnowledge,origin:signals.candidateNames.some(name=>normalizeIdentity(name)===normalizeIdentity(value.name))?"lore":input.origin,introducedEventId:input.eventId,introducedAt:t,lastInteractionAt:t,interactionCount:value.firstAppearance==="contact-only"?0:1,createdAt:t,updatedAt:t};state.contacts.push(contact);addFirstAppearance(state,input.character,contact,value,input.eventId,t);markContactRoll(state,input.eventId);state.updatedAt=t;await db.characterPhoneStates.put(state);return state}catch{return state}}
