import {db} from "./db";
import {PHONE_APPS,type PhoneAppId,type PhoneRiskLevel} from "./phoneCheck";
import {now,uid,type CharacterPhoneState,type PhoneRecentApp} from "./types";

export interface PhoneSearchResult{appId:PhoneAppId;targetId:string;title:string;subtitle:string;snippet:string;occurredAt?:number;risk:PhoneRiskLevel}
const text=(value:unknown)=>typeof value==="string"?value:"";
const normalize=(value:string)=>value.trim().toLocaleLowerCase();
const includes=(query:string,...values:unknown[])=>values.some(value=>normalize(text(value)).includes(query));
const riskOf=(appId:PhoneAppId)=>PHONE_APPS.find(item=>item.id===appId)?.risk??"medium";
const push=(results:PhoneSearchResult[],value:Omit<PhoneSearchResult,"risk">)=>results.push({...value,risk:riskOf(value.appId)});
export function normalizePhoneNavigationState(state:CharacterPhoneState){const next=structuredClone(state);next.searchState??={recentQueries:[]};next.recentApps??=[];next.recentApps=next.recentApps.filter(item=>PHONE_APPS.some(app=>app.id===item.appId)).sort((a,b)=>b.lastOpenedAt-a.lastOpenedAt).slice(0,6);next.contacts=next.contacts.map(contact=>({...contact,origin:contact.origin??"initial",interactionCount:contact.interactionCount??0,lastInteractionAt:contact.lastInteractionAt??contact.updatedAt}));return next}
export function buildPhoneSearchResults(state:CharacterPhoneState,rawQuery:string){const query=normalize(rawQuery);if(!query)return[];const results:PhoneSearchResult[]=[];
 for(const contact of state.contacts)if(includes(query,contact.name,contact.relationship,contact.persona,contact.status,contact.email,contact.phone,contact.characterKnowledge.join(" ")))push(results,{appId:"contacts",targetId:contact.id,title:contact.name,subtitle:contact.relationship,snippet:contact.status||contact.persona,occurredAt:contact.lastInteractionAt??contact.updatedAt});
 for(const thread of state.talkThreads){const contact=state.contacts.find(item=>item.id===thread.contactId);for(const message of thread.messages)if(includes(query,message.content,contact?.name,contact?.relationship))push(results,{appId:"messages",targetId:thread.contactId,title:contact?.name??"Talk",subtitle:"Talk 消息",snippet:message.content,occurredAt:message.createdAt})}
 for(const message of state.mail.messages)if(message.folder!=="trash"&&includes(query,message.subject,message.body,message.fromAddress,message.toAddresses.join(" "))){const contact=state.contacts.find(item=>item.id===message.fromContactId||message.toContactIds.includes(item.id));push(results,{appId:"mail",targetId:message.id,title:message.subject||"无主题",subtitle:contact?.name??message.fromAddress??"邮件",snippet:message.body,occurredAt:message.sentAt??message.updatedAt})}
 const calls=(state.appContents.calls as any)?.records;if(Array.isArray(calls))for(const [index,record] of calls.entries()){const contact=state.contacts.find(item=>item.name===record.contactName);if(includes(query,record.contactName,record.summary,record.details,JSON.stringify(record.transcript??[])))push(results,{appId:"calls",targetId:contact?.id??`call:${index}`,title:record.contactName||"通话",subtitle:record.summary||"通话记录",snippet:record.details||record.summary||"",occurredAt:Date.parse(record.time)||undefined})}
 const calendar=(state.appContents.calendar as any)?.events;if(Array.isArray(calendar))for(const [index,event] of calendar.entries())if(includes(query,event.title,event.note,event.category,event.date,event.time))push(results,{appId:"calendar",targetId:event.generationEventId??`calendar:${index}`,title:event.title||"日历事项",subtitle:`${event.date??""} ${event.time??""}`.trim(),snippet:event.note||event.category||"",occurredAt:Date.parse(`${event.date??""}T${event.time||"00:00"}`)||undefined});
 for(const place of state.maps.savedPlaces)if(includes(query,place.name,place.address,place.category,place.description))push(results,{appId:"maps",targetId:place.id,title:place.name,subtitle:place.category,snippet:place.address||place.description,occurredAt:state.maps.recentVisits.filter(item=>item.placeId===place.id).sort((a,b)=>b.visitedAt-a.visitedAt)[0]?.visitedAt});
 for(const reminder of state.reminders??[])if(includes(query,reminder.title,reminder.notes))push(results,{appId:"notes",targetId:reminder.id,title:reminder.title,subtitle:reminder.completed?"已完成":"提醒事项",snippet:reminder.notes,occurredAt:reminder.dueAt});
 for(const file of state.files?.items??[])if(!file.hidden&&file.kind!=="hidden"&&includes(query,file.name,file.folder,file.content))push(results,{appId:"files",targetId:file.id,title:file.name,subtitle:file.kind==="private"?"私人文件":file.folder,snippet:file.content,occurredAt:file.updatedAt});
 for(const memo of state.voiceMemos??[])if(includes(query,memo.title,memo.transcript,memo.category))push(results,{appId:"voice-memos",targetId:memo.id,title:memo.title,subtitle:"语音备忘录 · "+memo.duration,snippet:memo.transcript,occurredAt:memo.recordedAt});
 const browser=(state.appContents.browser as any)?.history;if(Array.isArray(browser))for(const [index,item] of browser.entries())if(includes(query,item.query,item.title,item.visitedAt))push(results,{appId:"browser",targetId:`browser:${index}`,title:item.query||"搜索记录",subtitle:"浏览记录",snippet:item.title||"",occurredAt:Date.parse(item.visitedAt)||undefined});
 for(const event of state.timeline)if(includes(query,event.summary)){const appId:PhoneAppId=event.type==="mail"?"mail":event.type==="call"?"calls":event.type==="calendar"?"calendar":event.type==="visit"?"maps":event.type==="purchase"?"wallet":event.type==="talk"?"messages":"notes";push(results,{appId,targetId:event.sourceId??event.id,title:event.summary,subtitle:"手机事件",snippet:event.summary,occurredAt:event.occurredAt})}
 const seen=new Set<string>();return results.filter(result=>{const key=`${result.appId}:${result.targetId}:${result.snippet}`;if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>(b.occurredAt??0)-(a.occurredAt??0)).slice(0,80)
}
export async function savePhoneSearchQuery(characterId:string,query:string){const state=await db.characterPhoneStates.get(characterId);if(!state||!query.trim())return state;const next=normalizePhoneNavigationState(state),value=query.trim(),t=now();next.searchState!.recentQueries=[{id:uid(),query:value,searchedAt:t},...next.searchState!.recentQueries.filter(item=>normalize(item.query)!==normalize(value))].slice(0,20);next.updatedAt=t;await db.characterPhoneStates.put(next);return next}
export async function recordRecentPhoneApp(characterId:string,appId:PhoneAppId,targetId?:string){const state=await db.characterPhoneStates.get(characterId);if(!state)return state;const next=normalizePhoneNavigationState(state),t=now(),existing=next.recentApps!.find(item=>item.appId===appId);const row:PhoneRecentApp=existing?{...existing,lastOpenedAt:t,openCount:existing.openCount+1,targetId}:{appId,lastOpenedAt:t,openCount:1,targetId};next.recentApps=[row,...next.recentApps!.filter(item=>item.appId!==appId)].slice(0,6);next.updatedAt=t;await db.characterPhoneStates.put(next);return next}
export async function removeRecentPhoneApp(characterId:string,appId:string){const state=await db.characterPhoneStates.get(characterId);if(!state)return state;const next=normalizePhoneNavigationState(state);next.recentApps=next.recentApps!.filter(item=>item.appId!==appId);next.updatedAt=now();await db.characterPhoneStates.put(next);return next}
export function recentAppSummary(state:CharacterPhoneState,row:PhoneRecentApp){const appId=row.appId as PhoneAppId,app=PHONE_APPS.find(item=>item.id===appId);if(appId==="messages"){const thread=state.talkThreads.find(item=>item.contactId===row.targetId)??state.talkThreads.slice().sort((a,b)=>b.updatedAt-a.updatedAt)[0],contact=state.contacts.find(item=>item.id===thread?.contactId);return{title:contact?.name??"Talk",subtitle:thread?.messages.at(-1)?.content??"没有最近消息",badge:thread?.unreadCount??0}}if(appId==="mail"){const message=state.mail.messages.find(item=>item.id===row.targetId)??state.mail.messages.filter(item=>item.folder!=="trash").sort((a,b)=>b.updatedAt-a.updatedAt)[0];return{title:message?.subject??"邮箱",subtitle:message?.body??"没有最近邮件",badge:state.mail.unreadCount}}if(appId==="files"){const file=state.files?.items.find(item=>item.id===row.targetId)??state.files?.items.slice().sort((a,b)=>b.updatedAt-a.updatedAt)[0];return{title:file?.name??"文件",subtitle:file?.folder??"最近文件"}}if(appId==="voice-memos"){const memo=state.voiceMemos?.find(item=>item.id===row.targetId)??state.voiceMemos?.slice().sort((a,b)=>b.recordedAt-a.recordedAt)[0];return{title:memo?.title??"语音备忘录",subtitle:memo?.transcript??"最近录音"}}if(appId==="notes")return{title:"提醒事项",subtitle:`${(state.reminders??[]).filter(item=>!item.completed).length} 项待完成`,badge:(state.reminders??[]).filter(item=>!item.completed).length};if(appId==="contacts"){const contact=state.contacts.find(item=>item.id===row.targetId)??state.contacts.slice().sort((a,b)=>(b.lastInteractionAt??0)-(a.lastInteractionAt??0))[0];return{title:contact?.name??"联系人",subtitle:contact?.relationship??"通讯录"}}return{title:app?.label??appId,subtitle:app?.subtitle??"最近打开"}}
