import {beforeEach,describe,expect,it,vi} from "vitest";
import {db} from "./db";
import {maybeAttachCharacterVoice,normalizeCharacterSpeech,normalizeSpeechSettings,resolveCharacterSpeech,SpeechProvider} from "./speech";
import {defaultProvider,defaultSpeechSettings,type Character,type Message} from "./types";

const base={enabled:true,apiKey:"key",baseUrl:"https://speech.test/v1",model:"model",defaultVoiceId:"voice",speed:1};
const character={id:"c",schemaVersion:1,createdAt:1,updatedAt:1,name:"茶茶",avatar:"",bio:"",personality:"温柔",speakingStyle:"自然",background:"",language:"中文",proactive:{messages:false,timeAware:false,frequency:"low",quietStart:"23:00",quietEnd:"08:00",catchupLimit:1,dailyLimit:1},relationship:{intimacy:10,trust:10,mood:"平静",recentEvents:[]},lastActiveAt:1} as Character;

describe("speech provider",()=>{
 beforeEach(async()=>{vi.restoreAllMocks();await db.delete();await db.open()});
 it("reads ElevenLabs binary audio with advanced voice settings",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(new Uint8Array([1,2,3]),{status:200,headers:{"Content-Type":"audio/mpeg"}})));const blob=await new SpeechProvider("elevenlabs",{...base,stability:.4,similarityBoost:.8,style:.2,useSpeakerBoost:true}).synthesize("你好");expect(blob.size).toBe(3);expect(fetch).toHaveBeenCalledWith(expect.stringContaining("/text-to-speech/voice"),expect.objectContaining({headers:expect.objectContaining({"xi-api-key":"key"}),body:expect.stringContaining("similarity_boost")}))});
 it("decodes MiniMax hex audio and sends advanced parameters",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({data:{audio:"010203"}}),{status:200,headers:{"Content-Type":"application/json"}})));const blob=await new SpeechProvider("minimax",{...base,volume:1.2,pitch:2,languageBoost:"Chinese"}).synthesize("你好");expect(blob.size).toBe(3);expect(fetch).toHaveBeenCalledWith(expect.stringContaining("/t2a_v2"),expect.objectContaining({headers:expect.objectContaining({Authorization:"Bearer key"}),body:expect.stringContaining("language_boost")}))});
 it("loads ElevenLabs voices and models",async()=>{vi.stubGlobal("fetch",vi.fn(async(url:string)=>url.endsWith("/voices")?new Response(JSON.stringify({voices:[{voice_id:"v1",name:"Alice",category:"premade"}]})):new Response(JSON.stringify([{model_id:"m1",name:"Multilingual",can_do_text_to_speech:true}]))));const provider=new SpeechProvider("elevenlabs",base);expect(await provider.listVoices()).toEqual([{id:"v1",name:"Alice",category:"premade",previewUrl:undefined}]);expect(await provider.listModels()).toEqual([{id:"m1",name:"Multilingual"}])});
 it("loads and deduplicates MiniMax voice groups",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({data:{system_voice:[{voice_id:"v1",voice_name:"系统音"}],voice_cloning:["v2"],voice_generation:["v2"]}}))));const voices=await new SpeechProvider("minimax",base).listVoices();expect(voices.map(item=>item.id)).toEqual(["v1","v2"])});
 it("normalizes legacy global and character settings",()=>{const global=normalizeSpeechSettings({defaultProvider:"elevenlabs",minimax:{...defaultSpeechSettings.minimax,speed:9},elevenlabs:{...defaultSpeechSettings.elevenlabs,stability:2}});expect(global.minimax.speed).toBe(2);expect(global.elevenlabs.stability).toBe(1);expect(normalizeCharacterSpeech(undefined).autoMessages).toMatchObject({enabled:false,tendency:"medium"});expect(resolveCharacterSpeech({...character,chatSettings:{language:"中文",contextLimit:30,stream:false,speech:{enabled:true,provider:"elevenlabs",voiceId:"role-voice"}}},normalizeSpeechSettings({...defaultSpeechSettings,elevenlabs:{...defaultSpeechSettings.elevenlabs,enabled:true,apiKey:"key",defaultVoiceId:"global"}}))?.settings.defaultVoiceId).toBe("role-voice")});
 it("resolves a character-selected speech preset independently",()=>{const preset={id:"preset-1",name:"月白低声",provider:"minimax" as const,settings:{...defaultSpeechSettings.minimax,enabled:true,apiKey:"preset-key",model:"preset-model",defaultVoiceId:"preset-voice"},createdAt:1,updatedAt:1},global=normalizeSpeechSettings({...defaultSpeechSettings,presets:[preset]}),configured={...character,chatSettings:{language:"中文" as const,contextLimit:30,stream:false,speech:{enabled:true,provider:"inherit" as const,presetId:preset.id}}};expect(resolveCharacterSpeech(configured,global)).toMatchObject({kind:"minimax",settings:{apiKey:"preset-key",model:"preset-model",defaultVoiceId:"preset-voice"},preset:{id:"preset-1"}})});
 it("enforces the daily tendency cap without calling a model",async()=>{const today=new Date().toLocaleDateString("en-CA"),row:Message={id:"m",schemaVersion:1,createdAt:1,updatedAt:1,conversationId:"v",senderType:"character",senderId:"c",content:"晚安",status:"complete",generation:{model:"model",temperature:1}},configured:Character={...character,chatSettings:{language:"中文",contextLimit:30,stream:false,speech:{enabled:true,provider:"inherit",autoMessages:{enabled:true,tendency:"low",dailyProgress:{date:today,count:1}}}}};await db.characters.put(configured);await db.messages.put(row);const result=await maybeAttachCharacterVoice({character:configured,messageIds:[row.id],provider:defaultProvider});expect(result.status).toBe("text");expect((await db.messages.get(row.id))?.generation?.voiceDecision).toBe("text")});
});