import mammoth from "mammoth";
import {db} from "./db";
import {now,SCHEMA_VERSION,uid,type StickerImportEntry,type StickerImportPreview,type StickerItem,type StickerPack} from "./types";

export const STICKER_DOCUMENT_ACCEPT=".txt,.docx,.md,.markdown,.csv,text/plain,text/markdown,text/csv,application/vnd.openxmlformats-officedocument.wordprocessingml.document";
export const MAX_STICKER_DOCUMENT_SIZE=10_000_000;
const imageFile=/^[A-Za-z0-9][A-Za-z0-9._%+()@-]*\.(?:png|jpe?g|gif|webp|avif)(?:[?#].*)?$/i;
export function stickerNameFromUrl(url:string){try{const name=decodeURIComponent(new URL(url).pathname.split("/").filter(Boolean).at(-1)??"");return name.replace(/\.[a-z0-9]+$/i,"")||"网络表情"}catch{return"网络表情"}}
function cleanUrl(value:string){return value.trim().replace(/[。，；、)\]}>]+$/g,"")}
function validUrl(value:string){try{const url=new URL(value);return url.protocol==="http:"||url.protocol==="https:"}catch{return false}}
function labelFrom(segment:string){const lines=segment.replace(/\r/g,"").split("\n").map(line=>line.trim()).filter(Boolean);let value=lines.at(-1)??"";value=value.replace(/^[-|,，;；:：\s]+|[-|,，;；:：\s]+$/g,"").replace(/^(?:name|title|description|含义|表情含义)\s*[:：]?\s*/i,"").trim();if(imageFile.test(value))return"";return value.slice(-120)}
function joinWrappedUrls(text:string){let value=text.replace(/\r\n?/g,"\n");for(let attempt=0;attempt<3;attempt++){const next=value.replace(/(https?:\/\/[^\s<>"']+\/)\s*\n\s*([A-Za-z0-9][A-Za-z0-9._%+()@-]*\.(?:png|jpe?g|gif|webp|avif)(?:[?#][^\s]*)?)/gi,"$1$2");if(next===value)break;value=next}return value}
export function parseStickerDocument(text:string):StickerImportPreview{const normalized=joinWrappedUrls(text).replace(/\u0000/g,"").trim(),warnings:string[]=[],ignoredLines:string[]=[];if(!normalized)return{entries:[],warnings:["导入文档为空"],ignoredLines:[]};const matches=[...normalized.matchAll(/https?:\/\/[^\s<>"']+/gi)],entries:StickerImportEntry[]=[],byUrl=new Map<string,StickerImportEntry>();let previousEnd=0;for(const match of matches){const raw=match[0],url=cleanUrl(raw),sourceLine=normalized.slice(0,match.index??0).split("\n").length;if(!validUrl(url)){warnings.push(`第 ${sourceLine} 行不是有效链接：${url}`);continue}const label=labelFrom(normalized.slice(previousEnd,match.index??0)),fallback=stickerNameFromUrl(url),entry:StickerImportEntry={url,name:(label||fallback).slice(0,40),description:(label||fallback).slice(0,120),sourceLine};const key=url.toLocaleLowerCase(),old=byUrl.get(key);if(!old){byUrl.set(key,entry);entries.push(entry)}else if(old.name===stickerNameFromUrl(old.url)&&label){old.name=entry.name;old.description=entry.description}previousEnd=(match.index??0)+raw.length}for(const [index,line]of normalized.split("\n").entries()){const trimmed=line.trim();if(!trimmed||/https?:\/\//i.test(trimmed)||imageFile.test(trimmed)||/[:：,，]/.test(trimmed))continue;ignoredLines.push(`第 ${index+1} 行：${trimmed.slice(0,120)}`)}if(!entries.length)warnings.push("没有识别到有效的 http 或 https 图片链接");if(entries.some(entry=>entry.name===stickerNameFromUrl(entry.url)))warnings.push("部分链接前没有含义说明，已使用图片文件名作为名称");return{entries,warnings:[...new Set(warnings)],ignoredLines:ignoredLines.slice(0,50)}}
export const parseStickerTxt=(text:string)=>parseStickerDocument(text).entries.map(entry=>entry.url);
export async function readStickerImportFile(file:File):Promise<StickerImportPreview>{const extension=file.name.toLowerCase().match(/\.[^.]+$/)?.[0]??"";if(![".txt",".docx",".md",".markdown",".csv"].includes(extension))throw new Error("只支持 TXT、DOCX、MD 或 CSV 表情文档");if(file.size>MAX_STICKER_DOCUMENT_SIZE)throw new Error("表情文档不能超过 10 MB");try{const text=extension===".docx"?(await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()})).value:await file.text();return parseStickerDocument(text)}catch(error){if(error instanceof Error&&/(?:只支持|10 MB)/.test(error.message))throw error;throw new Error(extension===".docx"?"无法读取这个 DOCX 文档":"无法读取这个表情文档")}}
export async function createStickerPack(name:string){const clean=name.trim();if(!clean)throw new Error("请输入分组名称");const t=now(),order=await db.stickerPacks.count(),pack:StickerPack={id:uid(),schemaVersion:SCHEMA_VERSION,createdAt:t,updatedAt:t,name:clean.slice(0,30),order,stickers:[]};await db.stickerPacks.add(pack);return pack}
export async function addStickerUrls(packId:string,values:Array<string|StickerImportEntry>){const pack=await db.stickerPacks.get(packId);if(!pack)throw new Error("表情分组不存在");const existing=new Set(pack.stickers.map(item=>item.url?.toLocaleLowerCase()).filter(Boolean)),start=pack.stickers.length,items:StickerItem[]=[];for(const value of values){const entry=typeof value==="string"?{url:value,name:stickerNameFromUrl(value),description:stickerNameFromUrl(value)}:value,key=entry.url.toLocaleLowerCase();if(existing.has(key)||!validUrl(entry.url))continue;existing.add(key);items.push({id:uid(),source:"url",url:entry.url,name:entry.name.trim().slice(0,40)||stickerNameFromUrl(entry.url),description:entry.description.trim().slice(0,120)||entry.name.trim().slice(0,40)||stickerNameFromUrl(entry.url),order:start+items.length})}if(items.length)await db.stickerPacks.update(packId,{stickers:[...pack.stickers,...items],updatedAt:now()});return items}
export async function addStickerAsset(packId:string,assetId:string,name:string){const pack=await db.stickerPacks.get(packId);if(!pack)throw new Error("表情分组不存在");const clean=name.trim()||"我的表情",item:StickerItem={id:uid(),source:"asset",assetId,name:clean,description:clean,order:pack.stickers.length};await db.stickerPacks.update(packId,{stickers:[...pack.stickers,item],updatedAt:now()});return item}
export async function updateSticker(packId:string,stickerId:string,patch:Partial<Pick<StickerItem,"name"|"description">>){const pack=await db.stickerPacks.get(packId);if(!pack)return;await db.stickerPacks.update(packId,{stickers:pack.stickers.map(s=>s.id===stickerId?{...s,...patch,name:(patch.name??s.name).trim()||s.name,description:(patch.description??s.description).trim()||s.description}:s),updatedAt:now()})}
