import {createHash,createPublicKey,generateKeyPairSync,randomBytes} from "node:crypto";
import {mkdir,readFile,writeFile} from "node:fs/promises";
import {spawnSync} from "node:child_process";
import path from "node:path";
import process from "node:process";

const ROOT=path.resolve(import.meta.dirname,"..");
const ENV_ID="matchaphone-d5gjgy87ybfb50382";
const COLLECTION="activation_codes";
const PRIVATE_DIR=path.join(ROOT,"private","activation");
const OUTPUT_DIR=path.join(ROOT,"outputs","activation-codes");
const PRIVATE_KEY_PATH=path.join(PRIVATE_DIR,"license-private-key.pem");
const PUBLIC_META_PATH=path.join(PRIVATE_DIR,"license-public.json");
const PUBLIC_TS_PATH=path.join(ROOT,"src","core","activationPublicKey.ts");
const CROCKFORD="23456789ABCDEFGHJKLMNPQRSTUVWXYZ";

function base64url(value){return Buffer.from(value).toString("base64url")}
function hash(value){return createHash("sha256").update(value).digest("hex")}
function normalizeCode(value){const compact=String(value??"").toUpperCase().replace(/[^A-Z0-9]/g,"");if(!compact.startsWith("MATCHA")||compact.length!==22)return "";return compact}
function displayCode(compact){const body=compact.slice(6);return `MATCHA-${body.match(/.{1,4}/g).join("-")}`}
function randomCode(){let body="";const bytes=randomBytes(16);for(let i=0;i<16;i++)body+=CROCKFORD[bytes[i]%CROCKFORD.length];return "MATCHA"+body}
function arg(name,fallback){const index=process.argv.indexOf(`--${name}`);return index>=0?process.argv[index+1]:fallback}
function tcb(args){const windowsCli=process.env.APPDATA?path.join(process.env.APPDATA,"npm","node_modules","@cloudbase","cli","bin","tcb"):"",command=process.platform==="win32"?process.execPath:"tcb",commandArgs=process.platform==="win32"?[windowsCli,...args]:args;const result=spawnSync(command,commandArgs,{cwd:ROOT,encoding:"utf8",windowsHide:true,maxBuffer:20*1024*1024});if(result.status!==0)throw new Error((result.error?.message||result.stderr||result.stdout||`tcb exited ${result.status}`).trim());const text=(result.stdout||"").trim();const start=text.indexOf("{");if(start<0)return{};return JSON.parse(text.slice(start))}
function execute(commands){return tcb(["db","nosql","execute","--command",JSON.stringify(commands),"--json"])}
async function keygen(){await mkdir(PRIVATE_DIR,{recursive:true});const {privateKey,publicKey}=generateKeyPairSync("ec",{namedCurve:"prime256v1",privateKeyEncoding:{type:"pkcs8",format:"pem"},publicKeyEncoding:{type:"spki",format:"pem"}});const publicObject=createPublicKey(publicKey);const publicJwk=publicObject.export({format:"jwk"});const spki=publicObject.export({format:"der",type:"spki"});const publicKeyId=base64url(createHash("sha256").update(spki).digest()).slice(0,22);await writeFile(PRIVATE_KEY_PATH,privateKey,{encoding:"utf8",mode:0o600});await writeFile(PUBLIC_META_PATH,JSON.stringify({publicKeyId,publicJwk,publicKeyPem:publicKey},null,2),"utf8");await writeFile(PUBLIC_TS_PATH,`export const ACTIVATION_PUBLIC_KEY_ID=${JSON.stringify(publicKeyId)};\nexport const ACTIVATION_LICENSE_PUBLIC_JWK=${JSON.stringify(publicJwk)} as JsonWebKey;\n`,"utf8");console.log(`Activation signing keys created. Public key id: ${publicKeyId}`);console.log(`Private key: ${PRIVATE_KEY_PATH}`)}
async function generate(countValue,batch){const count=Math.max(1,Math.min(1000,Number(countValue)||120)),createdAt=Date.now(),rows=[];for(let i=0;i<count;i++){const compact=randomCode(),code=displayCode(compact);rows.push({code,document:{_id:hash(compact),codeHash:hash(compact),codeSuffix:compact.slice(-4),batch,status:"unused",createdAt,updatedAt:createdAt}})}for(let i=0;i<rows.length;i+=20){const documents=rows.slice(i,i+20).map(row=>row.document);execute([{TableName:COLLECTION,CommandType:"INSERT",Command:JSON.stringify({insert:COLLECTION,documents})}])}await mkdir(OUTPUT_DIR,{recursive:true});const safeBatch=batch.replace(/[^A-Za-z0-9_-]/g,"_")||"beta";const file=path.join(OUTPUT_DIR,`${safeBatch}-${new Date(createdAt).toISOString().replace(/[:.]/g,"-")}.csv`);await writeFile(file,"code,batch,createdAt\n"+rows.map(row=>`${row.code},${safeBatch},${new Date(createdAt).toISOString()}`).join("\n")+"\n","utf8");console.log(`Generated ${rows.length} activation codes.`);console.log(`Private CSV: ${file}`)}
function numericValue(value){if(typeof value==="number")return value;if(typeof value==="string")return Number(value);if(value&&typeof value==="object"){const raw=value.$numberLong??value.$numberInt??value.$numberDouble;if(raw!==undefined)return Number(raw)}return NaN}
function queryAll(){const response=execute([{TableName:COLLECTION,CommandType:"QUERY",Command:JSON.stringify({find:COLLECTION,filter:{},sort:{createdAt:-1},limit:500})}]);const results=response?.data?.results;if(Array.isArray(results))return results.flatMap(item=>Array.isArray(item)?item:[]);const raw=response?.data?.[0]?.Result??response?.data?.[0]?.result??response?.data?.[0];if(typeof raw==="string")return JSON.parse(raw)?.documents??[];return raw?.documents??raw?.DocumentSet??[]}
async function list(){const rows=queryAll();console.table(rows.map(row=>({id:String(row._id).slice(0,10),batch:row.batch,suffix:row.codeSuffix,status:row.status,activatedAt:Number.isFinite(numericValue(row.activatedAt))?new Date(numericValue(row.activatedAt)).toLocaleString():"",device:String(row.deviceKeyHash??"").slice(0,12)})));console.log(`${rows.length} records`)}
async function disable(code){const compact=normalizeCode(code);if(!compact)throw new Error("Invalid activation code format");const codeHash=hash(compact),updatedAt=Date.now();execute([{TableName:COLLECTION,CommandType:"UPDATE",Command:JSON.stringify({update:COLLECTION,updates:[{q:{_id:codeHash,status:"unused"},u:{$set:{status:"disabled",updatedAt}}}]})}]);console.log(`Disabled unused code ending ${compact.slice(-4)}.`)}
async function replace(code){const compact=normalizeCode(code);if(!compact)throw new Error("Invalid activation code format");const oldHash=hash(compact),newCompact=randomCode(),newCode=displayCode(newCompact),createdAt=Date.now(),batch=arg("batch","replacement");execute([{TableName:COLLECTION,CommandType:"UPDATE",Command:JSON.stringify({update:COLLECTION,updates:[{q:{_id:oldHash},u:{$set:{status:"replaced",replacementCodeHash:hash(newCompact),updatedAt:createdAt}}}]})},{TableName:COLLECTION,CommandType:"INSERT",Command:JSON.stringify({insert:COLLECTION,documents:[{_id:hash(newCompact),codeHash:hash(newCompact),codeSuffix:newCompact.slice(-4),batch,status:"unused",replacesCodeHash:oldHash,createdAt,updatedAt:createdAt}]})}]);await mkdir(OUTPUT_DIR,{recursive:true});const file=path.join(OUTPUT_DIR,`replacement-${newCompact.slice(-4)}-${createdAt}.csv`);await writeFile(file,`code,batch,createdAt\n${newCode},${batch},${new Date(createdAt).toISOString()}\n`,"utf8");console.log(`Replacement code created for old code ending ${compact.slice(-4)}; new code ends ${newCompact.slice(-4)}.`);console.log(`Private CSV: ${file}`);console.warn("The old device keeps its permanent offline license and cannot be remotely revoked.")}
async function printDeploySecret(){const pem=await readFile(PRIVATE_KEY_PATH,"utf8");const meta=JSON.parse(await readFile(PUBLIC_META_PATH,"utf8"));console.log(JSON.stringify({ACTIVATION_LICENSE_PRIVATE_KEY:pem.replace(/\n/g,"\\n"),ACTIVATION_PUBLIC_KEY_ID:meta.publicKeyId}))}
const command=process.argv[2];try{if(command==="keygen")await keygen();else if(command==="generate")await generate(arg("count","120"),arg("batch","beta-1"));else if(command==="list")await list();else if(command==="disable")await disable(arg("code",""));else if(command==="replace")await replace(arg("code",""));else if(command==="print-deploy-secret")await printDeploySecret();else throw new Error("Usage: activation-admin.mjs <keygen|generate|list|disable|replace|print-deploy-secret>")}catch(error){console.error(error instanceof Error?error.message:String(error));process.exitCode=1}
